.TH "LIGHTNING-CHANNEL_RECEIVE_LIMIT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-receive-limit \- FEAT-922 channel-receive-limit
.SH SYNOPSIS
.B lightning channel-receive-limit
.SH DESCRIPTION
channel-receive-limit for lightning CLI (FEAT-922).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
