.TH "LIGHTNING-PEER-SPENDABLE-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-spendable-min \- FEAT-2593 verb
.SH SYNOPSIS
.B lightning peer-spendable-min
.SH DESCRIPTION
Peer with lowest total spendable_msat for lightning CLI (FEAT-2593).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
