.TH "LIGHTNING-WALLET_LABEL_DELETE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-label-delete \- FEAT-1228 wallet-label-delete
.SH SYNOPSIS
.B lightning wallet-label-delete
.SH DESCRIPTION
wallet-label-delete for lightning CLI (FEAT-1228).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
