.TH "LIGHTNING-NODE_LISTFORWARDS_BY_IN_CHANNEL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-by-in-channel \- FEAT-1129 node-listforwards-by-in-channel
.SH SYNOPSIS
.B lightning node-listforwards-by-in-channel
.SH DESCRIPTION
node-listforwards-by-in-channel for lightning CLI (FEAT-1129).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
