.TH "LIGHTNING-CHANNEL_THEIR_RESERVE_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-their-reserve-total \- FEAT-1652 channel-their-reserve-total
.SH SYNOPSIS
.B lightning channel-their-reserve-total
.SH DESCRIPTION
channel-their-reserve-total for lightning CLI (FEAT-1652).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
