.TH "LIGHTNING-PEER_LATENCY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-latency \- FEAT-877 peer-latency
.SH SYNOPSIS
.B lightning peer-latency
.SH DESCRIPTION
peer-latency for lightning CLI (FEAT-877).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
