.TH "LIGHTNING-CHANNEL_OPENER_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-opener-count \- FEAT-1852 channel-opener-count
.SH SYNOPSIS
.B lightning channel-opener-count
.SH DESCRIPTION
channel-opener-count for lightning CLI (FEAT-1852).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
