.TH "LIGHTNING-CHANNEL_HTLC_IN_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-in-count \- FEAT-706 channel-htlc-in-count verb
.SH SYNOPSIS
.B lightning channel-htlc-in-count
.SH DESCRIPTION
channel-htlc-in-count verb for lightning CLI (FEAT-706).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
