.TH "LIGHTNING-WALLET_BALANCE_LIGHTNING" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-balance-lightning \- FEAT-948 wallet-balance-lightning
.SH SYNOPSIS
.B lightning wallet-balance-lightning
.SH DESCRIPTION
wallet-balance-lightning for lightning CLI (FEAT-948).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
