.TH "LIGHTNING-PEER-LOCAL-RESERVE-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-local-reserve-total \- FEAT-2493 total our_reserve_msat across all channels
.SH SYNOPSIS
.B lightning peer-local-reserve-total
.SH DESCRIPTION
total our_reserve_msat across all channels for lightning CLI (FEAT-2493).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
