.TH "LIGHTNING-CHANNEL_CLOSE_TX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-tx \- FEAT-1132 channel-close-tx
.SH SYNOPSIS
.B lightning channel-close-tx
.SH DESCRIPTION
channel-close-tx for lightning CLI (FEAT-1132).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
