.TH "LIGHTNING-WALLET_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-count \- FEAT-653 wallet-count verb
.SH SYNOPSIS
.B lightning wallet-count
.SH DESCRIPTION
wallet-count verb for lightning CLI (FEAT-653).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
