.TH "LIGHTNING-INVOICE_AMOUNT_CHECK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-amount-check \- decode a BOLT11 and show its amount
.SH SYNOPSIS
.B lightning invoice-amount-check
.I bolt11
.SH DESCRIPTION
Decodes a BOLT11 invoice and returns its amount in msat and sat.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
