.TH "LIGHTNING-NODE_CHECK_ROUTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-check-route \- check if a route exists to a destination
.SH SYNOPSIS
.B lightning node-check-route
.SH DESCRIPTION
Check if a route exists to a destination.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
