.TH "LIGHTNING-INVOICE-CREATE-LNURL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-create-lnurl \- create an invoice and encode as LNURL
.SH SYNOPSIS
.B lightning invoice-create-lnurl
.I amount_msat label
.RI [ description ]
.SH DESCRIPTION
Creates a BOLT 11 invoice and encodes it as an LNURL string.
.PP
Output:
.nf
{"bolt11":..., "lnurl":..., "label":...}
.fi
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-invoice (1),
.BR lightning-node-lnurl-info (1)
