.TH "LIGHTNING-NODE-PAY-FEE-STATS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-fee-stats \- FEAT-2119 verb
.SH SYNOPSIS
.B lightning node-pay-fee-stats
.SH DESCRIPTION
Report min/max/avg fee paid for complete outgoing payments (FEAT-2119).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
