.TH "LIGHTNING-PEER_ROUTING_SCORE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-routing-score \- FEAT-997 peer-routing-score
.SH SYNOPSIS
.B lightning peer-routing-score
.SH DESCRIPTION
peer-routing-score for lightning CLI (FEAT-997).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
