.TH "LIGHTNING-CHANNEL_IN_PAYMENTS_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-in-payments-msat \- FEAT-1370 channel-in-payments-msat
.SH SYNOPSIS
.B lightning channel-in-payments-msat
.SH DESCRIPTION
channel-in-payments-msat for lightning CLI (FEAT-1370).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
