.TH "LIGHTNING-PEER-BALANCE-SKEWNESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-balance-skewness \- FEAT-3346 verb
.SH SYNOPSIS
.B lightning peer-balance-skewness
.SH DESCRIPTION
peer-balance-skewness for lightning CLI (FEAT-3346).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
