.TH "LIGHTNING-NODE_REBALANCE_STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-rebalance-status \- identify imbalanced channels needing rebalancing
.SH SYNOPSIS
.B lightning node-rebalance-status
.SH DESCRIPTION
Identify imbalanced channels needing rebalancing.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
