.TH "LIGHTNING-CHANNEL_STATE_TRANSITIONS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-state-transitions \- FEAT-972 channel-state-transitions
.SH SYNOPSIS
.B lightning channel-state-transitions
.SH DESCRIPTION
channel-state-transitions for lightning CLI (FEAT-972).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
