.TH "LIGHTNING-NODE_INVOICE_FALLBACK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-fallback \- create an invoice with an on-chain fallback address
.SH SYNOPSIS
.B lightning node-invoice-fallback
.SH DESCRIPTION
Create an invoice with an on-chain fallback address.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
