.TH "LIGHTNING-CHANNEL-HTLC-VALUE-MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-value-max \- FEAT-2482 channel with highest total HTLC value
.SH SYNOPSIS
.B lightning channel-htlc-value-max
.SH DESCRIPTION
Channel with highest total HTLC value (amount_msat sum) for lightning CLI (FEAT-2482).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
