.TH "LIGHTNING-NODE_LISTCHANNELS_BY_FEERATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-by-feerate \- FEAT-1354 node-listchannels-by-feerate
.SH SYNOPSIS
.B lightning node-listchannels-by-feerate
.SH DESCRIPTION
node-listchannels-by-feerate for lightning CLI (FEAT-1354).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
