.TH "LIGHTNING-CHANNEL-HTLC-EXPIRY-LATEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-expiry-latest \- FEAT-2512 channel with latest (highest) HTLC cltv_expiry
.SH SYNOPSIS
.B lightning channel-htlc-expiry-latest
.SH DESCRIPTION
Channel with latest (highest) HTLC cltv_expiry for lightning CLI (FEAT-2512).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
