.TH "LIGHTNING-NODE-LISTINVOICES-LABEL-LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listinvoices-label-list \- FEAT-2269 node-listinvoices-label-list
.SH SYNOPSIS
.B lightning node-listinvoices-label-list
.SH DESCRIPTION
node-listinvoices-label-list for lightning CLI (FEAT-2269).
.PP
Output: JSON from CLN listing all invoice labels.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
