.TH "LIGHTNING-PEER_CONNECTION_TIME" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-connection-time \- FEAT-917 peer-connection-time
.SH SYNOPSIS
.B lightning peer-connection-time
.SH DESCRIPTION
peer-connection-time for lightning CLI (FEAT-917).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
