.TH "LIGHTNING-NODE_GRAPH_UNREACHABLE_NODES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-unreachable-nodes \- FEAT-1669 node-graph-unreachable-nodes
.SH SYNOPSIS
.B lightning node-graph-unreachable-nodes
.SH DESCRIPTION
node-graph-unreachable-nodes for lightning CLI (FEAT-1669).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
