.TH "LIGHTNING-CHANNEL_HTLCS_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlcs-total \- FEAT-1080 channel-htlcs-total
.SH SYNOPSIS
.B lightning channel-htlcs-total
.SH DESCRIPTION
channel-htlcs-total for lightning CLI (FEAT-1080).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
