.TH "LIGHTNING-INVOICE_PAID_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-paid-count \- FEAT-684 invoice-paid-count verb
.SH SYNOPSIS
.B lightning invoice-paid-count
.SH DESCRIPTION
invoice-paid-count verb for lightning CLI (FEAT-684).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
