.TH "LIGHTNING-NODE_ONCHAIN_BALANCE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-onchain-balance \- FEAT-909 node-onchain-balance
.SH SYNOPSIS
.B lightning node-onchain-balance
.SH DESCRIPTION
node-onchain-balance for lightning CLI (FEAT-909).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
