.TH "LIGHTNING-NODE-INVOICE-COUNT-WEEKLY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-count-weekly \- FEAT-3358 verb
.SH SYNOPSIS
.B lightning node-invoice-count-weekly
.SH DESCRIPTION
node-invoice-count-weekly for lightning CLI (FEAT-3358).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
