.TH "LIGHTNING-NODE_LISTPAYS_BY_STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-by-status \- FEAT-1801 node-listpays-by-status
.SH SYNOPSIS
.B lightning node-listpays-by-status
.SH DESCRIPTION
node-listpays-by-status for lightning CLI (FEAT-1801).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
