.TH "LIGHTNING-WALLET-RECOVER" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-recover \- check wallet database integrity
.SH SYNOPSIS
.B lightning wallet-recover
.I wallet_name
.SH DESCRIPTION
Runs SQLite PRAGMA integrity_check on the wallet database and returns the result.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-wallet-archive (1),
.BR lightning-wallet-stats (1)
