.TH "LIGHTNING-NODE-INVOICE-PAID-AMOUNT-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-paid-amount-total \- FEAT-2464 total amount_msat of paid invoices
.SH SYNOPSIS
.B lightning node-invoice-paid-amount-total
.SH DESCRIPTION
total amount_msat of paid invoices for lightning CLI (FEAT-2464).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
