.TH "LIGHTNING-CHANNEL_TOTAL_HTLC_OUT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-total-htlc-out \- FEAT-1462 channel-total-htlc-out
.SH SYNOPSIS
.B lightning channel-total-htlc-out
.SH DESCRIPTION
channel-total-htlc-out for lightning CLI (FEAT-1462).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
