.TH "LIGHTNING-WALLET_META_DELETE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-meta-delete \- FEAT-1658 wallet-meta-delete
.SH SYNOPSIS
.B lightning wallet-meta-delete
.SH DESCRIPTION
wallet-meta-delete for lightning CLI (FEAT-1658).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
