.TH "LIGHTNING-CHANNEL-LOCAL-BALANCE-PCT-LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-local-balance-pct-list \- FEAT-2208 verb
.SH SYNOPSIS
.B lightning channel-local-balance-pct-list
.SH DESCRIPTION
Lists the local balance percentage for all peer channels (FEAT-2208).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
