.TH "LIGHTNING-CHANNEL_SPENDABLE_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-spendable-total \- FEAT-932 channel-spendable-total
.SH SYNOPSIS
.B lightning channel-spendable-total
.SH DESCRIPTION
channel-spendable-total for lightning CLI (FEAT-932).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
