.TH "LIGHTNING-CHANNEL_TYPE_FEATURES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-type-features \- FEAT-1596 channel-type-features
.SH SYNOPSIS
.B lightning channel-type-features
.SH DESCRIPTION
channel-type-features for lightning CLI (FEAT-1596).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
