.TH "LIGHTNING-WALLET_BALANCE_CONFIRMED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-balance-confirmed \- FEAT-1118 wallet-balance-confirmed
.SH SYNOPSIS
.B lightning wallet-balance-confirmed
.SH DESCRIPTION
wallet-balance-confirmed for lightning CLI (FEAT-1118).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
