.TH "LIGHTNING-WALLET_NOTES_PEEK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-peek \- FEAT-1688 wallet-notes-peek
.SH SYNOPSIS
.B lightning wallet-notes-peek
.SH DESCRIPTION
wallet-notes-peek for lightning CLI (FEAT-1688).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
