.TH "LIGHTNING-CHANNEL_RECEIVE_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-receive-msat \- FEAT-1142 channel-receive-msat
.SH SYNOPSIS
.B lightning channel-receive-msat
.SH DESCRIPTION
channel-receive-msat for lightning CLI (FEAT-1142).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
