.TH "LIGHTNING-PEER_CONNECTED_DURATION" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-connected-duration \- FEAT-1287 peer-connected-duration
.SH SYNOPSIS
.B lightning peer-connected-duration
.SH DESCRIPTION
peer-connected-duration for lightning CLI (FEAT-1287).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
