.TH "LIGHTNING-PEER-LOCAL-RESERVE-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-local-reserve-min \- FEAT-3103 verb
.SH SYNOPSIS
.B lightning peer-local-reserve-min
.SH DESCRIPTION
peer-local-reserve-min for lightning CLI (FEAT-3103).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
