.TH "LIGHTNING-NODE_LISTPEERS_PUBLIC" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpeers-public \- FEAT-1484 node-listpeers-public
.SH SYNOPSIS
.B lightning node-listpeers-public
.SH DESCRIPTION
node-listpeers-public for lightning CLI (FEAT-1484).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
