.TH "LIGHTNING-WALLET_IMPORT_SEED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-import-seed \- FEAT-803 wallet-import-seed verb
.SH SYNOPSIS
.B lightning wallet-import-seed
.SH DESCRIPTION
wallet-import-seed verb for lightning CLI (FEAT-803).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
