.TH LIGHTNING-CHANNEL_SPENDABLE_BALANCE_KURTOSIS_WEEKLY 1
.SH NAME
lightning-channel-spendable-balance-kurtosis-weekly \- compute channel-spendable-balance-kurtosis-weekly metric
.SH SYNOPSIS
.B lightning channel-spendable-balance-kurtosis-weekly
.SH DESCRIPTION
Outputs the channel-spendable-balance-kurtosis-weekly metric as JSON.
.SH EXIT STATUS
0 on success.
