.TH "LIGHTNING-NODE_TOTAL_RECEIVED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-total-received \- show total msat received across all paid invoices
.SH SYNOPSIS
.B lightning node-total-received
.SH DESCRIPTION
Show total msat received across all paid invoices.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
