.TH "LIGHTNING-CHANNEL-MAX-HTLC-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-max-htlc-count \- FEAT-1942 verb
.SH SYNOPSIS
.B lightning channel-max-htlc-count
.SH DESCRIPTION
channel-max-htlc-count for lightning CLI (FEAT-1942).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
