.TH "LIGHTNING-CHANNEL_COMMIT_FEE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-commit-fee \- FEAT-750 channel-commit-fee verb
.SH SYNOPSIS
.B lightning channel-commit-fee
.SH DESCRIPTION
channel-commit-fee verb for lightning CLI (FEAT-750).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
