.TH "LIGHTNING-NODE_LISTPAYS_FAILED_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-failed-count \- FEAT-1351 node-listpays-failed-count
.SH SYNOPSIS
.B lightning node-listpays-failed-count
.SH DESCRIPTION
node-listpays-failed-count for lightning CLI (FEAT-1351).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
