.TH "LIGHTNING-PEER-OLDEST-CHANNEL-AGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-oldest-channel-age \- FEAT-1996 verb
.SH SYNOPSIS
.B lightning peer-oldest-channel-age
.I node_id
.SH DESCRIPTION
peer-oldest-channel-age for lightning CLI (FEAT-1996).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
