.TH "LIGHTNING-CHANNEL-SPENDABLE-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-spendable-range \- FEAT-3130 verb
.SH SYNOPSIS
.B lightning channel-spendable-range
.SH DESCRIPTION
channel-spendable-range for lightning CLI (FEAT-3130).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
