.TH "LIGHTNING-CHANNEL_REMOTE_PCT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-remote-pct \- FEAT-976 channel-remote-pct
.SH SYNOPSIS
.B lightning channel-remote-pct
.SH DESCRIPTION
channel-remote-pct for lightning CLI (FEAT-976).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
