.TH "LIGHTNING-NODE-LISTINVOICES-BOLT12-LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listinvoices-bolt12-list \- FEAT-2389 list of bolt12 invoices
.SH SYNOPSIS
.B lightning node-listinvoices-bolt12-list
.SH DESCRIPTION
node-listinvoices-bolt12-list for lightning CLI (FEAT-2389).
.PP
Output: JSON from CLN with bolt12_invoice_count and bolt12_invoices array.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
