.TH "LIGHTNING-CHANNEL-FEE-BASE-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-fee-base-min \- FEAT-2395 channel with lowest fee_base_msat
.SH SYNOPSIS
.B lightning channel-fee-base-min
.SH DESCRIPTION
channel-fee-base-min verb for lightning CLI (FEAT-2395).
.PP
Output: JSON from CLN containing the channel with the lowest fee_base_msat.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
