.TH "LIGHTNING-WALLET_TAGS_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-tags-list \- FEAT-818 wallet-tags-list verb
.SH SYNOPSIS
.B lightning wallet-tags-list
.SH DESCRIPTION
wallet-tags-list verb for lightning CLI (FEAT-818).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
