.TH "LIGHTNING-CHANNEL_BALANCE_SNAPSHOT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-balance-snapshot \- FEAT-940 channel-balance-snapshot
.SH SYNOPSIS
.B lightning channel-balance-snapshot
.SH DESCRIPTION
channel-balance-snapshot for lightning CLI (FEAT-940).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
