.TH "LIGHTNING-PEER_DISCONNECT_ALL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-disconnect-all \- FEAT-967 peer-disconnect-all
.SH SYNOPSIS
.B lightning peer-disconnect-all
.SH DESCRIPTION
peer-disconnect-all for lightning CLI (FEAT-967).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
