.TH "LIGHTNING-WALLET_META_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-meta-set \- FEAT-1393 wallet-meta-set
.SH SYNOPSIS
.B lightning wallet-meta-set
.SH DESCRIPTION
wallet-meta-set for lightning CLI (FEAT-1393).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
