.TH "LIGHTNING-CHANNEL_LOCAL_FEE_PPM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-local-fee-ppm \- FEAT-1542 channel-local-fee-ppm
.SH SYNOPSIS
.B lightning channel-local-fee-ppm
.SH DESCRIPTION
channel-local-fee-ppm for lightning CLI (FEAT-1542).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
