.TH "LIGHTNING-CHANNEL_CLOSE_STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-status \- FEAT-736 channel-close-status verb
.SH SYNOPSIS
.B lightning channel-close-status
.SH DESCRIPTION
channel-close-status verb for lightning CLI (FEAT-736).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
