.TH LIGHTNING-PEER-BOTH-BALANCES-KURTOSIS 1
.SH NAME
lightning-peer-both-balances-kurtosis \- kurtosis of both peer balances
.SH SYNOPSIS
lightning peer-both-balances-kurtosis
.SH DESCRIPTION
Returns the kurtosis of both peer balances.
.SH OUTPUT
JSON object with key \fBboth_balances_kurtosis_peer\fR.
