.TH "LIGHTNING-INVOICE_LIST_EXPIRED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-expired \- list expired invoices
.SH SYNOPSIS
.B lightning invoice-list-expired

.SH DESCRIPTION
Returns a list of expired invoices.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
