.TH "LIGHTNING-CHANNEL_THEIR_CLTV_DELTA" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-their-cltv-delta \- FEAT-1820 channel-their-cltv-delta
.SH SYNOPSIS
.B lightning channel-their-cltv-delta
.SH DESCRIPTION
channel-their-cltv-delta for lightning CLI (FEAT-1820).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
