.TH "LIGHTNING-NODE_GRAPH_CHANNEL_AGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-channel-age \- FEAT-1609 node-graph-channel-age
.SH SYNOPSIS
.B lightning node-graph-channel-age
.SH DESCRIPTION
node-graph-channel-age for lightning CLI (FEAT-1609).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
