.TH "LIGHTNING-NODE_ROUTE_FIND" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-route-find \- find a route to a destination node
.SH SYNOPSIS
.B lightning node-route-find\n.I destination amount_msat
.SH DESCRIPTION
Finds a route to the destination using CLN's getroute command.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
