.TH "LIGHTNING-WALLET_BALANCE_ONCHAIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-balance-onchain \- FEAT-1058 wallet-balance-onchain
.SH SYNOPSIS
.B lightning wallet-balance-onchain
.SH DESCRIPTION
wallet-balance-onchain for lightning CLI (FEAT-1058).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
