.TH "LIGHTNING-NODE_PEER_SCORE_DETAIL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-peer-score-detail \- FEAT-799 node-peer-score-detail verb
.SH SYNOPSIS
.B lightning node-peer-score-detail
.SH DESCRIPTION
node-peer-score-detail verb for lightning CLI (FEAT-799).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
