.TH "LIGHTNING-NODE_GRAPH_NODES_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-nodes-count \- FEAT-839 node-graph-nodes-count verb
.SH SYNOPSIS
.B lightning node-graph-nodes-count
.SH DESCRIPTION
node-graph-nodes-count verb for lightning CLI (FEAT-839).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
