.TH "LIGHTNING-NODE_LISTPEERS_CONNECTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpeers-connected \- FEAT-904 node-listpeers-connected
.SH SYNOPSIS
.B lightning node-listpeers-connected
.SH DESCRIPTION
node-listpeers-connected for lightning CLI (FEAT-904).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
