.TH "LIGHTNING-INVOICE_LIST_CREATED_AFTER" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-created-after \- FEAT-1725 invoice-list-created-after
.SH SYNOPSIS
.B lightning invoice-list-created-after
.SH DESCRIPTION
invoice-list-created-after for lightning CLI (FEAT-1725).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
