.TH "LIGHTNING-NODE_ROUTING_POLICY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-routing-policy \- FEAT-719 node-routing-policy verb
.SH SYNOPSIS
.B lightning node-routing-policy
.SH DESCRIPTION
node-routing-policy verb for lightning CLI (FEAT-719).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
