.TH "LIGHTNING-NODE_LISTFORWARDS_IN_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-in-msat \- FEAT-1809 node-listforwards-in-msat
.SH SYNOPSIS
.B lightning node-listforwards-in-msat
.SH DESCRIPTION
node-listforwards-in-msat for lightning CLI (FEAT-1809).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
