.TH "LIGHTNING-CHANNEL-BOTH-RESERVES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-both-reserves \- FEAT-2070 verb
.SH SYNOPSIS
.B lightning channel-both-reserves
.SH DESCRIPTION
channel-both-reserves for lightning CLI (FEAT-2070).
.PP
Returns our and their channel reserve amounts for each peer channel.
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
