.TH "LIGHTNING-NODE_LISTPAYS_BY_BOLT11" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-by-bolt11 \- FEAT-1671 node-listpays-by-bolt11
.SH SYNOPSIS
.B lightning node-listpays-by-bolt11
.SH DESCRIPTION
node-listpays-by-bolt11 for lightning CLI (FEAT-1671).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
