.TH "LIGHTNING-INVOICE_BOLT11_EXPIRY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-bolt11-expiry \- FEAT-1695 invoice-bolt11-expiry
.SH SYNOPSIS
.B lightning invoice-bolt11-expiry
.SH DESCRIPTION
invoice-bolt11-expiry for lightning CLI (FEAT-1695).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
