.TH "LIGHTNING-CHANNEL_MIN_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-min-capacity \- FEAT-1060 channel-min-capacity
.SH SYNOPSIS
.B lightning channel-min-capacity
.SH DESCRIPTION
channel-min-capacity for lightning CLI (FEAT-1060).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
