.TH "LIGHTNING-CHANNEL_MIN_DEPTH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-min-depth \- show minimum confirmation depth for a channel
.SH SYNOPSIS
.B lightning channel-min-depth
.SH DESCRIPTION
Show minimum confirmation depth for a channel.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
