.TH "LIGHTNING-CHANNEL_OPEN_PENDING" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-pending \- list channels that are not yet fully open
.SH SYNOPSIS
.B lightning channel-open-pending
.SH DESCRIPTION
List channels that are not yet fully open.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
