.TH "LIGHTNING-CHANNEL_PUSH_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-push-msat \- FEAT-1590 channel-push-msat
.SH SYNOPSIS
.B lightning channel-push-msat
.SH DESCRIPTION
channel-push-msat for lightning CLI (FEAT-1590).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
