.TH "LIGHTNING-PEER-FEE-PROPORTIONAL-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-fee-proportional-range \- FEAT-3291 verb
.SH SYNOPSIS
.B lightning peer-fee-proportional-range
.SH DESCRIPTION
peer-fee-proportional-range for lightning CLI (FEAT-3291).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
