.TH "LIGHTNING-WALLET_SEED_VERIFY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-seed-verify \- verify wallet seed hash
.SH SYNOPSIS
.B lightning wallet-seed-verify
.I wallet_name seed_hash
.SH DESCRIPTION
Compares the provided seed hash against the stored hash in the wallet.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
