.TH "LIGHTNING-PEER_NET_ADDRESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-net-address \- FEAT-1347 peer-net-address
.SH SYNOPSIS
.B lightning peer-net-address
.SH DESCRIPTION
peer-net-address for lightning CLI (FEAT-1347).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
