.TH "LIGHTNING-NODE_LISTFUNDS_CHANNELS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listfunds-channels \- FEAT-931 node-listfunds-channels
.SH SYNOPSIS
.B lightning node-listfunds-channels
.SH DESCRIPTION
node-listfunds-channels for lightning CLI (FEAT-931).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
