.TH "LIGHTNING-CHANNEL_SHORT_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-short-count \- FEAT-1906 channel-short-count
.SH SYNOPSIS
.B lightning channel-short-count
.SH DESCRIPTION
channel-short-count for lightning CLI (FEAT-1906).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
