.TH "LIGHTNING-NODE_COLOR" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-color \- FEAT-951 node-color
.SH SYNOPSIS
.B lightning node-color
.SH DESCRIPTION
node-color for lightning CLI (FEAT-951).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
