.TH "LIGHTNING-NODE_ALIAS_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-alias-set \- set the node alias via setconfig
.SH SYNOPSIS
.B lightning node-alias-set
.I alias
.SH DESCRIPTION
Sets the node alias using CLN's setconfig command.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
