.TH LIGHTNING-NODE-INVOICE-PAID-AMOUNT-YEARLY 1
.SH NAME
lightning-node-invoice-paid-amount-yearly \- total paid invoice amount over the past year
.SH SYNOPSIS
lightning node-invoice-paid-amount-yearly
.SH DESCRIPTION
Returns the total paid invoice amount (msat) aggregated over the past year.
.SH SEE ALSO
lightning(1)
