.TH "LIGHTNING-NODE_LISTCHANNELS_BY_SCID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-by-scid \- FEAT-1644 node-listchannels-by-scid
.SH SYNOPSIS
.B lightning node-listchannels-by-scid
.SH DESCRIPTION
node-listchannels-by-scid for lightning CLI (FEAT-1644).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
