.TH "LIGHTNING-NODE_GRAPH_CHANNEL_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-channel-capacity \- FEAT-1779 node-graph-channel-capacity
.SH SYNOPSIS
.B lightning node-graph-channel-capacity
.SH DESCRIPTION
node-graph-channel-capacity for lightning CLI (FEAT-1779).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
