.TH "LIGHTNING-NODE_LISTCHANNELS_STATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-state \- FEAT-954 node-listchannels-state
.SH SYNOPSIS
.B lightning node-listchannels-state
.SH DESCRIPTION
node-listchannels-state for lightning CLI (FEAT-954).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
