.TH "LIGHTNING-NODE_ONCHAIN_UTXO_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-onchain-utxo-count \- FEAT-794 node-onchain-utxo-count verb
.SH SYNOPSIS
.B lightning node-onchain-utxo-count
.SH DESCRIPTION
node-onchain-utxo-count verb for lightning CLI (FEAT-794).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
