.TH "LIGHTNING-PEER_INVOICE_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-invoice-total \- FEAT-1277 peer-invoice-total
.SH SYNOPSIS
.B lightning peer-invoice-total
.SH DESCRIPTION
peer-invoice-total for lightning CLI (FEAT-1277).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
