.TH "LIGHTNING-PEER_GOSSIP_ACTIVE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-gossip-active \- FEAT-1567 peer-gossip-active
.SH SYNOPSIS
.B lightning peer-gossip-active
.SH DESCRIPTION
peer-gossip-active for lightning CLI (FEAT-1567).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
