.TH "LIGHTNING-CHANNEL-HTLC-VALUE-STDDEV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-value-stddev \- FEAT-3209 verb
.SH SYNOPSIS
.B lightning channel-htlc-value-stddev
.SH DESCRIPTION
channel-htlc-value-stddev for lightning CLI (FEAT-3209).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
