.TH "LIGHTNING-PEER_SPENDABLE_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-spendable-msat \- FEAT-1597 peer-spendable-msat
.SH SYNOPSIS
.B lightning peer-spendable-msat
.SH DESCRIPTION
peer-spendable-msat for lightning CLI (FEAT-1597).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
