.TH "LIGHTNING-PEER-SPENDABLE-PCT-STDDEV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-spendable-pct-stddev \- FEAT-3499 verb
.SH SYNOPSIS
.B lightning peer-spendable-pct-stddev
.SH DESCRIPTION
peer-spendable-pct-stddev for lightning CLI (FEAT-3499).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
