.TH "LIGHTNING-CHANNEL_HEALTH_CHECK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-health-check \- FEAT-950 channel-health-check
.SH SYNOPSIS
.B lightning channel-health-check
.SH DESCRIPTION
channel-health-check for lightning CLI (FEAT-950).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
