.TH "LIGHTNING-CHANNEL-OPEN-PSBT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-psbt \- start a PSBT-based channel open
.SH SYNOPSIS
.B lightning channel-open-psbt
.I peer_id amount_sat
.SH DESCRIPTION
Initiates a PSBT-based channel open via
.BR fundchannel_start ,
returning the funding address and other details for external PSBT construction.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-channel-open (1),
.BR lightning-channel-open-dual (1)
