.TH "LIGHTNING-NODE_ONION_DECODE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-onion-decode \- decode a payment string via CLN decode
.SH SYNOPSIS
.B lightning node-onion-decode
.I onion_hex
.SH DESCRIPTION
Decodes a payment string using CLN's decodepay command.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
