.TH "LIGHTNING-NODE_PAY_AVG_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-avg-msat \- FEAT-1311 node-pay-avg-msat
.SH SYNOPSIS
.B lightning node-pay-avg-msat
.SH DESCRIPTION
node-pay-avg-msat for lightning CLI (FEAT-1311).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
