.TH "LIGHTNING-NODE-INVOICE-UNPAID-AMOUNT-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-unpaid-amount-total \- FEAT-2990 node-invoice-unpaid-amount-total
.SH SYNOPSIS
.B lightning node-invoice-unpaid-amount-total
.SH DESCRIPTION
Total amount of unpaid invoices for lightning CLI (FEAT-2990).
.PP
Output: JSON from CLN with key \fBunpaid_amount_total_msat\fR.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
