.TH "LIGHTNING-NODE-PAY-90D-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-90d-count \- FEAT-2346 count of complete pays in last 90 days
.SH SYNOPSIS
.B lightning node-pay-90d-count
.SH DESCRIPTION
count of complete pays in last 90 days for lightning CLI (FEAT-2346).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
