.TH "LIGHTNING-PEER-HTLC-MIN-MSAT-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-htlc-min-msat-avg \- FEAT-3300 verb
.SH SYNOPSIS
.B lightning peer-htlc-min-msat-avg
.SH DESCRIPTION
peer-htlc-min-msat-avg for lightning CLI (FEAT-3300).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
