.TH "LIGHTNING-INVOICE_TOTAL_VALUE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-total-value \- FEAT-673 invoice-total-value verb
.SH SYNOPSIS
.B lightning invoice-total-value
.SH DESCRIPTION
invoice-total-value verb for lightning CLI (FEAT-673).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
