.TH "LIGHTNING-NODE_CLOSE_ALL_CHANNELS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-close-all-channels \- FEAT-789 node-close-all-channels verb
.SH SYNOPSIS
.B lightning node-close-all-channels
.SH DESCRIPTION
node-close-all-channels verb for lightning CLI (FEAT-789).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
