.TH "LIGHTNING-CHANNEL_AGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-age \- FEAT-1110 channel-age
.SH SYNOPSIS
.B lightning channel-age
.SH DESCRIPTION
channel-age for lightning CLI (FEAT-1110).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
