.TH "LIGHTNING-NODE-LISTPAYS-BY-DAY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-by-day \- FEAT-2051 Group complete payments by calendar day
.SH SYNOPSIS
.B lightning node-listpays-by-day
.SH DESCRIPTION
Group complete payments by calendar day (FEAT-2051).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
