.TH "LIGHTNING-CHANNEL_OUTGOING_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-outgoing-count \- FEAT-992 channel-outgoing-count
.SH SYNOPSIS
.B lightning channel-outgoing-count
.SH DESCRIPTION
channel-outgoing-count for lightning CLI (FEAT-992).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
