.TH "LIGHTNING-PEER-BOTH-RESERVES-KURTOSIS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-both-reserves-kurtosis \- FEAT-3583 verb
.SH SYNOPSIS
.B lightning peer-both-reserves-kurtosis
.SH DESCRIPTION
peer-both-reserves-kurtosis for lightning CLI (FEAT-3583).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
