.TH "LIGHTNING-WALLET_UNLOCK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-unlock \- verify a wallet database is accessible
.SH SYNOPSIS
.B lightning wallet-unlock
.SH DESCRIPTION
Verify a wallet database is accessible.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
