.TH "LIGHTNING-CHANNEL_CAPACITY_HISTOGRAM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-capacity-histogram \- FEAT-2218 histogram of channel capacity ranges
.SH SYNOPSIS
.B lightning channel-capacity-histogram
.SH DESCRIPTION
histogram of channel capacity ranges for the lightning CLI (FEAT-2218).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
