.TH "LIGHTNING-NODE_LIQUIDITY_ADS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-liquidity-ads \- show liquidity ads configuration
.SH SYNOPSIS
.B lightning node-liquidity-ads

.SH DESCRIPTION
Reports whether liquidity ads are configured on this node.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
