.TH "LIGHTNING-PAYMENT_TRACK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-payment-track \- look up a payment by hash
.SH SYNOPSIS
.B lightning payment-track
.I payment_hash
.SH DESCRIPTION
Looks up a payment by its payment_hash and returns status and amount.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
