.TH "LIGHTNING-CHANNEL-RESERVE-REMOTE-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-reserve-remote-total \- FEAT-3027 verb
.SH SYNOPSIS
.B lightning channel-reserve-remote-total
.SH DESCRIPTION
channel-reserve-remote-total for lightning CLI (FEAT-3027).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
