.TH "LIGHTNING-WALLET-NOTES-RECENT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-recent \- FEAT-2053 Show most recent notes from the wallet database
.SH SYNOPSIS
.B lightning wallet-notes-recent
.SH DESCRIPTION
Show most recent notes from the wallet database (FEAT-2053).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
