.TH "LIGHTNING-CHANNEL_CLOSE_COOP" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-coop \- cooperatively close a channel
.SH SYNOPSIS
.B lightning channel-close-coop
.SH DESCRIPTION
Cooperatively close a channel.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
