.TH "LIGHTNING-NODE_GRAPH_NODES_WITH_ADDRESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-nodes-with-address \- FEAT-1699 node-graph-nodes-with-address
.SH SYNOPSIS
.B lightning node-graph-nodes-with-address
.SH DESCRIPTION
node-graph-nodes-with-address for lightning CLI (FEAT-1699).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
