.TH "LIGHTNING-CHANNEL_HTLC_OUT_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-out-count \- FEAT-1472 channel-htlc-out-count
.SH SYNOPSIS
.B lightning channel-htlc-out-count
.SH DESCRIPTION
channel-htlc-out-count for lightning CLI (FEAT-1472).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
