.TH "LIGHTNING-NODE_CHANNEL_AGE_AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-age-avg \- FEAT-824 node-channel-age-avg verb
.SH SYNOPSIS
.B lightning node-channel-age-avg
.SH DESCRIPTION
node-channel-age-avg verb for lightning CLI (FEAT-824).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
