.TH "LIGHTNING-CHANNEL_SAT_PER_VBYTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-sat-per-vbyte \- show fee rates in sat/vbyte
.SH SYNOPSIS
.B lightning channel-sat-per-vbyte

.SH DESCRIPTION
Returns urgent, normal, and slow fee rates converted to sat/vbyte.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
