.TH "LIGHTNING-CHANNEL_DUST_LIMIT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-dust-limit \- FEAT-1450 channel-dust-limit
.SH SYNOPSIS
.B lightning channel-dust-limit
.SH DESCRIPTION
channel-dust-limit for lightning CLI (FEAT-1450).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
