.TH "LIGHTNING-CHANNEL_LOCAL_RESERVE_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-local-reserve-msat \- FEAT-1550 channel-local-reserve-msat
.SH SYNOPSIS
.B lightning channel-local-reserve-msat
.SH DESCRIPTION
channel-local-reserve-msat for lightning CLI (FEAT-1550).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
