.TH "LIGHTNING-WALLET_CREATED_AT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-created-at \- show wallet creation timestamp
.SH SYNOPSIS
.B lightning wallet-created-at
.SH DESCRIPTION
Show wallet creation timestamp.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
