.TH "LIGHTNING-CHANNEL_SHORT_CHANNEL_ID_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-short-channel-id-list \- FEAT-1440 channel-short-channel-id-list
.SH SYNOPSIS
.B lightning channel-short-channel-id-list
.SH DESCRIPTION
channel-short-channel-id-list for lightning CLI (FEAT-1440).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
