.TH "LIGHTNING-WALLET_FEE_ESTIMATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-fee-estimate \- FEAT-957 wallet-fee-estimate
.SH SYNOPSIS
.B lightning wallet-fee-estimate
.SH DESCRIPTION
wallet-fee-estimate for lightning CLI (FEAT-957).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
