.TH "LIGHTNING-NODE_LISTCHANNELS_TOTAL_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-total-capacity \- FEAT-1289 node-listchannels-total-capacity
.SH SYNOPSIS
.B lightning node-listchannels-total-capacity
.SH DESCRIPTION
node-listchannels-total-capacity for lightning CLI (FEAT-1289).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
