.TH "LIGHTNING-CHANNEL_OPEN_COST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-cost \- FEAT-866 channel-open-cost
.SH SYNOPSIS
.B lightning channel-open-cost
.SH DESCRIPTION
channel-open-cost for lightning CLI (FEAT-866).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
