.TH "LIGHTNING-NODE-LISTFORWARDS-AMOUNT-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-amount-min \- FEAT-3289 verb
.SH SYNOPSIS
.B lightning node-listforwards-amount-min
.SH DESCRIPTION
node-listforwards-amount-min for lightning CLI (FEAT-3289).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
