.TH "LIGHTNING-CHANNEL_INFLIGHT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-inflight \- FEAT-662 channel-inflight verb
.SH SYNOPSIS
.B lightning channel-inflight
.SH DESCRIPTION
channel-inflight verb for lightning CLI (FEAT-662).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
