.TH "LIGHTNING-NODE-INVOICE-AMOUNT-VARIANCE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-amount-variance \- FEAT-3420 verb
.SH SYNOPSIS
.B lightning node-invoice-amount-variance
.SH DESCRIPTION
node-invoice-amount-variance for lightning CLI (FEAT-3420).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
