.TH "LIGHTNING-CHANNEL-HTLC-VALUE-TOP10" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-value-top10 \- FEAT-3338 verb
.SH SYNOPSIS
.B lightning channel-htlc-value-top10
.SH DESCRIPTION
channel-htlc-value-top10 for lightning CLI (FEAT-3338).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
