.TH "LIGHTNING-NODE_FEE_COLLECT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-fee-collect \- FEAT-809 node-fee-collect verb
.SH SYNOPSIS
.B lightning node-fee-collect
.SH DESCRIPTION
node-fee-collect verb for lightning CLI (FEAT-809).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
