.TH "LIGHTNING-NODE_LISTCHANNELS_LARGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-large \- FEAT-1904 node-listchannels-large
.SH SYNOPSIS
.B lightning node-listchannels-large
.SH DESCRIPTION
node-listchannels-large for lightning CLI (FEAT-1904).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
