.TH "LIGHTNING-NODE_OFFER_CREATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-offer-create \- create a BOLT12 offer
.SH SYNOPSIS
.B lightning node-offer-create
.RI [ description ]
.SH DESCRIPTION
Creates a BOLT12 offer via CLN's offer command.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
