.TH "LIGHTNING-CHANNEL_INFLIGHT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-inflight \- FEAT-1216 channel-inflight
.SH SYNOPSIS
.B lightning channel-inflight
.SH DESCRIPTION
channel-inflight for lightning CLI (FEAT-1216).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
