.TH "LIGHTNING-WALLET_NOTES_DUMP" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-dump \- FEAT-1568 wallet-notes-dump
.SH SYNOPSIS
.B lightning wallet-notes-dump
.SH DESCRIPTION
wallet-notes-dump for lightning CLI (FEAT-1568).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
