.TH "LIGHTNING-PEER-REMOTE-BALANCE-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-remote-balance-range \- FEAT-3247 verb
.SH SYNOPSIS
.B lightning peer-remote-balance-range
.SH DESCRIPTION
peer-remote-balance-range for lightning CLI (FEAT-3247).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
