.TH "LIGHTNING-INVOICE_EXPIRY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-expiry \- FEAT-1085 invoice-expiry
.SH SYNOPSIS
.B lightning invoice-expiry
.SH DESCRIPTION
invoice-expiry for lightning CLI (FEAT-1085).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
