.TH "LIGHTNING-WALLET_NOTES_BULK_REMOVE_TAG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-bulk-remove-tag \- FEAT-1703 wallet-notes-bulk-remove-tag
.SH SYNOPSIS
.B lightning wallet-notes-bulk-remove-tag
.SH DESCRIPTION
wallet-notes-bulk-remove-tag for lightning CLI (FEAT-1703).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
