.TH "LIGHTNING-WALLET_NOTES_OLDEST_KEY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-oldest-key \- FEAT-1518 wallet-notes-oldest-key
.SH SYNOPSIS
.B lightning wallet-notes-oldest-key
.SH DESCRIPTION
wallet-notes-oldest-key for lightning CLI (FEAT-1518).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
