.TH "LIGHTNING-WALLET_NOTES_KEYWORD_SEARCH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-keyword-search \- FEAT-1543 wallet-notes-keyword-search
.SH SYNOPSIS
.B lightning wallet-notes-keyword-search
.SH DESCRIPTION
wallet-notes-keyword-search for lightning CLI (FEAT-1543).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
