.TH "LIGHTNING-NODE-LISTFORWARDS-AMOUNT-SKEWNESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-amount-skewness \- FEAT-3303 verb
.SH SYNOPSIS
.B lightning node-listforwards-amount-skewness
.SH DESCRIPTION
node-listforwards-amount-skewness for lightning CLI (FEAT-3303).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
