.TH "LIGHTNING-INVOICE_DESCRIPTION_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-description-set \- create an invoice with a custom description
.SH SYNOPSIS
.B lightning invoice-description-set
.SH DESCRIPTION
Create an invoice with a custom description.
.PP
Output: JSON object from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
