.TH "LIGHTNING-PEER-LOCAL-BALANCE-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-local-balance-min \- FEAT-2403 peer with lowest total local_msat across their channels
.SH SYNOPSIS
.B lightning peer-local-balance-min
.SH DESCRIPTION
Peer with lowest total local_msat across their channels for lightning CLI (FEAT-2403).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
