.TH "LIGHTNING-CHANNEL-RECEIVABLE-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-receivable-range \- FEAT-3131 verb
.SH SYNOPSIS
.B lightning channel-receivable-range
.SH DESCRIPTION
channel-receivable-range for lightning CLI (FEAT-3131).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
