.TH "LIGHTNING-PEER-CAPACITY-RATIO-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-capacity-ratio-range \- FEAT-3096 verb
.SH SYNOPSIS
.B lightning peer-capacity-ratio-range
.SH DESCRIPTION
peer-capacity-ratio-range for lightning CLI (FEAT-3096).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
