.TH "LIGHTNING-NODE-LISTFORWARDS-AMOUNT-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-amount-range \- FEAT-3296 verb
.SH SYNOPSIS
.B lightning node-listforwards-amount-range
.SH DESCRIPTION
node-listforwards-amount-range for lightning CLI (FEAT-3296).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
