.TH "LIGHTNING-PEER-LOCAL-RESERVE-STDDEV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-local-reserve-stddev \- FEAT-3109 verb
.SH SYNOPSIS
.B lightning peer-local-reserve-stddev
.SH DESCRIPTION
peer-local-reserve-stddev for lightning CLI (FEAT-3109).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
