.TH "LIGHTNING-CHANNEL_OUT_PAYMENTS_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-out-payments-count \- FEAT-1272 channel-out-payments-count
.SH SYNOPSIS
.B lightning channel-out-payments-count
.SH DESCRIPTION
channel-out-payments-count for lightning CLI (FEAT-1272).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
