.TH "LIGHTNING-CHANNEL_AWAITING_UNILATERAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-awaiting-unilateral \- FEAT-1660 channel-awaiting-unilateral
.SH SYNOPSIS
.B lightning channel-awaiting-unilateral
.SH DESCRIPTION
channel-awaiting-unilateral for lightning CLI (FEAT-1660).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
