.TH "LIGHTNING-NODE-GRAPH-NODES-BY-ALIAS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-nodes-by-alias \- FEAT-1979 verb
.SH SYNOPSIS
.B lightning node-graph-nodes-by-alias
.SH DESCRIPTION
verb for lightning CLI (FEAT-1979).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
