.TH LIGHTNING-CHANNEL_LOCAL_BALANCE_KURTOSIS_MONTHLY 1
.SH NAME
lightning-channel-local-balance-kurtosis-monthly \- compute channel-local-balance-kurtosis-monthly metric
.SH SYNOPSIS
.B lightning channel-local-balance-kurtosis-monthly
.SH DESCRIPTION
Outputs the channel-local-balance-kurtosis-monthly metric as JSON.
.SH EXIT STATUS
0 on success.
