.TH "LIGHTNING-PEER_CONNECT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-connect \- connect to a remote peer
.SH SYNOPSIS
.B lightning peer-connect
.I peer_id host\n.RI [ port ]
.SH DESCRIPTION
Connects to a peer by node ID, host, and optional port (default 9735).
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
