.TH "LIGHTNING-NODE_CHANNEL_BALANCE_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-balance-total \- show total local and remote channel balance
.SH SYNOPSIS
.B lightning node-channel-balance-total
.SH DESCRIPTION
Show total local and remote channel balance.
.PP
Output: JSON object from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
