.TH "LIGHTNING-WALLET_META_DELETE_ALL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-meta-delete-all \- FEAT-1418 wallet-meta-delete-all
.SH SYNOPSIS
.B lightning wallet-meta-delete-all
.SH DESCRIPTION
wallet-meta-delete-all for lightning CLI (FEAT-1418).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
