.TH "LIGHTNING-WALLET_NOTES_COPY_TAG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-copy-tag \- FEAT-1623 wallet-notes-copy-tag
.SH SYNOPSIS
.B lightning wallet-notes-copy-tag
.SH DESCRIPTION
wallet-notes-copy-tag for lightning CLI (FEAT-1623).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
