.TH "LIGHTNING-NODE_GRAPH_CHANNELS_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-channels-total \- FEAT-1254 node-graph-channels-total
.SH SYNOPSIS
.B lightning node-graph-channels-total
.SH DESCRIPTION
node-graph-channels-total for lightning CLI (FEAT-1254).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
