.TH "LIGHTNING-NODE_CHANNEL_TOTAL_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-total-capacity \- FEAT-1451 node-channel-total-capacity
.SH SYNOPSIS
.B lightning node-channel-total-capacity
.SH DESCRIPTION
node-channel-total-capacity for lightning CLI (FEAT-1451).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
