.TH "LIGHTNING-WALLET_TAG_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-tag-list \- FEAT-1128 wallet-tag-list
.SH SYNOPSIS
.B lightning wallet-tag-list
.SH DESCRIPTION
wallet-tag-list for lightning CLI (FEAT-1128).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
