.TH "LIGHTNING-NODE_LISTFORWARDS_SETTLED_RATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-settled-rate \- FEAT-2331 ratio of settled to total forwards
.SH SYNOPSIS
.B lightning node-listforwards-settled-rate
.SH DESCRIPTION
ratio of settled to total forwards verb for lightning CLI (FEAT-2331).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
