.TH "LIGHTNING-PEER_LAST_INVOICE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-last-invoice \- FEAT-1127 peer-last-invoice
.SH SYNOPSIS
.B lightning peer-last-invoice
.SH DESCRIPTION
peer-last-invoice for lightning CLI (FEAT-1127).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
