.TH "LIGHTNING-WALLET_TRANSACTION_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-transaction-list \- FEAT-953 wallet-transaction-list
.SH SYNOPSIS
.B lightning wallet-transaction-list
.SH DESCRIPTION
wallet-transaction-list for lightning CLI (FEAT-953).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
