.TH "LIGHTNING-CHANNEL_FUNDING_DEPTH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-funding-depth \- FEAT-1682 channel-funding-depth
.SH SYNOPSIS
.B lightning channel-funding-depth
.SH DESCRIPTION
channel-funding-depth for lightning CLI (FEAT-1682).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
