.TH "LIGHTNING-NODE_PAY_ATTEMPT_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-attempt-count \- FEAT-814 node-pay-attempt-count verb
.SH SYNOPSIS
.B lightning node-pay-attempt-count
.SH DESCRIPTION
node-pay-attempt-count verb for lightning CLI (FEAT-814).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
