.TH "LIGHTNING-NODE_HTLC_TOTAL_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-htlc-total-msat \- FEAT-1251 node-htlc-total-msat
.SH SYNOPSIS
.B lightning node-htlc-total-msat
.SH DESCRIPTION
node-htlc-total-msat for lightning CLI (FEAT-1251).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
