.TH "LIGHTNING-WALLET_TRANSACTION_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-transaction-count \- FEAT-672 wallet-transaction-count verb
.SH SYNOPSIS
.B lightning wallet-transaction-count
.SH DESCRIPTION
wallet-transaction-count verb for lightning CLI (FEAT-672).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
