.TH "LIGHTNING-NODE_CLTV_DELTA" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-cltv-delta \- show CLTV delta configuration
.SH SYNOPSIS
.B lightning node-cltv-delta
.SH DESCRIPTION
Show CLTV delta configuration.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
