.TH LIGHTNING-CHANNEL_LOCAL_BALANCE_SKEWNESS_MONTHLY 1
.SH NAME
lightning-channel-local-balance-skewness-monthly \- compute channel-local-balance-skewness-monthly metric
.SH SYNOPSIS
.B lightning channel-local-balance-skewness-monthly
.SH DESCRIPTION
Outputs the channel-local-balance-skewness-monthly metric as JSON.
.SH EXIT STATUS
0 on success.
