.TH "LIGHTNING-PEER_SCB_BACKUP" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-scb-backup \- FEAT-807 peer-scb-backup verb
.SH SYNOPSIS
.B lightning peer-scb-backup
.SH DESCRIPTION
peer-scb-backup verb for lightning CLI (FEAT-807).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
