.TH "LIGHTNING-NODE_ONCHAIN_PENDING" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-onchain-pending \- FEAT-1539 node-onchain-pending
.SH SYNOPSIS
.B lightning node-onchain-pending
.SH DESCRIPTION
node-onchain-pending for lightning CLI (FEAT-1539).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
