.TH "LIGHTNING-NODE-LISTFORWARDS-IN-MSAT-SUM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-in-msat-sum \- FEAT-2621 node-listforwards-in-msat-sum
.SH SYNOPSIS
.B lightning node-listforwards-in-msat-sum
.SH DESCRIPTION
Sum of in_msat for all settled forwards for lightning CLI (FEAT-2621).
.PP
Output: JSON from CLN with key \fBin_msat_sum\fR.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
