.TH "LIGHTNING-NODE_LISTCHANNELS_INACTIVE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-inactive \- FEAT-1209 node-listchannels-inactive
.SH SYNOPSIS
.B lightning node-listchannels-inactive
.SH DESCRIPTION
node-listchannels-inactive for lightning CLI (FEAT-1209).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
