.TH "LIGHTNING-CHANNEL_FUNDING_STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-funding-status \- FEAT-770 channel-funding-status verb
.SH SYNOPSIS
.B lightning channel-funding-status
.SH DESCRIPTION
channel-funding-status verb for lightning CLI (FEAT-770).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
