.TH "LIGHTNING-PEER_INFO" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-info \- show connection status for a peer
.SH SYNOPSIS
.B lightning peer-info
.I peer_id
.SH DESCRIPTION
Returns connection status and channel count for a peer.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
