.TH "LIGHTNING-INVOICE_PAY_LOCAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-pay-local \- pay a BOLT11 invoice
.SH SYNOPSIS
.B lightning invoice-pay-local
.SH DESCRIPTION
Pay a BOLT11 invoice.
.PP
Output: JSON object from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
