.TH "LIGHTNING-INVOICE_PREIMAGE_REVEAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-preimage-reveal \- reveal payment preimage for a paid invoice
.SH SYNOPSIS
.B lightning invoice-preimage-reveal
.SH DESCRIPTION
Reveal payment preimage for a paid invoice.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
