.TH "LIGHTNING-WALLET_NOTES_BULK_DELETE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-bulk-delete \- FEAT-1353 wallet-notes-bulk-delete
.SH SYNOPSIS
.B lightning wallet-notes-bulk-delete
.SH DESCRIPTION
wallet-notes-bulk-delete for lightning CLI (FEAT-1353).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
