.TH "LIGHTNING-CHANNEL-THEIR-RESERVE-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-their-reserve-min \- FEAT-2560 verb
.SH SYNOPSIS
.B lightning channel-their-reserve-min
.SH DESCRIPTION
Channel with lowest their_reserve_msat for lightning CLI (FEAT-2560).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
