.TH "LIGHTNING-CHANNEL_MSATOSHI_TO_US" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-msatoshi-to-us \- FEAT-678 channel-msatoshi-to-us verb
.SH SYNOPSIS
.B lightning channel-msatoshi-to-us
.SH DESCRIPTION
channel-msatoshi-to-us verb for lightning CLI (FEAT-678).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
