.TH "LIGHTNING-CHANNEL_LOG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-log \- FEAT-1300 channel-log
.SH SYNOPSIS
.B lightning channel-log
.SH DESCRIPTION
channel-log for lightning CLI (FEAT-1300).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
