.TH "LIGHTNING-WALLET_NOTES_SIZE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-size \- FEAT-1883 wallet-notes-size
.SH SYNOPSIS
.B lightning wallet-notes-size
.SH DESCRIPTION
wallet-notes-size for lightning CLI (FEAT-1883).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
