.TH "LIGHTNING-WALLET_NOTES_STATS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-stats \- FEAT-1493 wallet-notes-stats
.SH SYNOPSIS
.B lightning wallet-notes-stats
.SH DESCRIPTION
wallet-notes-stats for lightning CLI (FEAT-1493).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
