.TH "LIGHTNING-PEER_SHARED_CHANNELS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-shared-channels \- FEAT-817 peer-shared-channels verb
.SH SYNOPSIS
.B lightning peer-shared-channels
.SH DESCRIPTION
peer-shared-channels verb for lightning CLI (FEAT-817).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
