.TH "LIGHTNING-CHANNEL-INCOMING-CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-incoming-capacity \- show total inbound capacity
.SH SYNOPSIS
.B lightning channel-incoming-capacity
.SH DESCRIPTION
Returns the total inbound (remote) capacity across all active channels.
.PP
Output:
.nf
{"incoming_capacity_msat":N, "incoming_capacity_sat":N, "active_channels":N}
.fi
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-channel-local-balance (1),
.BR lightning-channel-remote-balance (1)
