.TH "LIGHTNING-NODE_LISTPAYS_BY_AMOUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-by-amount \- FEAT-1331 node-listpays-by-amount
.SH SYNOPSIS
.B lightning node-listpays-by-amount
.SH DESCRIPTION
node-listpays-by-amount for lightning CLI (FEAT-1331).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
