.TH "LIGHTNING-PEER_LIST_WITH_CHANNELS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-list-with-channels \- FEAT-1377 peer-list-with-channels
.SH SYNOPSIS
.B lightning peer-list-with-channels
.SH DESCRIPTION
peer-list-with-channels for lightning CLI (FEAT-1377).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
