.TH "LIGHTNING-CHANNEL_ALL_FEES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-all-fees \- show fee policy for all channels
.SH SYNOPSIS
.B lightning channel-all-fees
.SH DESCRIPTION
Show fee policy for all channels.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
