.TH "LIGHTNING-CHANNEL-UPTIME-MEDIAN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-uptime-median \- FEAT-3064 verb
.SH SYNOPSIS
.B lightning channel-uptime-median
.SH DESCRIPTION
channel-uptime-median for lightning CLI (FEAT-3064).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
