.TH "LIGHTNING-WALLET_ACCOUNTS_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-accounts-list \- list accounts in the wallet ledger
.SH SYNOPSIS
.B lightning wallet-accounts-list
.I wallet_name
.SH DESCRIPTION
Returns all distinct account names from the wallet ledger.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
