.TH "LIGHTNING-NODE_LISTPEERS_FEATURES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpeers-features \- FEAT-1041 node-listpeers-features
.SH SYNOPSIS
.B lightning node-listpeers-features
.SH DESCRIPTION
node-listpeers-features for lightning CLI (FEAT-1041).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
