.TH "LIGHTNING-WALLET_NOTES_OLDEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-oldest \- FEAT-1363 wallet-notes-oldest
.SH SYNOPSIS
.B lightning wallet-notes-oldest
.SH DESCRIPTION
wallet-notes-oldest for lightning CLI (FEAT-1363).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
