.TH LIGHTNING-NODE-INVOICE-EXPIRED-COUNT-MONTHLY 1
.SH NAME
lightning-node-invoice-expired-count-monthly \- count of expired invoices over the past month
.SH SYNOPSIS
lightning node-invoice-expired-count-monthly
.SH DESCRIPTION
Returns the count of expired invoices over the past month.
.SH SEE ALSO
lightning(1)
