.TH "LIGHTNING-CHANNEL-CAPACITY-TOTAL-BTC" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-capacity-total-btc \- FEAT-2477 channel-capacity-total-btc
.SH SYNOPSIS
.B lightning channel-capacity-total-btc
.SH DESCRIPTION
Total channel capacity in BTC (sum of local+remote msat across all channels divided by 100000000000) (FEAT-2477).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
