.TH "LIGHTNING-NODE_KEYSEND_STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-keysend-status \- show keysend availability
.SH SYNOPSIS
.B lightning node-keysend-status

.SH DESCRIPTION
Reports whether keysend (spontaneous payments) is configured.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
