.TH "LIGHTNING-PEER_CHANNEL_STATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-channel-state \- FEAT-1237 peer-channel-state
.SH SYNOPSIS
.B lightning peer-channel-state
.SH DESCRIPTION
peer-channel-state for lightning CLI (FEAT-1237).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
