.TH "LIGHTNING-INVOICE_WEBHOOK_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-webhook-set \- FEAT-795 invoice-webhook-set verb
.SH SYNOPSIS
.B lightning invoice-webhook-set
.SH DESCRIPTION
invoice-webhook-set verb for lightning CLI (FEAT-795).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
