.TH "LIGHTNING-CHANNEL_FEEBASE_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-feebase-set \- set base fee for a channel
.SH SYNOPSIS
.B lightning channel-feebase-set
.SH DESCRIPTION
Set base fee for a channel.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
