.TH "LIGHTNING-WALLET_NOTES_BATCH_GET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-batch-get \- FEAT-1593 wallet-notes-batch-get
.SH SYNOPSIS
.B lightning wallet-notes-batch-get
.SH DESCRIPTION
wallet-notes-batch-get for lightning CLI (FEAT-1593).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
