.TH "LIGHTNING-NODE-PAY-180D-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-180d-total \- FEAT-2356 total amount_sent_msat for complete pays in last 180 days
.SH SYNOPSIS
.B lightning node-pay-180d-total
.SH DESCRIPTION
node-pay-180d-total for lightning CLI (FEAT-2356).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
