.TH "LIGHTNING-INVOICE_BOLT11_AMOUNT_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-bolt11-amount-msat \- FEAT-1655 invoice-bolt11-amount-msat
.SH SYNOPSIS
.B lightning invoice-bolt11-amount-msat
.SH DESCRIPTION
invoice-bolt11-amount-msat for lightning CLI (FEAT-1655).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
