.TH "LIGHTNING-WALLET_TAG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-tag \- FEAT-698 wallet-tag verb
.SH SYNOPSIS
.B lightning wallet-tag
.SH DESCRIPTION
wallet-tag verb for lightning CLI (FEAT-698).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
