.TH "LIGHTNING-NODE_LISTFORWARDS_TOTAL_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-total-msat \- FEAT-1549 node-listforwards-total-msat
.SH SYNOPSIS
.B lightning node-listforwards-total-msat
.SH DESCRIPTION
node-listforwards-total-msat for lightning CLI (FEAT-1549).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
