.TH "LIGHTNING-NODE_FEERATE_ESTIMATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-feerate-estimate \- FEAT-749 node-feerate-estimate verb
.SH SYNOPSIS
.B lightning node-feerate-estimate
.SH DESCRIPTION
node-feerate-estimate verb for lightning CLI (FEAT-749).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
