.TH LIGHTNING-CHANNEL-LOCAL-BALANCE-SKEWNESS-YEARLY 1
.SH NAME
lightning-channel-local-balance-skewness-yearly \- skewness of channel local balances over the past year
.SH SYNOPSIS
lightning channel-local-balance-skewness-yearly
.SH DESCRIPTION
Returns the skewness of local balance (msat) across all peer channels over the past year.
.SH SEE ALSO
lightning(1)
