.TH "LIGHTNING-CHANNEL_SHORT_ID_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-short-id-list \- FEAT-1150 channel-short-id-list
.SH SYNOPSIS
.B lightning channel-short-id-list
.SH DESCRIPTION
channel-short-id-list for lightning CLI (FEAT-1150).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
