.TH "LIGHTNING-PEER-FEE-EARNED-MEDIAN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-fee-earned-median \- FEAT-3083 verb
.SH SYNOPSIS
.B lightning peer-fee-earned-median
.SH DESCRIPTION
peer-fee-earned-median for lightning CLI (FEAT-3083).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
