.TH "LIGHTNING-NODE_LISTFUNDS_ONCHAIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listfunds-onchain \- FEAT-704 node-listfunds-onchain verb
.SH SYNOPSIS
.B lightning node-listfunds-onchain
.SH DESCRIPTION
node-listfunds-onchain verb for lightning CLI (FEAT-704).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
