.TH "LIGHTNING-WALLET_PRUNE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-prune \- FEAT-676 wallet-prune verb
.SH SYNOPSIS
.B lightning wallet-prune
.SH DESCRIPTION
wallet-prune verb for lightning CLI (FEAT-676).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
