.TH "LIGHTNING-NODE_LISTCHANNELS_HTLC_DISABLED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-htlc-disabled \- FEAT-1844 node-listchannels-htlc-disabled
.SH SYNOPSIS
.B lightning node-listchannels-htlc-disabled
.SH DESCRIPTION
node-listchannels-htlc-disabled for lightning CLI (FEAT-1844).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
