.TH "LIGHTNING-NODE-LISTFORWARDS-FEE-AVG-WEEKLY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-fee-avg-weekly \- FEAT-3333 verb
.SH SYNOPSIS
.B lightning node-listforwards-fee-avg-weekly
.SH DESCRIPTION
node-listforwards-fee-avg-weekly for lightning CLI (FEAT-3333).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
