.TH LIGHTNING-PEER-RECEIVABLE-BALANCE-SKEWNESS-WEEKLY 1
.SH NAME
lightning-peer-receivable-balance-skewness-weekly \- skewness of peer receivable balances over the past week
.SH SYNOPSIS
lightning peer-receivable-balance-skewness-weekly
.SH DESCRIPTION
Returns the skewness of receivable balances per peer over the past week.
.SH SEE ALSO
lightning(1)
