.TH "LIGHTNING-CHANNEL-REMOTE-RESERVE-TOP10" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-remote-reserve-top10 \- FEAT-3374 verb
.SH SYNOPSIS
.B lightning channel-remote-reserve-top10
.SH DESCRIPTION
channel-remote-reserve-top10 for lightning CLI (FEAT-3374).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
