.TH "LIGHTNING-NODE-LISTINVOICES-BOLT12-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listinvoices-bolt12-count \- FEAT-2309 count of bolt12 invoices
.SH SYNOPSIS
.B lightning node-listinvoices-bolt12-count
.SH DESCRIPTION
Count of bolt12 invoices (local_offer_id field present) for lightning CLI (FEAT-2309).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
