.TH "LIGHTNING-NODE_PAYMENT_ROUTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-payment-route \- FEAT-894 node-payment-route
.SH SYNOPSIS
.B lightning node-payment-route
.SH DESCRIPTION
node-payment-route for lightning CLI (FEAT-894).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
