.TH "LIGHTNING-CHANNEL_NEXT_HTLC_ID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-next-htlc-id \- FEAT-1830 channel-next-htlc-id
.SH SYNOPSIS
.B lightning channel-next-htlc-id
.SH DESCRIPTION
channel-next-htlc-id for lightning CLI (FEAT-1830).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
