.TH "LIGHTNING-CHANNEL_FINAL_STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-final-status \- FEAT-850 channel-final-status
.SH SYNOPSIS
.B lightning channel-final-status
.SH DESCRIPTION
channel-final-status for lightning CLI (FEAT-850).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
