.TH "LIGHTNING-NODE_LISTPAYS_AMOUNT_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-amount-total \- FEAT-1471 node-listpays-amount-total
.SH SYNOPSIS
.B lightning node-listpays-amount-total
.SH DESCRIPTION
node-listpays-amount-total for lightning CLI (FEAT-1471).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
