.TH "LIGHTNING-NODE_LISTFORWARDS_BY_STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-by-status \- FEAT-1094 node-listforwards-by-status
.SH SYNOPSIS
.B lightning node-listforwards-by-status
.SH DESCRIPTION
node-listforwards-by-status for lightning CLI (FEAT-1094).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
