.TH "LIGHTNING-CHANNEL-LOCAL-PCT-KURTOSIS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-local-pct-kurtosis \- FEAT-3472 verb
.SH SYNOPSIS
.B lightning channel-local-pct-kurtosis
.SH DESCRIPTION
channel-local-pct-kurtosis for lightning CLI (FEAT-3472).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
