.TH "LIGHTNING-CHANNEL_FUNDING_SAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-funding-sat \- FEAT-1402 channel-funding-sat
.SH SYNOPSIS
.B lightning channel-funding-sat
.SH DESCRIPTION
channel-funding-sat for lightning CLI (FEAT-1402).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
