.TH "LIGHTNING-NODE_LISTPAYS_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-count \- FEAT-889 node-listpays-count
.SH SYNOPSIS
.B lightning node-listpays-count
.SH DESCRIPTION
node-listpays-count for lightning CLI (FEAT-889).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
