.TH "LIGHTNING-NODE_LISTFORWARDS_SETTLED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-settled \- FEAT-899 node-listforwards-settled
.SH SYNOPSIS
.B lightning node-listforwards-settled
.SH DESCRIPTION
node-listforwards-settled for lightning CLI (FEAT-899).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
