.TH "LIGHTNING-NODE_LISTFORWARDS_FEE_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-fee-total \- FEAT-1769 node-listforwards-fee-total
.SH SYNOPSIS
.B lightning node-listforwards-fee-total
.SH DESCRIPTION
node-listforwards-fee-total for lightning CLI (FEAT-1769).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
