.TH "LIGHTNING-PEER_FEATURE_BITS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-feature-bits \- FEAT-1756 peer-feature-bits
.SH SYNOPSIS
.B lightning peer-feature-bits
.SH DESCRIPTION
peer-feature-bits for lightning CLI (FEAT-1756).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
