.TH "LIGHTNING-NODE_LISTPAYS_MEMO" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-memo \- FEAT-1851 node-listpays-memo
.SH SYNOPSIS
.B lightning node-listpays-memo
.SH DESCRIPTION
node-listpays-memo for lightning CLI (FEAT-1851).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
