.TH "LIGHTNING-CHANNEL_DRAIN_TO" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-drain-to \- FEAT-822 channel-drain-to verb
.SH SYNOPSIS
.B lightning channel-drain-to
.SH DESCRIPTION
channel-drain-to verb for lightning CLI (FEAT-822).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
