.TH "LIGHTNING-CHANNEL_MIN_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-min-msat \- FEAT-1090 channel-min-msat
.SH SYNOPSIS
.B lightning channel-min-msat
.SH DESCRIPTION
channel-min-msat for lightning CLI (FEAT-1090).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
