.TH "LIGHTNING-INVOICE_CREATE_AUTO" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-create-auto \- FEAT-955 invoice-create-auto
.SH SYNOPSIS
.B lightning invoice-create-auto
.SH DESCRIPTION
invoice-create-auto for lightning CLI (FEAT-955).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
