.TH "LIGHTNING-NODE_GRAPH_LOCAL_NODE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-local-node \- FEAT-1739 node-graph-local-node
.SH SYNOPSIS
.B lightning node-graph-local-node
.SH DESCRIPTION
node-graph-local-node for lightning CLI (FEAT-1739).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
