.TH "LIGHTNING-NODE_LIQUIDITY_SUMMARY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-liquidity-summary \- show overall spendable and receivable liquidity
.SH SYNOPSIS
.B lightning node-liquidity-summary
.SH DESCRIPTION
Show overall spendable and receivable liquidity.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
