.TH "LIGHTNING-WALLET_META_RENAME" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-meta-rename \- FEAT-1698 wallet-meta-rename
.SH SYNOPSIS
.B lightning wallet-meta-rename
.SH DESCRIPTION
wallet-meta-rename for lightning CLI (FEAT-1698).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
