.TH "LIGHTNING-WALLET_NOTES_COUNT_ARCHIVED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-count-archived \- FEAT-1738 wallet-notes-count-archived
.SH SYNOPSIS
.B lightning wallet-notes-count-archived
.SH DESCRIPTION
wallet-notes-count-archived for lightning CLI (FEAT-1738).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
