.TH "LIGHTNING-PEER_FEATURES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-features \- FEAT-1027 peer-features
.SH SYNOPSIS
.B lightning peer-features
.SH DESCRIPTION
peer-features for lightning CLI (FEAT-1027).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
