.TH "LIGHTNING-INVOICE_PAYMENT_PREIMAGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-payment-preimage \- FEAT-1625 invoice-payment-preimage
.SH SYNOPSIS
.B lightning invoice-payment-preimage
.SH DESCRIPTION
invoice-payment-preimage for lightning CLI (FEAT-1625).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
