.TH "LIGHTNING-NODE_LISTFORWARDS_CHANNEL_PAIR" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-channel-pair \- FEAT-1899 node-listforwards-channel-pair
.SH SYNOPSIS
.B lightning node-listforwards-channel-pair
.SH DESCRIPTION
node-listforwards-channel-pair for lightning CLI (FEAT-1899).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
