.TH "LIGHTNING-NODE_LISTCHANNELS_HTLC_MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-htlc-min \- FEAT-1814 node-listchannels-htlc-min
.SH SYNOPSIS
.B lightning node-listchannels-htlc-min
.SH DESCRIPTION
node-listchannels-htlc-min for lightning CLI (FEAT-1814).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
