.TH "LIGHTNING-NODE_FEE_SCHEDULE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-fee-schedule \- show fee policy for all channels
.SH SYNOPSIS
.B lightning node-fee-schedule

.SH DESCRIPTION
Returns the fee base and fee-proportional-millionths for every peer channel.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
