.TH "LIGHTNING-NODE_FEE_RATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-fee-rate \- show current fee rates from CLN
.SH SYNOPSIS
.B lightning node-fee-rate
.SH DESCRIPTION
Show current fee rates from CLN.
.PP
Output: JSON object from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
