.TH "LIGHTNING-PEER_NODE_COLOR" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-node-color \- FEAT-1487 peer-node-color
.SH SYNOPSIS
.B lightning peer-node-color
.SH DESCRIPTION
peer-node-color for lightning CLI (FEAT-1487).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
