.TH "LIGHTNING-NODE_INVOICES_PENDING_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoices-pending-msat \- FEAT-991 node-invoices-pending-msat
.SH SYNOPSIS
.B lightning node-invoices-pending-msat
.SH DESCRIPTION
node-invoices-pending-msat for lightning CLI (FEAT-991).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
