.TH "LIGHTNING-CHANNEL_FORCE_CLOSEABLE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-force-closeable \- FEAT-1910 channel-force-closeable
.SH SYNOPSIS
.B lightning channel-force-closeable
.SH DESCRIPTION
channel-force-closeable for lightning CLI (FEAT-1910).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
