.TH "LIGHTNING-NODE_LISTCHANNELS_PPM_SORTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-ppm-sorted \- FEAT-1874 node-listchannels-ppm-sorted
.SH SYNOPSIS
.B lightning node-listchannels-ppm-sorted
.SH DESCRIPTION
node-listchannels-ppm-sorted for lightning CLI (FEAT-1874).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
