.TH "LIGHTNING-CHANNEL-RECEIVABLE-PCT-KURTOSIS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-receivable-pct-kurtosis \- FEAT-3497 verb
.SH SYNOPSIS
.B lightning channel-receivable-pct-kurtosis
.SH DESCRIPTION
channel-receivable-pct-kurtosis for lightning CLI (FEAT-3497).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
