.TH "LIGHTNING-WALLET_IMPORT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-import \- FEAT-1053 wallet-import
.SH SYNOPSIS
.B lightning wallet-import
.SH DESCRIPTION
wallet-import for lightning CLI (FEAT-1053).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
