.TH "LIGHTNING-CHANNEL_HTLC_MIN_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-min-msat \- FEAT-1556 channel-htlc-min-msat
.SH SYNOPSIS
.B lightning channel-htlc-min-msat
.SH DESCRIPTION
channel-htlc-min-msat for lightning CLI (FEAT-1556).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
