.TH "LIGHTNING-NODE_REBALANCE_NEEDED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-rebalance-needed \- FEAT-739 node-rebalance-needed verb
.SH SYNOPSIS
.B lightning node-rebalance-needed
.SH DESCRIPTION
node-rebalance-needed verb for lightning CLI (FEAT-739).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
