.TH "LIGHTNING-INVOICE_PAY_INDEX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-pay-index \- FEAT-1185 invoice-pay-index
.SH SYNOPSIS
.B lightning invoice-pay-index
.SH DESCRIPTION
invoice-pay-index for lightning CLI (FEAT-1185).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
