.TH "LIGHTNING-INVOICE_BOLT11_AMOUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-bolt11-amount \- FEAT-1805 invoice-bolt11-amount
.SH SYNOPSIS
.B lightning invoice-bolt11-amount
.SH DESCRIPTION
invoice-bolt11-amount for lightning CLI (FEAT-1805).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
