.TH "LIGHTNING-CHANNEL_HTLC_IN_TOTAL_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-in-total-msat \- FEAT-1700 channel-htlc-in-total-msat
.SH SYNOPSIS
.B lightning channel-htlc-in-total-msat
.SH DESCRIPTION
channel-htlc-in-total-msat for lightning CLI (FEAT-1700).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
