.TH "LIGHTNING-NODE_INVOICE_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-count \- FEAT-1489 node-invoice-count
.SH SYNOPSIS
.B lightning node-invoice-count
.SH DESCRIPTION
node-invoice-count for lightning CLI (FEAT-1489).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
