.TH "LIGHTNING-NODE_LISTCHANNELS_SORTED_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-sorted-capacity \- FEAT-1419 node-listchannels-sorted-capacity
.SH SYNOPSIS
.B lightning node-listchannels-sorted-capacity
.SH DESCRIPTION
node-listchannels-sorted-capacity for lightning CLI (FEAT-1419).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
