.TH "LIGHTNING-WALLET_META_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-meta-count \- FEAT-1618 wallet-meta-count
.SH SYNOPSIS
.B lightning wallet-meta-count
.SH DESCRIPTION
wallet-meta-count for lightning CLI (FEAT-1618).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
