.TH "LIGHTNING-PEER-HTLC-VALUE-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-htlc-value-avg \- FEAT-2408 average total HTLC value per peer
.SH SYNOPSIS
.B lightning peer-htlc-value-avg
.SH DESCRIPTION
Average total HTLC value per peer for lightning CLI (FEAT-2408).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
