.TH "LIGHTNING-PEER_IP_ADDRESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-ip-address \- FEAT-827 peer-ip-address verb
.SH SYNOPSIS
.B lightning peer-ip-address
.SH DESCRIPTION
peer-ip-address verb for lightning CLI (FEAT-827).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
