.TH "LIGHTNING-NODE-PEERS-DISCONNECTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-peers-disconnected \- list currently disconnected peers
.SH SYNOPSIS
.B lightning node-peers-disconnected
.SH DESCRIPTION
Returns peers that are not currently connected.
.PP
Output:
.nf
[{peer_id, alias}]
.fi
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-peer-list-connected (1),
.BR lightning-node-connect-auto (1)
