.TH "LIGHTNING-CHANNEL_LAST_STATE_CHANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-last-state-change \- FEAT-1582 channel-last-state-change
.SH SYNOPSIS
.B lightning channel-last-state-change
.SH DESCRIPTION
channel-last-state-change for lightning CLI (FEAT-1582).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
