.TH "LIGHTNING-NODE_CAPACITY_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-capacity-total \- show total channel capacity
.SH SYNOPSIS
.B lightning node-capacity-total
.SH DESCRIPTION
Show total channel capacity.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
