.TH "LIGHTNING-NODE-PAY-DESTINATION-LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-destination-list \- FEAT-1941 verb
.SH SYNOPSIS
.B lightning node-pay-destination-list
.SH DESCRIPTION
node-pay-destination-list for lightning CLI (FEAT-1941).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
