.TH "LIGHTNING-INVOICE_LIST_UNPAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-unpaid \- FEAT-905 invoice-list-unpaid
.SH SYNOPSIS
.B lightning invoice-list-unpaid
.SH DESCRIPTION
invoice-list-unpaid for lightning CLI (FEAT-905).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
