.TH "LIGHTNING-CHANNEL_OUT_MSATOSHI" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-out-msatoshi \- FEAT-1296 channel-out-msatoshi
.SH SYNOPSIS
.B lightning channel-out-msatoshi
.SH DESCRIPTION
channel-out-msatoshi for lightning CLI (FEAT-1296).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
