.TH "LIGHTNING-NODE-INVOICE-EXPIRED-AMOUNT-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-expired-amount-total \- FEAT-2992 node-invoice-expired-amount-total
.SH SYNOPSIS
.B lightning node-invoice-expired-amount-total
.SH DESCRIPTION
Total amount of expired invoices in millisatoshis (FEAT-2992).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
