.TH "LIGHTNING-NODE_ONCHAIN_CONFIRMED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-onchain-confirmed \- FEAT-1509 node-onchain-confirmed
.SH SYNOPSIS
.B lightning node-onchain-confirmed
.SH DESCRIPTION
node-onchain-confirmed for lightning CLI (FEAT-1509).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
