.TH "LIGHTNING-NODE-LISTFORWARDS-COUNT-DAY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-count-day \- FEAT-3058 verb
.SH SYNOPSIS
.B lightning node-listforwards-count-day
.SH DESCRIPTION
node-listforwards-count-day for lightning CLI (FEAT-3058).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
