.TH "LIGHTNING-CHANNEL_OPEN_FEERATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-feerate \- FEAT-982 channel-open-feerate
.SH SYNOPSIS
.B lightning channel-open-feerate
.SH DESCRIPTION
channel-open-feerate for lightning CLI (FEAT-982).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
