.TH "LIGHTNING-NODE_INVOICE_AUTO_EXPIRE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-auto-expire \- FEAT-874 node-invoice-auto-expire
.SH SYNOPSIS
.B lightning node-invoice-auto-expire
.SH DESCRIPTION
node-invoice-auto-expire for lightning CLI (FEAT-874).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
