.TH "LIGHTNING-NODE-LISTINVOICES-RECENT-PAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listinvoices-recent-paid \- FEAT-2319 node-listinvoices-recent-paid
.SH SYNOPSIS
.B lightning node-listinvoices-recent-paid
.SH DESCRIPTION
node-listinvoices-recent-paid for lightning CLI (FEAT-2319).
.PP
Reports the last 5 paid invoices.
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
