.TH "LIGHTNING-CHANNEL_OPEN_BLOCKS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-blocks \- FEAT-900 channel-open-blocks
.SH SYNOPSIS
.B lightning channel-open-blocks
.SH DESCRIPTION
channel-open-blocks for lightning CLI (FEAT-900).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
