.TH "LIGHTNING-NODE_CHANNEL_CLOSING_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-closing-count \- FEAT-1299 node-channel-closing-count
.SH SYNOPSIS
.B lightning node-channel-closing-count
.SH DESCRIPTION
node-channel-closing-count for lightning CLI (FEAT-1299).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
