.TH "LIGHTNING-WALLET_NAME_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-name-list \- list wallet names
.SH SYNOPSIS
.B lightning wallet-name-list
.SH DESCRIPTION
List wallet names.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
