.TH "LIGHTNING-NODE_LISTPAYS_DESTINATION_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-destination-count \- FEAT-1791 node-listpays-destination-count
.SH SYNOPSIS
.B lightning node-listpays-destination-count
.SH DESCRIPTION
node-listpays-destination-count for lightning CLI (FEAT-1791).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
