.TH "LIGHTNING-INVOICE_PAID_AT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-paid-at \- FEAT-1465 invoice-paid-at
.SH SYNOPSIS
.B lightning invoice-paid-at
.SH DESCRIPTION
invoice-paid-at for lightning CLI (FEAT-1465).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
