.TH "LIGHTNING-NODE_PAYMENT_SUCCESS_RATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-payment-success-rate \- FEAT-729 node-payment-success-rate verb
.SH SYNOPSIS
.B lightning node-payment-success-rate
.SH DESCRIPTION
node-payment-success-rate verb for lightning CLI (FEAT-729).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
