.TH "LIGHTNING-NODE_PAY_FEE_AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-fee-avg \- FEAT-1681 node-pay-fee-avg
.SH SYNOPSIS
.B lightning node-pay-fee-avg
.SH DESCRIPTION
node-pay-fee-avg for lightning CLI (FEAT-1681).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
