.TH LIGHTNING-CHANNEL_SPENDABLE_BALANCE_SKEWNESS_WEEKLY 1
.SH NAME
lightning-channel-spendable-balance-skewness-weekly \- compute channel-spendable-balance-skewness-weekly metric
.SH SYNOPSIS
.B lightning channel-spendable-balance-skewness-weekly
.SH DESCRIPTION
Outputs the channel-spendable-balance-skewness-weekly metric as JSON.
.SH EXIT STATUS
0 on success.
