.TH "LIGHTNING-INVOICE_LIST_PAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-paid \- list paid invoices
.SH SYNOPSIS
.B lightning invoice-list-paid

.SH DESCRIPTION
Returns a list of paid invoices with label, amount, and paid_at timestamp.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
