.TH "LIGHTNING-PEER_AVG_CHANNEL_SIZE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-avg-channel-size \- FEAT-1837 peer-avg-channel-size
.SH SYNOPSIS
.B lightning peer-avg-channel-size
.SH DESCRIPTION
peer-avg-channel-size for lightning CLI (FEAT-1837).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
