.TH "LIGHTNING-INVOICE_AMOUNT_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-amount-msat \- show amount of an invoice
.SH SYNOPSIS
.B lightning invoice-amount-msat
.SH DESCRIPTION
Show amount of an invoice.
.PP
Output: JSON object from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
