.TH "LIGHTNING-CHANNEL_RESERVE_REMOTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-reserve-remote \- FEAT-860 channel-reserve-remote
.SH SYNOPSIS
.B lightning channel-reserve-remote
.SH DESCRIPTION
channel-reserve-remote for lightning CLI (FEAT-860).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
