.TH "LIGHTNING-WALLET_NOTES_SYNC" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-sync \- FEAT-1713 wallet-notes-sync
.SH SYNOPSIS
.B lightning wallet-notes-sync
.SH DESCRIPTION
wallet-notes-sync for lightning CLI (FEAT-1713).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
