.TH "LIGHTNING-WALLET_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-list \- list all wallets in the wallet root
.SH SYNOPSIS
.B lightning wallet-list

.SH DESCRIPTION
Returns the names of all wallet directories under WALLETS_ROOT.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
