.TH "LIGHTNING-NODE_INVOICE_CREATE_KEYSEND" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-create-keysend \- FEAT-709 node-invoice-create-keysend verb
.SH SYNOPSIS
.B lightning node-invoice-create-keysend
.SH DESCRIPTION
node-invoice-create-keysend verb for lightning CLI (FEAT-709).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
