.TH "LIGHTNING-CHANNEL-REMOTE-BALANCE-BOTTOM5" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-remote-balance-bottom5 \- FEAT-2617 verb
.SH SYNOPSIS
.B lightning channel-remote-balance-bottom5
.SH DESCRIPTION
channel-remote-balance-bottom5 for lightning CLI (FEAT-2617).
.PP
Output: JSON from CLN with the bottom 5 channels by remote balance (total_msat - to_us_msat).
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
