.TH "LIGHTNING-CHANNEL_TOTAL_HTLC_IN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-total-htlc-in \- FEAT-1786 channel-total-htlc-in
.SH SYNOPSIS
.B lightning channel-total-htlc-in
.SH DESCRIPTION
channel-total-htlc-in for lightning CLI (FEAT-1786).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
