.TH "LIGHTNING-CHANNEL_FEERATE_PERKB" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-feerate-perkb \- FEAT-1856 channel-feerate-perkb
.SH SYNOPSIS
.B lightning channel-feerate-perkb
.SH DESCRIPTION
channel-feerate-perkb for lightning CLI (FEAT-1856).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
