.TH "LIGHTNING-WALLET_TAG_GET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-tag-get \- FEAT-1083 wallet-tag-get
.SH SYNOPSIS
.B lightning wallet-tag-get
.SH DESCRIPTION
wallet-tag-get for lightning CLI (FEAT-1083).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
