.TH "LIGHTNING-WALLET_LOCK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-lock \- FEAT-843 wallet-lock
.SH SYNOPSIS
.B lightning wallet-lock
.SH DESCRIPTION
wallet-lock for lightning CLI (FEAT-843).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
