.TH "LIGHTNING-NODE_LISTFORWARDS_LOCAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-local \- FEAT-1559 node-listforwards-local
.SH SYNOPSIS
.B lightning node-listforwards-local
.SH DESCRIPTION
node-listforwards-local for lightning CLI (FEAT-1559).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
