.TH "LIGHTNING-NODE_GRAPH_TOTAL_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-total-capacity \- FEAT-1649 node-graph-total-capacity
.SH SYNOPSIS
.B lightning node-graph-total-capacity
.SH DESCRIPTION
node-graph-total-capacity for lightning CLI (FEAT-1649).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
