.TH "LIGHTNING-NODE_FEE_SUMMARY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-fee-summary \- FEAT-677 node-fee-summary verb
.SH SYNOPSIS
.B lightning node-fee-summary
.SH DESCRIPTION
node-fee-summary verb for lightning CLI (FEAT-677).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
