.TH "LIGHTNING-NODE_LISTPAYS_LATEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-latest \- FEAT-1281 node-listpays-latest
.SH SYNOPSIS
.B lightning node-listpays-latest
.SH DESCRIPTION
node-listpays-latest for lightning CLI (FEAT-1281).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
