.TH "LIGHTNING-CHANNEL_MIN_DEPTH_ACTUAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-min-depth-actual \- FEAT-1680 channel-min-depth-actual
.SH SYNOPSIS
.B lightning channel-min-depth-actual
.SH DESCRIPTION
channel-min-depth-actual for lightning CLI (FEAT-1680).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
