.TH "LIGHTNING-NODE_FEERATE_NORMAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-feerate-normal \- FEAT-1774 node-feerate-normal
.SH SYNOPSIS
.B lightning node-feerate-normal
.SH DESCRIPTION
node-feerate-normal for lightning CLI (FEAT-1774).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
