.TH "LIGHTNING-CHANNEL-HTLC-DENSITY-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-density-min \- FEAT-3154 verb
.SH SYNOPSIS
.B lightning channel-htlc-density-min
.SH DESCRIPTION
channel-htlc-density-min for lightning CLI (FEAT-3154).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
