.TH "LIGHTNING-CHANNEL_SHORT_ID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-short-id \- FEAT-870 channel-short-id
.SH SYNOPSIS
.B lightning channel-short-id
.SH DESCRIPTION
channel-short-id for lightning CLI (FEAT-870).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
