.TH "LIGHTNING-PEER_FEERATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-feerate \- FEAT-1327 peer-feerate
.SH SYNOPSIS
.B lightning peer-feerate
.SH DESCRIPTION
peer-feerate for lightning CLI (FEAT-1327).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
