.TH "LIGHTNING-INVOICE_LIST_EXPIRED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-expired \- FEAT-665 invoice-list-expired verb
.SH SYNOPSIS
.B lightning invoice-list-expired
.SH DESCRIPTION
invoice-list-expired verb for lightning CLI (FEAT-665).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
