.TH "LIGHTNING-NODE_CHANNEL_LOCAL_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-local-count \- FEAT-1109 node-channel-local-count
.SH SYNOPSIS
.B lightning node-channel-local-count
.SH DESCRIPTION
node-channel-local-count for lightning CLI (FEAT-1109).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
