.TH "LIGHTNING-WALLET_ADDRESS_LATEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-address-latest \- FEAT-1008 wallet-address-latest
.SH SYNOPSIS
.B lightning wallet-address-latest
.SH DESCRIPTION
wallet-address-latest for lightning CLI (FEAT-1008).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
