.TH LIGHTNING-CHANNEL-BOTH-RESERVES-KURTOSIS-WEEKLY 1
.SH NAME
lightning-channel-both-reserves-kurtosis-weekly \- weekly kurtosis of both channel reserves
.SH SYNOPSIS
lightning channel-both-reserves-kurtosis-weekly
.SH DESCRIPTION
Returns the weekly kurtosis of both channel reserves in millisatoshis.
.SH OUTPUT
JSON object with key \fBboth_reserves_kurtosis_weekly_msat\fR.
