.TH LIGHTNING-CHANNEL-LOCAL-BALANCE-KURTOSIS-YEARLY 1
.SH NAME
lightning-channel-local-balance-kurtosis-yearly \- kurtosis of channel local balances over the past year
.SH SYNOPSIS
lightning channel-local-balance-kurtosis-yearly
.SH DESCRIPTION
Returns the kurtosis of channel local balances over the past year.
.SH SEE ALSO
lightning(1)
