.TH "LIGHTNING-CHANNEL_FEE_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-fee-set \- set fee policy for a channel
.SH SYNOPSIS
.B lightning channel-fee-set
.SH DESCRIPTION
Set fee policy for a channel.
.PP
Output: JSON object from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
