.TH "LIGHTNING-NODE_CHANNEL_AGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-age \- show age of each channel in seconds
.SH SYNOPSIS
.B lightning node-channel-age

.SH DESCRIPTION
Returns the age in seconds of each channel from its opened_at timestamp.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
