.TH LIGHTNING-CHANNEL-SPENDABLE-BALANCE-SKEWNESS-YEARLY 1
.SH NAME
lightning-channel-spendable-balance-skewness-yearly \- skewness of channel spendable balances over the past year
.SH SYNOPSIS
lightning channel-spendable-balance-skewness-yearly
.SH DESCRIPTION
Returns the skewness of channel spendable balances over the past year.
.SH SEE ALSO
lightning(1)
