.TH "LIGHTNING-PEER-LOCAL-BALANCE-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-local-balance-range \- FEAT-3244 verb
.SH SYNOPSIS
.B lightning peer-local-balance-range
.SH DESCRIPTION
peer-local-balance-range for lightning CLI (FEAT-3244).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
