.TH "LIGHTNING-NODE-SHORT-CHANNEL-ID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-short-channel-id \- look up the short channel ID for a channel
.SH SYNOPSIS
.B lightning node-short-channel-id
.I channel_id
.SH DESCRIPTION
Returns the short channel ID (block:tx:output) for the given full channel ID.
.PP
Output:
.nf
{"channel_id":..., "short_channel_id":...}
.fi
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-channel-info (1)
