.TH "LIGHTNING-CHANNEL-CAPACITY-MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-capacity-max \- FEAT-2287 channel with largest total capacity
.SH SYNOPSIS
.B lightning channel-capacity-max
.SH DESCRIPTION
Channel with largest total capacity verb for lightning CLI (FEAT-2287).
.PP
Output: JSON from CLN with the channel having the highest total_msat.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
