.TH "LIGHTNING-NODE_INVOICE_COUNT_PAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-count-paid \- FEAT-724 node-invoice-count-paid verb
.SH SYNOPSIS
.B lightning node-invoice-count-paid
.SH DESCRIPTION
node-invoice-count-paid verb for lightning CLI (FEAT-724).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
