.TH "LIGHTNING-CHANNEL-AGE-MEDIAN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-age-median \- FEAT-3071 verb
.SH SYNOPSIS
.B lightning channel-age-median
.SH DESCRIPTION
channel-age-median for lightning CLI (FEAT-3071).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
