.TH "LIGHTNING-PEER-OLDEST-PAY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-oldest-pay \- FEAT-2328 verb
.SH SYNOPSIS
.B lightning peer-oldest-pay
.SH DESCRIPTION
peer-oldest-pay for lightning CLI (FEAT-2328).
.PP
Output: JSON from CLN with the oldest complete payment.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
