.TH "LIGHTNING-WALLET_NOTES_EXPORT_CSV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-export-csv \- FEAT-1473 wallet-notes-export-csv
.SH SYNOPSIS
.B lightning wallet-notes-export-csv
.SH DESCRIPTION
wallet-notes-export-csv for lightning CLI (FEAT-1473).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
