.TH "LIGHTNING-NODE-LISTFORWARDS-IN-MSAT-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-in-msat-total \- FEAT-2341 total in_msat from settled forwards
.SH SYNOPSIS
.B lightning node-listforwards-in-msat-total
.SH DESCRIPTION
total in_msat from settled forwards for lightning CLI (FEAT-2341).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
