.TH "LIGHTNING-NODE-LISTFORWARDS-COUNT-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-count-total \- FEAT-2686 node-listforwards-count-total
.SH SYNOPSIS
.B lightning node-listforwards-count-total
.SH DESCRIPTION
Total count of all forwards (FEAT-2686).
.PP
Output: JSON from CLN with key \fBtotal_forward_count\fR.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
