.TH "LIGHTNING-CHANNEL-PEER-ALIAS-MAP" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-peer-alias-map \- FEAT-2072 verb
.SH SYNOPSIS
.B lightning channel-peer-alias-map
.SH DESCRIPTION
Maps peer_id to alias for all peer channels for the lightning CLI (FEAT-2072).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
