.TH "LIGHTNING-PEER_LAST_PAY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-last-pay \- FEAT-1077 peer-last-pay
.SH SYNOPSIS
.B lightning peer-last-pay
.SH DESCRIPTION
peer-last-pay for lightning CLI (FEAT-1077).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
