.TH "LIGHTNING-CHANNEL_STATE_CHANGES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-state-changes \- show state change history for a channel
.SH SYNOPSIS
.B lightning channel-state-changes
.SH DESCRIPTION
Show state change history for a channel.
.PP
Output: JSON object from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
