.TH "LIGHTNING-NODE-LISTFORWARDS-VOLUME-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-volume-avg \- FEAT-3052 verb
.SH SYNOPSIS
.B lightning node-listforwards-volume-avg
.SH DESCRIPTION
node-listforwards-volume-avg for lightning CLI (FEAT-3052).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
