.TH "LIGHTNING-PEER_ALIAS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-alias \- FEAT-1477 peer-alias
.SH SYNOPSIS
.B lightning peer-alias
.SH DESCRIPTION
peer-alias for lightning CLI (FEAT-1477).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
