.TH "LIGHTNING-NODE-PAY-VOLUME-7D" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-volume-7d \- FEAT-2406 total amount_sent_msat for complete pays in last 7 days
.SH SYNOPSIS
.B lightning node-pay-volume-7d
.SH DESCRIPTION
Total amount_sent_msat for complete pays in last 7 days for lightning CLI (FEAT-2406).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
