.TH "LIGHTNING-CHANNEL_MAX_HTLC_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-max-htlc-msat \- FEAT-1915 channel-max-htlc-msat
.SH SYNOPSIS
.B lightning channel-max-htlc-msat
.SH DESCRIPTION
channel-max-htlc-msat for lightning CLI (FEAT-1915).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
