.TH "LIGHTNING-NODE_INVOICE_REQUEST_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-request-list \- FEAT-804 node-invoice-request-list verb
.SH SYNOPSIS
.B lightning node-invoice-request-list
.SH DESCRIPTION
node-invoice-request-list verb for lightning CLI (FEAT-804).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
