.TH "LIGHTNING-CHANNEL_FEERATE_FLOOR" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-feerate-floor \- FEAT-1376 channel-feerate-floor
.SH SYNOPSIS
.B lightning channel-feerate-floor
.SH DESCRIPTION
channel-feerate-floor for lightning CLI (FEAT-1376).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
