.TH "LIGHTNING-NODE-LISTFORWARDS-OUT-MSAT-SUM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-out-msat-sum \- FEAT-2626 node-listforwards-out-msat-sum
.SH SYNOPSIS
.B lightning node-listforwards-out-msat-sum
.SH DESCRIPTION
Sum of out_msat for all settled forwards for lightning CLI (FEAT-2626).
.PP
Output: JSON from CLN with key \fBout_msat_sum\fR.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
