.TH "LIGHTNING-PEER-RECEIVABLE-KURTOSIS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-receivable-kurtosis \- FEAT-3463 verb
.SH SYNOPSIS
.B lightning peer-receivable-kurtosis
.SH DESCRIPTION
peer-receivable-kurtosis for lightning CLI (FEAT-3463).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
