.TH LIGHTNING-NODE-INVOICE-EXPIRED-COUNT-YEARLY 1
.SH NAME
lightning-node-invoice-expired-count-yearly \- count of expired invoices over the past year
.SH SYNOPSIS
lightning node-invoice-expired-count-yearly
.SH DESCRIPTION
Returns the count of expired invoices over the past year.
.SH SEE ALSO
lightning(1)
