.TH "LIGHTNING-NODE-INVOICE-EXPIRED-OLDEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-expired-oldest \- FEAT-2304 oldest expired invoice
.SH SYNOPSIS
.B lightning node-invoice-expired-oldest
.SH DESCRIPTION
Oldest expired invoice for lightning CLI (FEAT-2304).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
