.TH "LIGHTNING-PEER-TOTAL-SENT-MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-total-sent-msat \- FEAT-2056 Sum out_payments_fulfilled msat for a peer
.SH SYNOPSIS
.B lightning peer-total-sent-msat
.SH DESCRIPTION
Sum out_payments_fulfilled msat for a peer (FEAT-2056).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
