.TH "LIGHTNING-NODE_LISTFUNDS_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listfunds-total \- FEAT-961 node-listfunds-total
.SH SYNOPSIS
.B lightning node-listfunds-total
.SH DESCRIPTION
node-listfunds-total for lightning CLI (FEAT-961).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
