.TH "LIGHTNING-NODE_LISTPEERS_BY_ALIAS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpeers-by-alias \- FEAT-1194 node-listpeers-by-alias
.SH SYNOPSIS
.B lightning node-listpeers-by-alias
.SH DESCRIPTION
node-listpeers-by-alias for lightning CLI (FEAT-1194).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
