.TH "LIGHTNING-NODE_LISTCHANNELS_PRIVATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-private \- FEAT-1314 node-listchannels-private
.SH SYNOPSIS
.B lightning node-listchannels-private
.SH DESCRIPTION
node-listchannels-private for lightning CLI (FEAT-1314).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
