.TH LIGHTNING-CHANNEL-RECEIVABLE-BALANCE-SKEWNESS-YEARLY 1
.SH NAME
lightning-channel-receivable-balance-skewness-yearly \- skewness of channel receivable balances over the past year
.SH SYNOPSIS
lightning channel-receivable-balance-skewness-yearly
.SH DESCRIPTION
Returns the skewness of channel receivable balances over the past year.
.SH SEE ALSO
lightning(1)
