.TH "LIGHTNING-NODE_LISTCHANNELS_WITH_HTLCS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-with-htlcs \- FEAT-1604 node-listchannels-with-htlcs
.SH SYNOPSIS
.B lightning node-listchannels-with-htlcs
.SH DESCRIPTION
node-listchannels-with-htlcs for lightning CLI (FEAT-1604).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
