.TH "LIGHTNING-NODE-INVOICE-UNPAID-COUNT-MONTHLY" 1 "May 2026" "lightning" "User Commands"
.SH NAME
lightning-node-invoice-unpaid-count-monthly \- FEAT-3565 node-invoice-unpaid-count-monthly
.SH SYNOPSIS
.B lightning node-invoice-unpaid-count-monthly
.SH DESCRIPTION
Monthly count of unpaid invoices (FEAT-3565).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
