.TH "LIGHTNING-INVOICE_LIST_BY_PAID_AT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-by-paid-at \- FEAT-1675 invoice-list-by-paid-at
.SH SYNOPSIS
.B lightning invoice-list-by-paid-at
.SH DESCRIPTION
invoice-list-by-paid-at for lightning CLI (FEAT-1675).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
