.TH "LIGHTNING-INVOICE_LIST_UNPAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-unpaid \- list unpaid invoices
.SH SYNOPSIS
.B lightning invoice-list-unpaid

.SH DESCRIPTION
Returns all invoices with status unpaid.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
