.TH "LIGHTNING-NODE_INVOICE_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-count \- count total invoices
.SH SYNOPSIS
.B lightning node-invoice-count
.SH DESCRIPTION
Count total invoices.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
