.TH "LIGHTNING-NODE_LISTPAYS_GROUPED_DEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-grouped-dest \- FEAT-1891 node-listpays-grouped-dest
.SH SYNOPSIS
.B lightning node-listpays-grouped-dest
.SH DESCRIPTION
node-listpays-grouped-dest for lightning CLI (FEAT-1891).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
