.TH "LIGHTNING-CHANNEL-OUR-FEE-SUMMARY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-our-fee-summary \- FEAT-2062 verb
.SH SYNOPSIS
.B lightning channel-our-fee-summary
.SH DESCRIPTION
channel-our-fee-summary for lightning CLI (FEAT-2062).
.PP
Returns our base fee and fee-per-millionth for each peer channel.
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
