.TH "LIGHTNING-CHANNEL_FEES_EARNED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-fees-earned \- FEAT-1040 channel-fees-earned
.SH SYNOPSIS
.B lightning channel-fees-earned
.SH DESCRIPTION
channel-fees-earned for lightning CLI (FEAT-1040).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
