.TH "LIGHTNING-CHANNEL_TOTAL_HTLCS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-total-htlcs \- count in-flight HTLCs on a channel
.SH SYNOPSIS
.B lightning channel-total-htlcs
.SH DESCRIPTION
Count in-flight HTLCs on a channel.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
