.TH "LIGHTNING-NODE-PAY-COMPLETE-COUNT-1Y" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-complete-count-1y \- FEAT-2476 node-pay-complete-count-1y
.SH SYNOPSIS
.B lightning node-pay-complete-count-1y
.SH DESCRIPTION
Count of complete pays in the last 365 days (FEAT-2476).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
