.TH "LIGHTNING-CHANNEL_FUNDING_CONFIRMS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-funding-confirms \- FEAT-1560 channel-funding-confirms
.SH SYNOPSIS
.B lightning channel-funding-confirms
.SH DESCRIPTION
channel-funding-confirms for lightning CLI (FEAT-1560).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
