.TH "LIGHTNING-INVOICE_CHECK_PAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-check-paid \- FEAT-765 invoice-check-paid verb
.SH SYNOPSIS
.B lightning invoice-check-paid
.SH DESCRIPTION
invoice-check-paid verb for lightning CLI (FEAT-765).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
