.TH "LIGHTNING-CHANNEL-REMOTE-PCT-KURTOSIS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-remote-pct-kurtosis \- FEAT-3475 verb
.SH SYNOPSIS
.B lightning channel-remote-pct-kurtosis
.SH DESCRIPTION
channel-remote-pct-kurtosis for lightning CLI (FEAT-3475).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
