.TH "LIGHTNING-NODE_ONCHAIN_UNCONF" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-onchain-unconf \- FEAT-1099 node-onchain-unconf
.SH SYNOPSIS
.B lightning node-onchain-unconf
.SH DESCRIPTION
node-onchain-unconf for lightning CLI (FEAT-1099).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
