.TH "LIGHTNING-CHANNEL-OPEN-COUNT-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-count-total \- FEAT-3097 verb
.SH SYNOPSIS
.B lightning channel-open-count-total
.SH DESCRIPTION
channel-open-count-total for lightning CLI (FEAT-3097).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
