.TH "LIGHTNING-NODE-LISTFORWARDS-FEE-TOTAL-DAILY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-fee-total-daily \- FEAT-2869 node-listforwards-fee-total-daily
.SH SYNOPSIS
.B lightning node-listforwards-fee-total-daily
.SH DESCRIPTION
Total forward fees today for lightning CLI (FEAT-2869).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
