.TH "LIGHTNING-INVOICE-PAY-STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-pay-status \- check payment status by hash
.SH SYNOPSIS
.B lightning invoice-pay-status
.I payment_hash
.SH DESCRIPTION
Returns status of a payment by its hash from
.BR listpays .
.PP
Output:
.nf
{"payment_hash":..., "status":..., "amount_msat":N, "created_at":N}
.fi
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-pay (1),
.BR lightning-payment-list-failed (1)
