.TH "LIGHTNING-CHANNEL_MIN_TO_THEM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-min-to-them \- FEAT-1226 channel-min-to-them
.SH SYNOPSIS
.B lightning channel-min-to-them
.SH DESCRIPTION
channel-min-to-them for lightning CLI (FEAT-1226).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
