.TH "LIGHTNING-NODE-LISTINVOICES-PAID-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listinvoices-paid-count \- FEAT-2027 verb
.SH SYNOPSIS
.B lightning node-listinvoices-paid-count
.SH DESCRIPTION
verb for lightning CLI (FEAT-2027).
.PP
Output: JSON from CLN with count of paid invoices.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
