.TH "LIGHTNING-WALLET_ADDRESS_NEW" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-address-new \- FEAT-763 wallet-address-new verb
.SH SYNOPSIS
.B lightning wallet-address-new
.SH DESCRIPTION
wallet-address-new verb for lightning CLI (FEAT-763).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
