.TH "LIGHTNING-NODE-INVOICE-PAID-AMOUNT-MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-paid-amount-max \- FEAT-2689 node-invoice-paid-amount-max
.SH SYNOPSIS
.B lightning node-invoice-paid-amount-max
.SH DESCRIPTION
Maximum amount_msat of paid invoices (FEAT-2689).
.PP
Output: JSON from CLN with key \fBmax_paid_amount_msat\fR.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
