.TH "LIGHTNING-CHANNEL_OUT_PAYMENTS_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-out-payments-msat \- FEAT-1372 channel-out-payments-msat
.SH SYNOPSIS
.B lightning channel-out-payments-msat
.SH DESCRIPTION
channel-out-payments-msat for lightning CLI (FEAT-1372).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
