.TH "LIGHTNING-NODE-LISTINVOICES-PAID-AMOUNT-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listinvoices-paid-amount-avg \- FEAT-2499 average amount_msat of paid invoices
.SH SYNOPSIS
.B lightning node-listinvoices-paid-amount-avg
.SH DESCRIPTION
average amount_msat of paid invoices for lightning CLI (FEAT-2499).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
