.TH "LIGHTNING-NODE-LISTFORWARDS-FEE-TOTAL-1Y" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-fee-total-1y \- FEAT-2491 total fee_msat from settled forwards in last 365 days
.SH SYNOPSIS
.B lightning node-listforwards-fee-total-1y
.SH DESCRIPTION
total fee_msat from settled forwards in last 365 days for lightning CLI (FEAT-2491).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
