.TH "LIGHTNING-CHANNEL-REMOTE-BALANCE-SMALLEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-remote-balance-smallest \- FEAT-2200 verb
.SH SYNOPSIS
.B lightning channel-remote-balance-smallest
.SH DESCRIPTION
channel with least remote balance for lightning CLI (FEAT-2200).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
