.TH "LIGHTNING-CHANNEL-LOCAL-BALANCE-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-local-balance-min \- FEAT-2262 channel-local-balance-min
.SH SYNOPSIS
.B lightning channel-local-balance-min
.SH DESCRIPTION
channel-local-balance-min for lightning CLI (FEAT-2262).
.PP
Output: JSON from CLN with the channel having the lowest local_msat.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
