.TH "LIGHTNING-WALLET_PIN_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-pin-set \- set or update a wallet PIN
.SH SYNOPSIS
.B lightning wallet-pin-set
.SH DESCRIPTION
Set or update a wallet PIN.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
