.TH "LIGHTNING-CHANNEL_STATUS_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-status-list \- FEAT-1046 channel-status-list
.SH SYNOPSIS
.B lightning channel-status-list
.SH DESCRIPTION
channel-status-list for lightning CLI (FEAT-1046).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
