.TH "LIGHTNING-NODE_LISTCHANNELS_BY_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-by-capacity \- FEAT-1794 node-listchannels-by-capacity
.SH SYNOPSIS
.B lightning node-listchannels-by-capacity
.SH DESCRIPTION
node-listchannels-by-capacity for lightning CLI (FEAT-1794).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
