.TH "LIGHTNING-CHANNEL-HTLC-EXPIRY-SOONEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-expiry-soonest \- FEAT-2372 channel with soonest HTLC expiry
.SH SYNOPSIS
.B lightning channel-htlc-expiry-soonest
.SH DESCRIPTION
Channel with soonest HTLC expiry (cltv_expiry field) for lightning CLI (FEAT-2372).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
