.TH "LIGHTNING-CHANNEL-BALANCE-PCT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-balance-pct \- FEAT-1990 verb
.SH SYNOPSIS
.B lightning channel-balance-pct
.SH DESCRIPTION
channel-balance-pct for lightning CLI (FEAT-1990).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
