.TH "LIGHTNING-PEER_LIST_IDS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-list-ids \- FEAT-1147 peer-list-ids
.SH SYNOPSIS
.B lightning peer-list-ids
.SH DESCRIPTION
peer-list-ids for lightning CLI (FEAT-1147).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
