.TH "LIGHTNING-CHANNEL-MAX-SPENDABLE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-max-spendable \- FEAT-2018 channel-max-spendable
.SH SYNOPSIS
.B lightning channel-max-spendable
.SH DESCRIPTION
channel-max-spendable for lightning CLI (FEAT-2018).
.PP
Output: JSON from CLN with the channel having the maximum spendable balance in msat.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
