.TH "LIGHTNING-CHANNEL_DUST_LIMIT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-dust-limit \- show dust limit for a channel
.SH SYNOPSIS
.B lightning channel-dust-limit
.SH DESCRIPTION
Show dust limit for a channel.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
