.TH LIGHTNING-NODE-INVOICE-EXPIRED-COUNT-WEEKLY 1
.SH NAME
lightning-node-invoice-expired-count-weekly \- count of expired invoices over the past week
.SH SYNOPSIS
lightning node-invoice-expired-count-weekly
.SH DESCRIPTION
Returns the number of expired invoices aggregated over the past week.
.SH SEE ALSO
lightning(1)
