.TH "LIGHTNING-NODE_LISTPEERS_IDS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpeers-ids \- FEAT-741 node-listpeers-ids verb
.SH SYNOPSIS
.B lightning node-listpeers-ids
.SH DESCRIPTION
node-listpeers-ids verb for lightning CLI (FEAT-741).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
