.TH "LIGHTNING-INVOICE_BOLT12_CREATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-bolt12-create \- create a BOLT12 offer
.SH SYNOPSIS
.B lightning invoice-bolt12-create
.SH DESCRIPTION
Create a BOLT12 offer.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
