.TH "LIGHTNING-CHANNEL_PEER_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-peer-total \- FEAT-956 channel-peer-total
.SH SYNOPSIS
.B lightning channel-peer-total
.SH DESCRIPTION
channel-peer-total for lightning CLI (FEAT-956).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
