.TH "LIGHTNING-NODE_INVOICE_LIST_PAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-list-paid \- FEAT-1044 node-invoice-list-paid
.SH SYNOPSIS
.B lightning node-invoice-list-paid
.SH DESCRIPTION
node-invoice-list-paid for lightning CLI (FEAT-1044).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
