.TH "LIGHTNING-CHANNEL_STATE_CHANGES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-state-changes \- FEAT-1352 channel-state-changes
.SH SYNOPSIS
.B lightning channel-state-changes
.SH DESCRIPTION
channel-state-changes for lightning CLI (FEAT-1352).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
