.TH "LIGHTNING-WALLET_NOTES_LAST_MODIFIED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-last-modified \- FEAT-1628 wallet-notes-last-modified
.SH SYNOPSIS
.B lightning wallet-notes-last-modified
.SH DESCRIPTION
wallet-notes-last-modified for lightning CLI (FEAT-1628).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
