.TH "LIGHTNING-CHANNEL-UPTIME-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-uptime-avg \- FEAT-3054 verb
.SH SYNOPSIS
.B lightning channel-uptime-avg
.SH DESCRIPTION
channel-uptime-avg for lightning CLI (FEAT-3054).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
