.TH LIGHTNING-CHANNEL-SPENDABLE-BALANCE-KURTOSIS-YEARLY 1
.SH NAME
lightning-channel-spendable-balance-kurtosis-yearly \- kurtosis of channel spendable balances over the past year
.SH SYNOPSIS
lightning channel-spendable-balance-kurtosis-yearly
.SH DESCRIPTION
Returns the kurtosis of channel spendable balances over the past year.
.SH SEE ALSO
lightning(1)
