.TH "LIGHTNING-CHANNEL-HTLC-COUNT-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-count-min \- FEAT-2967 channel-htlc-count-min verb
.SH SYNOPSIS
.B lightning channel-htlc-count-min
.SH DESCRIPTION
Min HTLC count in any channel for lightning CLI (FEAT-2967).
.PP
Output: JSON from CLN with key \fBhtlc_count_min\fR.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
