.TH "LIGHTNING-NODE_LISTCHANNELS_BY_STATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-by-state \- FEAT-1089 node-listchannels-by-state
.SH SYNOPSIS
.B lightning node-listchannels-by-state
.SH DESCRIPTION
node-listchannels-by-state for lightning CLI (FEAT-1089).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
