.TH "LIGHTNING-CHANNEL-MIN-HTLC-SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-min-htlc-set \- set minimum HTLC size for a channel
.SH SYNOPSIS
.B lightning channel-min-htlc-set
.I channel_id min_htlc_msat
.SH DESCRIPTION
Sets the minimum HTLC size in millisatoshis for the specified channel
via
.BR setchannel .
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-channel-max-htlc-set (1),
.BR lightning-fee (1)
