.TH "LIGHTNING-CHANNEL_CLOSE_ALL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-all \- schedule close of all channels
.SH SYNOPSIS
.B lightning channel-close-all\n.RB [ --force ]
.SH DESCRIPTION
Schedules cooperative close of all channels. Requires --force to proceed.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
