.TH "LIGHTNING-NODE-LISTINVOICES-UNPAID-LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listinvoices-unpaid-list \- FEAT-2349 list of unpaid invoices with label and amount
.SH SYNOPSIS
.B lightning node-listinvoices-unpaid-list
.SH DESCRIPTION
list of unpaid invoices with label and amount for lightning CLI (FEAT-2349).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
