.TH "LIGHTNING-CHANNEL_FORCE_CLOSE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-force-close \- FEAT-1116 channel-force-close
.SH SYNOPSIS
.B lightning channel-force-close
.SH DESCRIPTION
channel-force-close for lightning CLI (FEAT-1116).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
