.TH "LIGHTNING-WALLET_NOTES_PURGE_OLD" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-purge-old \- FEAT-1438 wallet-notes-purge-old
.SH SYNOPSIS
.B lightning wallet-notes-purge-old
.SH DESCRIPTION
wallet-notes-purge-old for lightning CLI (FEAT-1438).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
