.TH "LIGHTNING-CHANNEL_LOCKTIME" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-locktime \- FEAT-1580 channel-locktime
.SH SYNOPSIS
.B lightning channel-locktime
.SH DESCRIPTION
channel-locktime for lightning CLI (FEAT-1580).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
