.TH "LIGHTNING-CHANNEL-AGE-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-age-avg \- FEAT-3067 verb
.SH SYNOPSIS
.B lightning channel-age-avg
.SH DESCRIPTION
channel-age-avg for lightning CLI (FEAT-3067).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
