.TH "LIGHTNING-WALLET_NOTES_AGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-age \- FEAT-1668 wallet-notes-age
.SH SYNOPSIS
.B lightning wallet-notes-age
.SH DESCRIPTION
wallet-notes-age for lightning CLI (FEAT-1668).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
