.TH "LIGHTNING-INVOICE_EXPIRE_TIME" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-expire-time \- FEAT-1765 invoice-expire-time
.SH SYNOPSIS
.B lightning invoice-expire-time
.SH DESCRIPTION
invoice-expire-time for lightning CLI (FEAT-1765).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
