.TH "LIGHTNING-NODE_PENDING_FORWARDS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pending-forwards \- list pending (offered) forwards
.SH SYNOPSIS
.B lightning node-pending-forwards\n.RI [ output_dir ]
.SH DESCRIPTION
Returns forwarding payments currently in the offered state (in-flight).
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
