.TH "LIGHTNING-PEER_LIST_CONNECTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-list-connected \- FEAT-1337 peer-list-connected
.SH SYNOPSIS
.B lightning peer-list-connected
.SH DESCRIPTION
peer-list-connected for lightning CLI (FEAT-1337).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
