.TH "LIGHTNING-WALLET_TAG_ADD" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-tag-add \- add a tag to a wallet
.SH SYNOPSIS
.B lightning wallet-tag-add
.SH DESCRIPTION
Add a tag to a wallet.
.PP
Output: JSON object from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
