.TH "LIGHTNING-NODE_GRAPH_BASE_FEE_AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-base-fee-avg \- FEAT-1629 node-graph-base-fee-avg
.SH SYNOPSIS
.B lightning node-graph-base-fee-avg
.SH DESCRIPTION
node-graph-base-fee-avg for lightning CLI (FEAT-1629).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
