.TH "LIGHTNING-CHANNEL_OUT_FEES_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-out-fees-msat \- FEAT-1380 channel-out-fees-msat
.SH SYNOPSIS
.B lightning channel-out-fees-msat
.SH DESCRIPTION
channel-out-fees-msat for lightning CLI (FEAT-1380).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
