.TH "LIGHTNING-PEER-REMOTE-PCT-MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-remote-pct-max \- FEAT-2518 peer with highest remote balance percentage
.SH SYNOPSIS
.B lightning peer-remote-pct-max
.SH DESCRIPTION
Peer with highest remote balance percentage for lightning CLI (FEAT-2518).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
