.TH "LIGHTNING-WALLET_ENCRYPT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-encrypt \- store a passphrase hash in the wallet meta
.SH SYNOPSIS
.B lightning wallet-encrypt
.I wallet_name
.SH DESCRIPTION
Stores a SHA-256 hash of the passphrase in the wallet meta table.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
