.TH "LIGHTNING-CHANNEL-RECEIVABLE-BOTTOM5" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-receivable-bottom5 \- FEAT-2620 verb
.SH SYNOPSIS
.B lightning channel-receivable-bottom5
.SH DESCRIPTION
channel-receivable-bottom5 for lightning CLI (FEAT-2620).
.PP
Output: JSON from CLN with the bottom 5 channels by receivable_msat.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
