.TH "LIGHTNING-NODE-LISTINVOICES-LABEL-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listinvoices-label-count \- FEAT-2359 count of distinct invoice labels
.SH SYNOPSIS
.B lightning node-listinvoices-label-count
.SH DESCRIPTION
node-listinvoices-label-count for lightning CLI (FEAT-2359).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
