.TH "LIGHTNING-CHANNEL_SCID_ALIAS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-scid-alias \- FEAT-1256 channel-scid-alias
.SH SYNOPSIS
.B lightning channel-scid-alias
.SH DESCRIPTION
channel-scid-alias for lightning CLI (FEAT-1256).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
