.TH "LIGHTNING-CHANNEL_PEER_STATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-peer-state \- FEAT-1020 channel-peer-state
.SH SYNOPSIS
.B lightning channel-peer-state
.SH DESCRIPTION
channel-peer-state for lightning CLI (FEAT-1020).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
