.TH "LIGHTNING-CHANNEL_STATE_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-state-list \- FEAT-2105 verb
.SH SYNOPSIS
.B lightning channel-state-list
.SH DESCRIPTION
list channels with id and state for lightning CLI (FEAT-2105).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
