.TH "LIGHTNING-NODE_LISTCHANNELS_REMOTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-remote \- FEAT-1144 node-listchannels-remote
.SH SYNOPSIS
.B lightning node-listchannels-remote
.SH DESCRIPTION
node-listchannels-remote for lightning CLI (FEAT-1144).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
