.TH "LIGHTNING-CHANNEL_IN_MSATOSHI" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-in-msatoshi \- FEAT-1292 channel-in-msatoshi
.SH SYNOPSIS
.B lightning channel-in-msatoshi
.SH DESCRIPTION
channel-in-msatoshi for lightning CLI (FEAT-1292).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
