.TH LIGHTNING-CHANNEL_SPENDABLE_BALANCE_SKEWNESS_MONTHLY 1
.SH NAME
lightning-channel-spendable-balance-skewness-monthly \- compute channel-spendable-balance-skewness-monthly metric
.SH SYNOPSIS
.B lightning channel-spendable-balance-skewness-monthly
.SH DESCRIPTION
Outputs the channel-spendable-balance-skewness-monthly metric as JSON.
.SH EXIT STATUS
0 on success.
