.TH "LIGHTNING-WALLET_EXPORT_CSV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-export-csv \- export wallet ledger to CSV
.SH SYNOPSIS
.B lightning wallet-export-csv
.I wallet_name
.SH DESCRIPTION
Exports the wallet ledger as CSV to stdout.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
