.TH "LIGHTNING-INVOICE_CLAIM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-claim \- claim a hold invoice with a preimage
.SH SYNOPSIS
.B lightning invoice-claim
.SH DESCRIPTION
Claim a hold invoice with a preimage.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
