.TH "LIGHTNING-CHANNEL_FUNDING_OUTPUT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-funding-output \- FEAT-722 channel-funding-output verb
.SH SYNOPSIS
.B lightning channel-funding-output
.SH DESCRIPTION
channel-funding-output verb for lightning CLI (FEAT-722).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
