.TH "LIGHTNING-CHANNEL-CAPACITY-MAX-BTC" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-capacity-max-btc \- FEAT-2487 highest single channel capacity in BTC
.SH SYNOPSIS
.B lightning channel-capacity-max-btc
.SH DESCRIPTION
Highest single channel capacity in BTC for lightning CLI (FEAT-2487).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
