.TH "LIGHTNING-NODE_HTLC_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-htlc-count \- count in-flight HTLCs across all channels
.SH SYNOPSIS
.B lightning node-htlc-count

.SH DESCRIPTION
Returns the total number of in-flight HTLCs across all peer channels.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
