.TH "LIGHTNING-WALLET_NOTES_NEWEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-newest \- FEAT-1793 wallet-notes-newest
.SH SYNOPSIS
.B lightning wallet-notes-newest
.SH DESCRIPTION
wallet-notes-newest for lightning CLI (FEAT-1793).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
