.TH "LIGHTNING-NODE_FEERATE_CURRENT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-feerate-current \- FEAT-999 node-feerate-current
.SH SYNOPSIS
.B lightning node-feerate-current
.SH DESCRIPTION
node-feerate-current for lightning CLI (FEAT-999).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
