.TH "LIGHTNING-PEER_LIST_INACTIVE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-list-inactive \- FEAT-707 peer-list-inactive verb
.SH SYNOPSIS
.B lightning peer-list-inactive
.SH DESCRIPTION
peer-list-inactive verb for lightning CLI (FEAT-707).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
