.TH "LIGHTNING-CHANNEL_LAST_HTLC_ID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-last-htlc-id \- FEAT-1492 channel-last-htlc-id
.SH SYNOPSIS
.B lightning channel-last-htlc-id
.SH DESCRIPTION
channel-last-htlc-id for lightning CLI (FEAT-1492).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
