.TH "LIGHTNING-WALLET_LIST_ALL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-list-all \- list all wallets in the wallets directory
.SH SYNOPSIS
.B lightning wallet-list-all
.SH DESCRIPTION
List all wallets in the wallets directory.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
