.TH "LIGHTNING-NODE_LISTFORWARDS_BY_OUT_CHANNEL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-by-out-channel \- FEAT-1219 node-listforwards-by-out-channel
.SH SYNOPSIS
.B lightning node-listforwards-by-out-channel
.SH DESCRIPTION
node-listforwards-by-out-channel for lightning CLI (FEAT-1219).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
