.TH "LIGHTNING-CHANNEL_PRIVATE_CHECK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-private-check \- FEAT-766 channel-private-check verb
.SH SYNOPSIS
.B lightning channel-private-check
.SH DESCRIPTION
channel-private-check verb for lightning CLI (FEAT-766).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
