.TH "LIGHTNING-WALLET_DEFAULT_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-default-set \- set the default wallet
.SH SYNOPSIS
.B lightning wallet-default-set
.I wallet_name
.SH DESCRIPTION
Writes the wallet name to ~/.lightning/default_wallet.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
