.TH "LIGHTNING-WALLET_EXPORT_CSV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-export-csv \- FEAT-773 wallet-export-csv verb
.SH SYNOPSIS
.B lightning wallet-export-csv
.SH DESCRIPTION
wallet-export-csv verb for lightning CLI (FEAT-773).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
