.TH "LIGHTNING-NODE_FEES_PER_DAY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-fees-per-day \- show routing fees earned in the last 24 hours
.SH SYNOPSIS
.B lightning node-fees-per-day
.SH DESCRIPTION
Show routing fees earned in the last 24 hours.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
