.TH "LIGHTNING-INVOICE_EXPIRY_CHECK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-expiry-check \- FEAT-865 invoice-expiry-check
.SH SYNOPSIS
.B lightning invoice-expiry-check
.SH DESCRIPTION
invoice-expiry-check for lightning CLI (FEAT-865).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
