.TH "LIGHTNING-NODE_CHANNEL_RECEIVABLE_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-receivable-total \- FEAT-1259 node-channel-receivable-total
.SH SYNOPSIS
.B lightning node-channel-receivable-total
.SH DESCRIPTION
node-channel-receivable-total for lightning CLI (FEAT-1259).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
