.TH "LIGHTNING-CHANNEL-REMOTE-PCT-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-remote-pct-avg \- FEAT-3187 verb
.SH SYNOPSIS
.B lightning channel-remote-pct-avg
.SH DESCRIPTION
channel-remote-pct-avg for lightning CLI (FEAT-3187).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
