.TH "LIGHTNING-NODE-PAY-VOLUME-WEEKLY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-volume-weekly \- FEAT-2306 total msat sent per week (last 4 weeks)
.SH SYNOPSIS
.B lightning node-pay-volume-weekly
.SH DESCRIPTION
Total msat sent per week for the last 4 weeks for lightning CLI (FEAT-2306).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
