.TH "LIGHTNING-WALLET_NOTES_COUNT_UNPINNED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-count-unpinned \- FEAT-1528 wallet-notes-count-unpinned
.SH SYNOPSIS
.B lightning wallet-notes-count-unpinned
.SH DESCRIPTION
wallet-notes-count-unpinned for lightning CLI (FEAT-1528).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
