.TH "LIGHTNING-WALLET_NOTES_ALL_KEYS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-all-keys \- FEAT-1388 wallet-notes-all-keys
.SH SYNOPSIS
.B lightning wallet-notes-all-keys
.SH DESCRIPTION
wallet-notes-all-keys for lightning CLI (FEAT-1388).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
