.TH "LIGHTNING-NODE-LISTFORWARDS-FEE-TOTAL-14D" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-fee-total-14d \- FEAT-2461 total fee_msat from settled forwards in last 14 days
.SH SYNOPSIS
.B lightning node-listforwards-fee-total-14d
.SH DESCRIPTION
total fee_msat from settled forwards in last 14 days for lightning CLI (FEAT-2461).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
