.TH "LIGHTNING-NODE-LISTFORWARDS-FEE-SKEWNESS-MONTHLY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-fee-skewness-monthly \- FEAT-3465 verb
.SH SYNOPSIS
.B lightning node-listforwards-fee-skewness-monthly
.SH DESCRIPTION
node-listforwards-fee-skewness-monthly for lightning CLI (FEAT-3465).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
