.TH "LIGHTNING-PEER-LISTPAYS-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-listpays-count \- FEAT-2268 peer-listpays-count
.SH SYNOPSIS
.B lightning peer-listpays-count
.SH DESCRIPTION
peer-listpays-count for lightning CLI (FEAT-2268).
.PP
Output: JSON from CLN with total count of complete pays.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
