.TH "LIGHTNING-CHANNEL_REBALANCE_SUGGESTION" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-rebalance-suggestion \- FEAT-890 channel-rebalance-suggestion
.SH SYNOPSIS
.B lightning channel-rebalance-suggestion
.SH DESCRIPTION
channel-rebalance-suggestion for lightning CLI (FEAT-890).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
