.TH "LIGHTNING-NODE_LISTPAYS_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-total \- FEAT-1011 node-listpays-total
.SH SYNOPSIS
.B lightning node-listpays-total
.SH DESCRIPTION
node-listpays-total for lightning CLI (FEAT-1011).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
