.TH "LIGHTNING-PEER-HTLC-VALUE-STDDEV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-htlc-value-stddev \- FEAT-3063 verb
.SH SYNOPSIS
.B lightning peer-htlc-value-stddev
.SH DESCRIPTION
peer-htlc-value-stddev for lightning CLI (FEAT-3063).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
