.TH "LIGHTNING-NODE_INVOICE_EXPIRE_ALL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-expire-all \- FEAT-714 node-invoice-expire-all verb
.SH SYNOPSIS
.B lightning node-invoice-expire-all
.SH DESCRIPTION
node-invoice-expire-all verb for lightning CLI (FEAT-714).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
