.TH "LIGHTNING-CHANNEL_LAST_FEERATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-last-feerate \- FEAT-1710 channel-last-feerate
.SH SYNOPSIS
.B lightning channel-last-feerate
.SH DESCRIPTION
channel-last-feerate for lightning CLI (FEAT-1710).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
