.TH "LIGHTNING-CHANNEL_STATE_SUMMARY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-state-summary \- FEAT-1430 channel-state-summary
.SH SYNOPSIS
.B lightning channel-state-summary
.SH DESCRIPTION
channel-state-summary for lightning CLI (FEAT-1430).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
