.TH "LIGHTNING-PEER_CONNECTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-connected \- FEAT-1317 peer-connected
.SH SYNOPSIS
.B lightning peer-connected
.SH DESCRIPTION
peer-connected for lightning CLI (FEAT-1317).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
