.TH "LIGHTNING-INVOICE_LIST_PAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-paid \- FEAT-1815 invoice-list-paid
.SH SYNOPSIS
.B lightning invoice-list-paid
.SH DESCRIPTION
invoice-list-paid for lightning CLI (FEAT-1815).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
