.TH "LIGHTNING-WALLET_META_KEYS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-meta-keys \- FEAT-1358 wallet-meta-keys
.SH SYNOPSIS
.B lightning wallet-meta-keys
.SH DESCRIPTION
wallet-meta-keys for lightning CLI (FEAT-1358).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
