.TH "LIGHTNING-PEER-FEE-BASE-MEDIAN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-fee-base-median \- FEAT-3149 verb
.SH SYNOPSIS
.B lightning peer-fee-base-median
.SH DESCRIPTION
peer-fee-base-median for lightning CLI (FEAT-3149).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
