.TH "LIGHTNING-PEER_INVOICE_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-invoice-count \- FEAT-1177 peer-invoice-count
.SH SYNOPSIS
.B lightning peer-invoice-count
.SH DESCRIPTION
peer-invoice-count for lightning CLI (FEAT-1177).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
