.TH "LIGHTNING-NODE_INVOICE_PAID_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-paid-total \- FEAT-781 node-invoice-paid-total verb
.SH SYNOPSIS
.B lightning node-invoice-paid-total
.SH DESCRIPTION
node-invoice-paid-total verb for lightning CLI (FEAT-781).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
