.TH "LIGHTNING-WALLET_NOTES_LIST_BY_TAG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-list-by-tag \- FEAT-1868 wallet-notes-list-by-tag
.SH SYNOPSIS
.B lightning wallet-notes-list-by-tag
.SH DESCRIPTION
wallet-notes-list-by-tag for lightning CLI (FEAT-1868).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
