.TH "LIGHTNING-NODE_FEERATE_MEDIUM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-feerate-medium \- FEAT-1399 node-feerate-medium
.SH SYNOPSIS
.B lightning node-feerate-medium
.SH DESCRIPTION
node-feerate-medium for lightning CLI (FEAT-1399).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
