.TH "LIGHTNING-NODE_FEE_BASE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-fee-base \- FEAT-879 node-fee-base
.SH SYNOPSIS
.B lightning node-fee-base
.SH DESCRIPTION
node-fee-base for lightning CLI (FEAT-879).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
