.TH "LIGHTNING-NODE-GRAPH-AVG-BASE-FEE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-avg-base-fee \- FEAT-1939 node-graph-avg-base-fee
.SH SYNOPSIS
.B lightning node-graph-avg-base-fee
.SH DESCRIPTION
node-graph-avg-base-fee for lightning CLI (FEAT-1939).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
