.TH "LIGHTNING-WALLET_STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-status \- show integrity and size of a wallet database
.SH SYNOPSIS
.B lightning wallet-status
.SH DESCRIPTION
Show integrity and size of a wallet database.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
