.TH "LIGHTNING-NODE-PAY-AMOUNT-RANGE-DAILY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-amount-range-daily \- FEAT-3492 verb
.SH SYNOPSIS
.B lightning node-pay-amount-range-daily
.SH DESCRIPTION
node-pay-amount-range-daily for lightning CLI (FEAT-3492).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
