.TH "LIGHTNING-PEER_ACTIVE_CHANNELS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-active-channels \- FEAT-1137 peer-active-channels
.SH SYNOPSIS
.B lightning peer-active-channels
.SH DESCRIPTION
peer-active-channels for lightning CLI (FEAT-1137).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
