.TH "LIGHTNING-NODE-INVOICE-PAID-TOTAL-MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-paid-total-msat \- FEAT-1914 node-invoice-paid-total-msat
.SH SYNOPSIS
.B lightning node-invoice-paid-total-msat
.SH DESCRIPTION
node-invoice-paid-total-msat for lightning CLI (FEAT-1914).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
