.TH "LIGHTNING-CHANNEL_SCID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-scid \- FEAT-1576 channel-scid
.SH SYNOPSIS
.B lightning channel-scid
.SH DESCRIPTION
channel-scid for lightning CLI (FEAT-1576).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
