.TH "LIGHTNING-CHANNEL-FEE-REVENUE-MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-fee-revenue-max \- FEAT-2325 verb
.SH SYNOPSIS
.B lightning channel-fee-revenue-max
.SH DESCRIPTION
channel-fee-revenue-max for lightning CLI (FEAT-2325).
.PP
Output: JSON from CLN with the channel with highest estimated fee revenue (ppm * capacity).
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
