.TH "LIGHTNING-CHANNEL_THEIR_CLTV_DELTA_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-their-cltv-delta-total \- FEAT-1640 channel-their-cltv-delta-total
.SH SYNOPSIS
.B lightning channel-their-cltv-delta-total
.SH DESCRIPTION
channel-their-cltv-delta-total for lightning CLI (FEAT-1640).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
