.TH "LIGHTNING-NODE_CLOSE_CHANNEL_CHECK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-close-channel-check \- FEAT-869 node-close-channel-check
.SH SYNOPSIS
.B lightning node-close-channel-check
.SH DESCRIPTION
node-close-channel-check for lightning CLI (FEAT-869).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
