.TH "LIGHTNING-PEER_CHANNEL_STATES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-channel-states \- FEAT-1907 peer-channel-states
.SH SYNOPSIS
.B lightning peer-channel-states
.SH DESCRIPTION
peer-channel-states for lightning CLI (FEAT-1907).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
