.TH "LIGHTNING-PEER_SHORT_CHANNEL_IDS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-short-channel-ids \- FEAT-1697 peer-short-channel-ids
.SH SYNOPSIS
.B lightning peer-short-channel-ids
.SH DESCRIPTION
peer-short-channel-ids for lightning CLI (FEAT-1697).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
