.TH "LIGHTNING-WALLET_ARCHIVE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-archive \- copy wallet database to an archive file
.SH SYNOPSIS
.B lightning wallet-archive
.I wallet_name
.SH DESCRIPTION
Copies the wallet SQLite database to an archive file.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
