.TH "LIGHTNING-NODE_PAY_MIN_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-min-msat \- FEAT-1141 node-pay-min-msat
.SH SYNOPSIS
.B lightning node-pay-min-msat
.SH DESCRIPTION
node-pay-min-msat for lightning CLI (FEAT-1141).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
