.TH LIGHTNING-NODE-INVOICE-EXPIRED-COUNT-DAILY 1
.SH NAME
lightning-node-invoice-expired-count-daily \- count of expired invoices over the past day
.SH SYNOPSIS
lightning node-invoice-expired-count-daily
.SH DESCRIPTION
Returns the number of expired invoices aggregated over the past day.
.SH SEE ALSO
lightning(1)
