.TH "LIGHTNING-CHANNEL_INFLIGHT_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-inflight-count \- FEAT-962 channel-inflight-count
.SH SYNOPSIS
.B lightning channel-inflight-count
.SH DESCRIPTION
channel-inflight-count for lightning CLI (FEAT-962).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
