.TH "LIGHTNING-CHANNEL-HTLC-TIMEOUT-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-timeout-range \- FEAT-3150 verb
.SH SYNOPSIS
.B lightning channel-htlc-timeout-range
.SH DESCRIPTION
channel-htlc-timeout-range for lightning CLI (FEAT-3150).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
