.TH "LIGHTNING-CHANNEL_TOTAL_SENT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-total-sent \- FEAT-1026 channel-total-sent
.SH SYNOPSIS
.B lightning channel-total-sent
.SH DESCRIPTION
channel-total-sent for lightning CLI (FEAT-1026).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
