.TH "LIGHTNING-WALLET_RECEIVE_ADDRESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-receive-address \- FEAT-1168 wallet-receive-address
.SH SYNOPSIS
.B lightning wallet-receive-address
.SH DESCRIPTION
wallet-receive-address for lightning CLI (FEAT-1168).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
