.TH "LIGHTNING-CHANNEL-CAPACITY-MIN-BTC" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-capacity-min-btc \- FEAT-2497 lowest single channel capacity in BTC
.SH SYNOPSIS
.B lightning channel-capacity-min-btc
.SH DESCRIPTION
lowest single channel capacity in BTC for lightning CLI (FEAT-2497).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
