.TH "LIGHTNING-WALLET_OPEN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-open \- FEAT-978 wallet-open
.SH SYNOPSIS
.B lightning wallet-open
.SH DESCRIPTION
wallet-open for lightning CLI (FEAT-978).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
