.TH "LIGHTNING-WALLET_NOTES_COUNT_BY_VALUE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-count-by-value \- FEAT-1583 wallet-notes-count-by-value
.SH SYNOPSIS
.B lightning wallet-notes-count-by-value
.SH DESCRIPTION
wallet-notes-count-by-value for lightning CLI (FEAT-1583).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
