.TH "LIGHTNING-CHANNEL_CLOSE_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-count \- FEAT-1726 channel-close-count
.SH SYNOPSIS
.B lightning channel-close-count
.SH DESCRIPTION
channel-close-count for lightning CLI (FEAT-1726).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
