.TH "LIGHTNING-NODE_GRAPH_AVG_FEE_PPM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-avg-fee-ppm \- FEAT-1679 node-graph-avg-fee-ppm
.SH SYNOPSIS
.B lightning node-graph-avg-fee-ppm
.SH DESCRIPTION
node-graph-avg-fee-ppm for lightning CLI (FEAT-1679).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
