.TH "LIGHTNING-CHANNEL_INITIATED_BY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-initiated-by \- FEAT-820 channel-initiated-by verb
.SH SYNOPSIS
.B lightning channel-initiated-by
.SH DESCRIPTION
channel-initiated-by verb for lightning CLI (FEAT-820).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
