.TH "LIGHTNING-CHANNEL_REMOTE_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-remote-msat \- FEAT-896 channel-remote-msat
.SH SYNOPSIS
.B lightning channel-remote-msat
.SH DESCRIPTION
channel-remote-msat for lightning CLI (FEAT-896).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
