.TH "LIGHTNING-PEER_CHANNELS_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-channels-count \- FEAT-667 peer-channels-count verb
.SH SYNOPSIS
.B lightning peer-channels-count
.SH DESCRIPTION
peer-channels-count verb for lightning CLI (FEAT-667).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
