.TH "LIGHTNING-PEER-LOCAL-RESERVE-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-local-reserve-range \- FEAT-3129 verb
.SH SYNOPSIS
.B lightning peer-local-reserve-range
.SH DESCRIPTION
peer-local-reserve-range for lightning CLI (FEAT-3129).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
