.TH "LIGHTNING-PEER_TOTAL_SENT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-total-sent \- FEAT-867 peer-total-sent
.SH SYNOPSIS
.B lightning peer-total-sent
.SH DESCRIPTION
peer-total-sent for lightning CLI (FEAT-867).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
