.TH "LIGHTNING-CHANNEL_CLOSE_TO" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-to \- FEAT-1242 channel-close-to
.SH SYNOPSIS
.B lightning channel-close-to
.SH DESCRIPTION
channel-close-to for lightning CLI (FEAT-1242).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
