.TH "LIGHTNING-NODE_PEER_COUNT_CONNECTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-peer-count-connected \- FEAT-1294 node-peer-count-connected
.SH SYNOPSIS
.B lightning node-peer-count-connected
.SH DESCRIPTION
node-peer-count-connected for lightning CLI (FEAT-1294).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
