.TH "LIGHTNING-INVOICE_LIST_ALL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-all \- FEAT-1055 invoice-list-all
.SH SYNOPSIS
.B lightning invoice-list-all
.SH DESCRIPTION
invoice-list-all for lightning CLI (FEAT-1055).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
