.TH "LIGHTNING-WALLET_NOTES_SEARCH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-search \- FEAT-888 wallet-notes-search
.SH SYNOPSIS
.B lightning wallet-notes-search
.SH DESCRIPTION
wallet-notes-search for lightning CLI (FEAT-888).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
