.TH "LIGHTNING-WALLET_NOTES_MOVE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-move \- FEAT-1343 wallet-notes-move
.SH SYNOPSIS
.B lightning wallet-notes-move
.SH DESCRIPTION
wallet-notes-move for lightning CLI (FEAT-1343).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
