.TH "LIGHTNING-CHANNEL_FUNDING_BLOCK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-funding-block \- FEAT-1510 channel-funding-block
.SH SYNOPSIS
.B lightning channel-funding-block
.SH DESCRIPTION
channel-funding-block for lightning CLI (FEAT-1510).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
