.TH "LIGHTNING-WALLET_NOTES_ROTATE_KEY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-rotate-key \- FEAT-1488 wallet-notes-rotate-key
.SH SYNOPSIS
.B lightning wallet-notes-rotate-key
.SH DESCRIPTION
wallet-notes-rotate-key for lightning CLI (FEAT-1488).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
