.TH "LIGHTNING-PEER_SCORE_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-score-list \- FEAT-697 peer-score-list verb
.SH SYNOPSIS
.B lightning peer-score-list
.SH DESCRIPTION
peer-score-list verb for lightning CLI (FEAT-697).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
