.TH "LIGHTNING-CHANNEL_CAPACITY_PERCENT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-capacity-percent \- FEAT-810 channel-capacity-percent verb
.SH SYNOPSIS
.B lightning channel-capacity-percent
.SH DESCRIPTION
channel-capacity-percent verb for lightning CLI (FEAT-810).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
