.TH "LIGHTNING-CHANNEL_COMMITMENT_FEERATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-commitment-feerate \- FEAT-1536 channel-commitment-feerate
.SH SYNOPSIS
.B lightning channel-commitment-feerate
.SH DESCRIPTION
channel-commitment-feerate for lightning CLI (FEAT-1536).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
