.TH "LIGHTNING-INVOICE_BOLT11_DECODE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-bolt11-decode \- FEAT-1125 invoice-bolt11-decode
.SH SYNOPSIS
.B lightning invoice-bolt11-decode
.SH DESCRIPTION
invoice-bolt11-decode for lightning CLI (FEAT-1125).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
