.TH "LIGHTNING-NODE-PAY-RECENT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-recent \- FEAT-2239 last 5 complete payments
.SH SYNOPSIS
.B lightning node-pay-recent
.SH DESCRIPTION
node-pay-recent for lightning CLI (FEAT-2239).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
