.TH "LIGHTNING-CHANNEL_OPEN_BLOCK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-block \- FEAT-1196 channel-open-block
.SH SYNOPSIS
.B lightning channel-open-block
.SH DESCRIPTION
channel-open-block for lightning CLI (FEAT-1196).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
