.TH "LIGHTNING-PEER_ALIAS_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-alias-set \- FEAT-897 peer-alias-set
.SH SYNOPSIS
.B lightning peer-alias-set
.SH DESCRIPTION
peer-alias-set for lightning CLI (FEAT-897).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
