.TH "LIGHTNING-CHANNEL_CAPACITY_RANK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-capacity-rank \- FEAT-1100 channel-capacity-rank
.SH SYNOPSIS
.B lightning channel-capacity-rank
.SH DESCRIPTION
channel-capacity-rank for lightning CLI (FEAT-1100).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
