.TH "LIGHTNING-PEER_TOTAL_RECEIVED_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-total-received-msat \- FEAT-1657 peer-total-received-msat
.SH SYNOPSIS
.B lightning peer-total-received-msat
.SH DESCRIPTION
peer-total-received-msat for lightning CLI (FEAT-1657).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
