.TH "LIGHTNING-CHANNEL-TO-US-MSAT-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-to-us-msat-total \- FEAT-1940 channel-to-us-msat-total
.SH SYNOPSIS
.B lightning channel-to-us-msat-total
.SH DESCRIPTION
channel-to-us-msat-total for lightning CLI (FEAT-1940).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
