.TH "LIGHTNING-NODE-INVOICE-PENDING-COUNT-YEAR" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-pending-count-year \- FEAT-3263 verb
.SH SYNOPSIS
.B lightning node-invoice-pending-count-year
.SH DESCRIPTION
node-invoice-pending-count-year for lightning CLI (FEAT-3263).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
