.TH "LIGHTNING-CHANNEL_MAX_INFLIGHT_HTLC" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-max-inflight-htlc \- FEAT-1236 channel-max-inflight-htlc
.SH SYNOPSIS
.B lightning channel-max-inflight-htlc
.SH DESCRIPTION
channel-max-inflight-htlc for lightning CLI (FEAT-1236).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
