.TH "LIGHTNING-NODE_GRAPH_PEERS_CONNECTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-peers-connected \- FEAT-1894 node-graph-peers-connected
.SH SYNOPSIS
.B lightning node-graph-peers-connected
.SH DESCRIPTION
node-graph-peers-connected for lightning CLI (FEAT-1894).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
