.TH "LIGHTNING-NODE_LISTCHANNELS_BY_AGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-by-age \- FEAT-1864 node-listchannels-by-age
.SH SYNOPSIS
.B lightning node-listchannels-by-age
.SH DESCRIPTION
node-listchannels-by-age for lightning CLI (FEAT-1864).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
