.TH "LIGHTNING-PEER-SPENDABLE-SKEWNESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-spendable-skewness \- FEAT-3457 verb
.SH SYNOPSIS
.B lightning peer-spendable-skewness
.SH DESCRIPTION
peer-spendable-skewness for lightning CLI (FEAT-3457).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
