.TH "LIGHTNING-NODE_SYNCED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-synced \- check if node is synced to chain and gossip
.SH SYNOPSIS
.B lightning node-synced
.SH DESCRIPTION
Check if node is synced to chain and gossip.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
