.TH "LIGHTNING-CHANNEL_PEER_NODE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-peer-node \- FEAT-1250 channel-peer-node
.SH SYNOPSIS
.B lightning channel-peer-node
.SH DESCRIPTION
channel-peer-node for lightning CLI (FEAT-1250).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
