.TH "LIGHTNING-CHANNEL_HTLC_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-count \- FEAT-1302 channel-htlc-count
.SH SYNOPSIS
.B lightning channel-htlc-count
.SH DESCRIPTION
channel-htlc-count for lightning CLI (FEAT-1302).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
