.TH "LIGHTNING-NODE-INVOICE-PAID-LAST-30D" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-paid-last-30d \- FEAT-2404 count of invoices paid in last 30 days
.SH SYNOPSIS
.B lightning node-invoice-paid-last-30d
.SH DESCRIPTION
Count of invoices paid in last 30 days for lightning CLI (FEAT-2404).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
