.TH "LIGHTNING-CHANNEL-HTLC-OUTGOING-VALUE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-outgoing-value \- FEAT-2327 verb
.SH SYNOPSIS
.B lightning channel-htlc-outgoing-value
.SH DESCRIPTION
channel-htlc-outgoing-value for lightning CLI (FEAT-2327).
.PP
Output: JSON from CLN with total value of outgoing in-flight HTLCs across all channels.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
