.TH "LIGHTNING-CHANNEL_ACTIVE_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-active-count \- FEAT-692 channel-active-count verb
.SH SYNOPSIS
.B lightning channel-active-count
.SH DESCRIPTION
channel-active-count verb for lightning CLI (FEAT-692).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
