.TH "LIGHTNING-WALLET_META_GET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-meta-get \- FEAT-733 wallet-meta-get verb
.SH SYNOPSIS
.B lightning wallet-meta-get
.SH DESCRIPTION
wallet-meta-get verb for lightning CLI (FEAT-733).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
