.TH "LIGHTNING-NODE_GRAPH_HIGH_FEE_NODES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-high-fee-nodes \- FEAT-1709 node-graph-high-fee-nodes
.SH SYNOPSIS
.B lightning node-graph-high-fee-nodes
.SH DESCRIPTION
node-graph-high-fee-nodes for lightning CLI (FEAT-1709).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
