.TH "LIGHTNING-CHANNEL-HTLC-MIN-MSAT-STDDEV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-min-msat-stddev \- FEAT-3305 verb
.SH SYNOPSIS
.B lightning channel-htlc-min-msat-stddev
.SH DESCRIPTION
channel-htlc-min-msat-stddev for lightning CLI (FEAT-3305).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
