.TH "LIGHTNING-WALLET_BACKUP_PATH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-backup-path \- FEAT-1148 wallet-backup-path
.SH SYNOPSIS
.B lightning wallet-backup-path
.SH DESCRIPTION
wallet-backup-path for lightning CLI (FEAT-1148).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
