.TH LIGHTNING-PEER-BOTH-RESERVES-SKEWNESS 1
.SH NAME
lightning-peer-both-reserves-skewness \- skewness of both peer reserves
.SH SYNOPSIS
lightning peer-both-reserves-skewness
.SH DESCRIPTION
Returns the skewness of both peer reserves.
.SH OUTPUT
JSON object with key \fBboth_reserves_skewness_peer\fR.
