.TH "LIGHTNING-CHANNEL-FEE-PROPORTIONAL-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-fee-proportional-range \- FEAT-3141 verb
.SH SYNOPSIS
.B lightning channel-fee-proportional-range
.SH DESCRIPTION
channel-fee-proportional-range for lightning CLI (FEAT-3141).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
