.TH "LIGHTNING-CHANNEL-SHORT-CHANNEL-ID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-short-channel-id \- FEAT-2055 Show short_channel_id for peer channels
.SH SYNOPSIS
.B lightning channel-short-channel-id
.SH DESCRIPTION
Show short_channel_id for peer channels (FEAT-2055).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
