.TH "LIGHTNING-NODE-LISTFORWARDS-COUNT-MONTH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-count-month \- FEAT-3065 verb
.SH SYNOPSIS
.B lightning node-listforwards-count-month
.SH DESCRIPTION
node-listforwards-count-month for lightning CLI (FEAT-3065).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
