.TH "LIGHTNING-CHANNEL-CAPACITY-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-capacity-range \- FEAT-2500 range of channel capacities in msat
.SH SYNOPSIS
.B lightning channel-capacity-range
.SH DESCRIPTION
range of channel capacities in msat for lightning CLI (FEAT-2500).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
