.TH "LIGHTNING-NODE_MAX_CHANNEL_SIZE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-max-channel-size \- show maximum channel size configuration
.SH SYNOPSIS
.B lightning node-max-channel-size
.SH DESCRIPTION
Show maximum channel size configuration.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
