.TH "LIGHTNING-WALLET_SEED_CHECK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-seed-check \- FEAT-1093 wallet-seed-check
.SH SYNOPSIS
.B lightning wallet-seed-check
.SH DESCRIPTION
wallet-seed-check for lightning CLI (FEAT-1093).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
