.TH "LIGHTNING-PEER_BANDWIDTH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-bandwidth \- FEAT-977 peer-bandwidth
.SH SYNOPSIS
.B lightning peer-bandwidth
.SH DESCRIPTION
peer-bandwidth for lightning CLI (FEAT-977).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
