.TH "LIGHTNING-INVOICE_DECODE_AMOUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-decode-amount \- decode amount from a BOLT11 invoice
.SH SYNOPSIS
.B lightning invoice-decode-amount
.SH DESCRIPTION
Decode amount from a BOLT11 invoice.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
