.TH "LIGHTNING-PEER_TOTAL_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-total-capacity \- FEAT-1787 peer-total-capacity
.SH SYNOPSIS
.B lightning peer-total-capacity
.SH DESCRIPTION
peer-total-capacity for lightning CLI (FEAT-1787).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
