.TH "LIGHTNING-NODE_REBALANCE_STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-rebalance-status \- FEAT-958 node-rebalance-status
.SH SYNOPSIS
.B lightning node-rebalance-status
.SH DESCRIPTION
node-rebalance-status for lightning CLI (FEAT-958).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
