.TH "LIGHTNING-PEER_CONNECTED_TIME" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-connected-time \- FEAT-1747 peer-connected-time
.SH SYNOPSIS
.B lightning peer-connected-time
.SH DESCRIPTION
peer-connected-time for lightning CLI (FEAT-1747).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
