.TH "LIGHTNING-CHANNEL-RESERVE-LOCAL-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-reserve-local-min \- FEAT-3034 verb
.SH SYNOPSIS
.B lightning channel-reserve-local-min
.SH DESCRIPTION
channel-reserve-local-min for lightning CLI (FEAT-3034).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
