.TH "LIGHTNING-NODE_INVOICE_LABEL_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-label-list \- FEAT-1624 node-invoice-label-list
.SH SYNOPSIS
.B lightning node-invoice-label-list
.SH DESCRIPTION
node-invoice-label-list for lightning CLI (FEAT-1624).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
