.TH "LIGHTNING-CHANNEL_DISABLED_CHECK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-disabled-check \- list channels that are not active
.SH SYNOPSIS
.B lightning channel-disabled-check
.SH DESCRIPTION
List channels that are not active.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
