.TH "LIGHTNING-NODE-PAY-FEE-VARIANCE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-fee-variance \- FEAT-2616 verb
.SH SYNOPSIS
.B lightning node-pay-fee-variance
.SH DESCRIPTION
node-pay-fee-variance for lightning CLI (FEAT-2616).
.PP
Output: JSON from CLN with the variance of fee_msat among completed payments.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
