.TH "LIGHTNING-WALLET_UNLOCK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-unlock \- FEAT-968 wallet-unlock
.SH SYNOPSIS
.B lightning wallet-unlock
.SH DESCRIPTION
wallet-unlock for lightning CLI (FEAT-968).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
