.TH "LIGHTNING-NODE_WATCH_INVOICES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-watch-invoices \- FEAT-829 node-watch-invoices verb
.SH SYNOPSIS
.B lightning node-watch-invoices
.SH DESCRIPTION
node-watch-invoices verb for lightning CLI (FEAT-829).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
