.TH "LIGHTNING-CHANNEL_PUSH_MSAT_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-push-msat-total \- FEAT-1782 channel-push-msat-total
.SH SYNOPSIS
.B lightning channel-push-msat-total
.SH DESCRIPTION
channel-push-msat-total for lightning CLI (FEAT-1782).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
