.TH "LIGHTNING-NODE-PAY-VOLUME-30D" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-volume-30d \- FEAT-2396 total amount_sent_msat for complete pays in last 30 days
.SH SYNOPSIS
.B lightning node-pay-volume-30d
.SH DESCRIPTION
node-pay-volume-30d verb for lightning CLI (FEAT-2396).
.PP
Output: JSON from CLN with the total amount_sent_msat for all complete payments in the past 30 days.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
