.TH LIGHTNING-PEER-SPENDABLE-BALANCE-KURTOSIS-MONTHLY 1
.SH NAME
lightning-peer-spendable-balance-kurtosis-monthly \- kurtosis of peer spendable balances over the past month
.SH SYNOPSIS
lightning peer-spendable-balance-kurtosis-monthly
.SH DESCRIPTION
Returns the kurtosis of peer spendable balances over the past month.
.SH SEE ALSO
lightning(1)
