.TH "LIGHTNING-CHANNEL_PEER_SCID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-peer-scid \- FEAT-1490 channel-peer-scid
.SH SYNOPSIS
.B lightning channel-peer-scid
.SH DESCRIPTION
channel-peer-scid for lightning CLI (FEAT-1490).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
