.TH "LIGHTNING-CHANNEL_TO_US_RATIO" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-to-us-ratio \- FEAT-1742 channel-to-us-ratio
.SH SYNOPSIS
.B lightning channel-to-us-ratio
.SH DESCRIPTION
channel-to-us-ratio for lightning CLI (FEAT-1742).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
