.TH "LIGHTNING-PEER-RECEIVABLE-BALANCE-KURTOSIS" 1 "May 2026" "lightning" "User Commands"
.SH NAME
lightning-peer-receivable-balance-kurtosis \- FEAT-3531 peer-receivable-balance-kurtosis
.SH SYNOPSIS
.B lightning peer-receivable-balance-kurtosis
.SH DESCRIPTION
Kurtosis of receivable balance across peers (FEAT-3531).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
