.TH "LIGHTNING-CHANNEL_HTLC_OUT_TOTAL_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-out-total-msat \- FEAT-1692 channel-htlc-out-total-msat
.SH SYNOPSIS
.B lightning channel-htlc-out-total-msat
.SH DESCRIPTION
channel-htlc-out-total-msat for lightning CLI (FEAT-1692).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
