.TH "LIGHTNING-NODE-LISTFORWARDS-FEE-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-fee-range \- FEAT-2759 node-listforwards-fee-range
.SH SYNOPSIS
.B lightning node-listforwards-fee-range
.SH DESCRIPTION
Reports the range (max minus min) of forward fees for lightning CLI (FEAT-2759).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
