.TH "LIGHTNING-NODE_VERSION" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-version \- show CLN node version and network
.SH SYNOPSIS
.B lightning node-version

.SH DESCRIPTION
Returns the CLN version string and network name.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
