.TH "LIGHTNING-CHANNEL_PEER_CONNECTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-peer-connected \- FEAT-1586 channel-peer-connected
.SH SYNOPSIS
.B lightning channel-peer-connected
.SH DESCRIPTION
channel-peer-connected for lightning CLI (FEAT-1586).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
