.TH "LIGHTNING-WALLET_TAG_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-tag-set \- FEAT-1073 wallet-tag-set
.SH SYNOPSIS
.B lightning wallet-tag-set
.SH DESCRIPTION
wallet-tag-set for lightning CLI (FEAT-1073).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
