.TH "LIGHTNING-CHANNEL_RESERVE_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-reserve-msat \- FEAT-1160 channel-reserve-msat
.SH SYNOPSIS
.B lightning channel-reserve-msat
.SH DESCRIPTION
channel-reserve-msat for lightning CLI (FEAT-1160).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
