.TH "LIGHTNING-CHANNEL-HTLC-VALUE-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-value-avg \- FEAT-2402 average total HTLC value per channel
.SH SYNOPSIS
.B lightning channel-htlc-value-avg
.SH DESCRIPTION
Average total HTLC value per channel for lightning CLI (FEAT-2402).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
