.TH "LIGHTNING-NODE_PAY_HASH_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-hash-list \- FEAT-1411 node-pay-hash-list
.SH SYNOPSIS
.B lightning node-pay-hash-list
.SH DESCRIPTION
node-pay-hash-list for lightning CLI (FEAT-1411).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
