.TH "LIGHTNING-CHANNEL_PRIVATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-private \- FEAT-1092 channel-private
.SH SYNOPSIS
.B lightning channel-private
.SH DESCRIPTION
channel-private for lightning CLI (FEAT-1092).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
