.TH "LIGHTNING-PEER-HTLC-COUNT-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-htlc-count-range \- FEAT-3257 verb
.SH SYNOPSIS
.B lightning peer-htlc-count-range
.SH DESCRIPTION
peer-htlc-count-range for lightning CLI (FEAT-3257).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
