.TH "LIGHTNING-CHANNEL_TO_THEM_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-to-them-msat \- FEAT-1732 channel-to-them-msat
.SH SYNOPSIS
.B lightning channel-to-them-msat
.SH DESCRIPTION
channel-to-them-msat for lightning CLI (FEAT-1732).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
