.TH "LIGHTNING-WALLET_NOTES_IMPORT_CSV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-import-csv \- FEAT-1798 wallet-notes-import-csv
.SH SYNOPSIS
.B lightning wallet-notes-import-csv
.SH DESCRIPTION
wallet-notes-import-csv for lightning CLI (FEAT-1798).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
