.TH "LIGHTNING-NODE_PAYMENT_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-payment-count \- FEAT-1004 node-payment-count
.SH SYNOPSIS
.B lightning node-payment-count
.SH DESCRIPTION
node-payment-count for lightning CLI (FEAT-1004).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
