.TH "LIGHTNING-CHANNEL-HTLC-COUNT-BY-CHANNEL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-count-by-channel \- FEAT-2342 count of HTLCs per channel
.SH SYNOPSIS
.B lightning channel-htlc-count-by-channel
.SH DESCRIPTION
count of HTLCs per channel for lightning CLI (FEAT-2342).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
