.TH "LIGHTNING-NODE_CHANNEL_UPDATES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-updates \- count gossip channel updates
.SH SYNOPSIS
.B lightning node-channel-updates
.SH DESCRIPTION
Count gossip channel updates.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
