.TH "LIGHTNING-NODE_LISTPEERS_ID_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpeers-id-list \- FEAT-1464 node-listpeers-id-list
.SH SYNOPSIS
.B lightning node-listpeers-id-list
.SH DESCRIPTION
node-listpeers-id-list for lightning CLI (FEAT-1464).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
