.TH "LIGHTNING-CHANNEL_RESERVE_CHECK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-reserve-check \- FEAT-782 channel-reserve-check verb
.SH SYNOPSIS
.B lightning channel-reserve-check
.SH DESCRIPTION
channel-reserve-check verb for lightning CLI (FEAT-782).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
