.TH "LIGHTNING-WALLET_EXPORT_KEYS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-export-keys \- FEAT-1133 wallet-export-keys
.SH SYNOPSIS
.B lightning wallet-export-keys
.SH DESCRIPTION
wallet-export-keys for lightning CLI (FEAT-1133).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
