.TH "LIGHTNING-NODE_PAYMENT_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-payment-count \- count payments by status
.SH SYNOPSIS
.B lightning node-payment-count
.SH DESCRIPTION
Count payments by status.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
