.TH "LIGHTNING-PEER-CHANNEL-AGE-STATS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-channel-age-stats \- FEAT-2156 verb
.SH SYNOPSIS
.B lightning peer-channel-age-stats
.SH DESCRIPTION
verb for lightning CLI (FEAT-2156).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
