.TH "LIGHTNING-CHANNEL_OUR_HTLC_MINIMUM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-our-htlc-minimum \- FEAT-1476 channel-our-htlc-minimum
.SH SYNOPSIS
.B lightning channel-our-htlc-minimum
.SH DESCRIPTION
channel-our-htlc-minimum for lightning CLI (FEAT-1476).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
