.TH "LIGHTNING-INVOICE_LIST_BY_INDEX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-by-index \- FEAT-1585 invoice-list-by-index
.SH SYNOPSIS
.B lightning invoice-list-by-index
.SH DESCRIPTION
invoice-list-by-index for lightning CLI (FEAT-1585).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
