.TH "LIGHTNING-NODE_INFO_SHORT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-info-short \- show brief node info
.SH SYNOPSIS
.B lightning node-info-short
.SH DESCRIPTION
Show brief node info.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
