.TH "LIGHTNING-NODE_LISTPAYS_MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-min \- FEAT-1781 node-listpays-min
.SH SYNOPSIS
.B lightning node-listpays-min
.SH DESCRIPTION
node-listpays-min for lightning CLI (FEAT-1781).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
