.TH "LIGHTNING-CHANNEL_OUR_FEE_PPM_AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-our-fee-ppm-avg \- FEAT-1696 channel-our-fee-ppm-avg
.SH SYNOPSIS
.B lightning channel-our-fee-ppm-avg
.SH DESCRIPTION
channel-our-fee-ppm-avg for lightning CLI (FEAT-1696).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
