.TH "LIGHTNING-PEER-REMOTE-RESERVE-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-remote-reserve-min \- FEAT-3113 verb
.SH SYNOPSIS
.B lightning peer-remote-reserve-min
.SH DESCRIPTION
peer-remote-reserve-min for lightning CLI (FEAT-3113).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
