.TH "LIGHTNING-CHANNEL_OUR_CLTV_DELTA_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-our-cltv-delta-total \- FEAT-1632 channel-our-cltv-delta-total
.SH SYNOPSIS
.B lightning channel-our-cltv-delta-total
.SH DESCRIPTION
channel-our-cltv-delta-total for lightning CLI (FEAT-1632).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
