.TH "LIGHTNING-PEER_SCORE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-score \- FEAT-1107 peer-score
.SH SYNOPSIS
.B lightning peer-score
.SH DESCRIPTION
peer-score for lightning CLI (FEAT-1107).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
