.TH "LIGHTNING-NODE_CHECK_FUNDS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-check-funds \- show total on-chain and off-chain funds
.SH SYNOPSIS
.B lightning node-check-funds
.RI [ channel_id ]
.SH DESCRIPTION
Returns confirmed on-chain output value and off-chain channel balance.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
