.TH "LIGHTNING-NODE-PAY-FEE-PCT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-fee-pct \- FEAT-2059 Total fee as a percentage of total amount sent
.SH SYNOPSIS
.B lightning node-pay-fee-pct
.SH DESCRIPTION
Total fee as a percentage of total amount sent (FEAT-2059).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
