.TH "LIGHTNING-NODE-INVOICE-AMOUNT-SKEWNESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-amount-skewness \- FEAT-3421 verb
.SH SYNOPSIS
.B lightning node-invoice-amount-skewness
.SH DESCRIPTION
node-invoice-amount-skewness for lightning CLI (FEAT-3421).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
