.TH "LIGHTNING-CHANNEL-HTLC-DENSITY-STDDEV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-density-stddev \- FEAT-3157 verb
.SH SYNOPSIS
.B lightning channel-htlc-density-stddev
.SH DESCRIPTION
channel-htlc-density-stddev for lightning CLI (FEAT-3157).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
