.TH "LIGHTNING-CHANNEL-REMOTE-HTLC-VALUE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-remote-htlc-value \- FEAT-2360 total value of remote incoming HTLCs
.SH SYNOPSIS
.B lightning channel-remote-htlc-value
.SH DESCRIPTION
channel-remote-htlc-value for lightning CLI (FEAT-2360).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
