.TH "LIGHTNING-CHANNEL_LOCAL_RESERVE_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-local-reserve-total \- FEAT-1646 channel-local-reserve-total
.SH SYNOPSIS
.B lightning channel-local-reserve-total
.SH DESCRIPTION
channel-local-reserve-total for lightning CLI (FEAT-1646).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
