.TH "LIGHTNING-NODE_PAY_OLDEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-oldest \- FEAT-1911 node-pay-oldest
.SH SYNOPSIS
.B lightning node-pay-oldest
.SH DESCRIPTION
node-pay-oldest for lightning CLI (FEAT-1911).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
