.TH "LIGHTNING-CHANNEL_MIN_BALANCE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-min-balance \- FEAT-802 channel-min-balance verb
.SH SYNOPSIS
.B lightning channel-min-balance
.SH DESCRIPTION
channel-min-balance verb for lightning CLI (FEAT-802).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
