.TH "LIGHTNING-PEER-DISCONNECTED-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-disconnected-count \- FEAT-2348 count of disconnected peers
.SH SYNOPSIS
.B lightning peer-disconnected-count
.SH DESCRIPTION
count of disconnected peers for lightning CLI (FEAT-2348).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
