.TH "LIGHTNING-CHANNEL_FUNDING_ADDRESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-funding-address \- FEAT-1759 channel-funding-address
.SH SYNOPSIS
.B lightning channel-funding-address
.SH DESCRIPTION
channel-funding-address for lightning CLI (FEAT-1759).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
