.TH "LIGHTNING-PEER_LIST_BY_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-list-by-capacity \- FEAT-787 peer-list-by-capacity verb
.SH SYNOPSIS
.B lightning peer-list-by-capacity
.SH DESCRIPTION
peer-list-by-capacity verb for lightning CLI (FEAT-787).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
