.TH "LIGHTNING-NODE-LISTFORWARDS-OUT-MSAT-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-out-msat-avg \- FEAT-2571 verb
.SH SYNOPSIS
.B lightning node-listforwards-out-msat-avg
.SH DESCRIPTION
Average out_msat for settled forwards for lightning CLI (FEAT-2571).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
