.TH "LIGHTNING-INVOICE_DESCRIPTION_HASH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-description-hash \- FEAT-1275 invoice-description-hash
.SH SYNOPSIS
.B lightning invoice-description-hash
.SH DESCRIPTION
invoice-description-hash for lightning CLI (FEAT-1275).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
