.TH "LIGHTNING-WALLET_BACKUP_DB" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-backup-db \- FEAT-658 wallet-backup-db verb
.SH SYNOPSIS
.B lightning wallet-backup-db
.SH DESCRIPTION
wallet-backup-db verb for lightning CLI (FEAT-658).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
