.TH "LIGHTNING-CHANNEL-FEE-EARNED-STDDEV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-fee-earned-stddev \- FEAT-2973 channel-fee-earned-stddev
.SH SYNOPSIS
.B lightning channel-fee-earned-stddev
.SH DESCRIPTION
Std dev of fees earned across peer channels for lightning CLI (FEAT-2973).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
