.TH "LIGHTNING-PEER_SCID_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-scid-list \- FEAT-1547 peer-scid-list
.SH SYNOPSIS
.B lightning peer-scid-list
.SH DESCRIPTION
peer-scid-list for lightning CLI (FEAT-1547).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
