.TH "LIGHTNING-NODE_HTLC_MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-htlc-max \- FEAT-681 node-htlc-max verb
.SH SYNOPSIS
.B lightning node-htlc-max
.SH DESCRIPTION
node-htlc-max verb for lightning CLI (FEAT-681).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
