.TH "LIGHTNING-PEER_CONNECTED_PCT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-connected-pct \- FEAT-2338 percentage of connected peers
.SH SYNOPSIS
.B lightning peer-connected-pct
.SH DESCRIPTION
percentage of connected peers verb for lightning CLI (FEAT-2338).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
