.TH "LIGHTNING-NODE-GRAPH-MAX-CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-max-capacity \- FEAT-1949 verb
.SH SYNOPSIS
.B lightning node-graph-max-capacity
.SH DESCRIPTION
node-graph-max-capacity for lightning CLI (FEAT-1949).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
