.TH "LIGHTNING-PEER-HTLC-VALUE-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-htlc-value-min \- FEAT-3056 verb
.SH SYNOPSIS
.B lightning peer-htlc-value-min
.SH DESCRIPTION
peer-htlc-value-min for lightning CLI (FEAT-3056).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
