.TH "LIGHTNING-CHANNEL_RESERVE_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-reserve-msat \- show reserve amounts for a channel
.SH SYNOPSIS
.B lightning channel-reserve-msat
.SH DESCRIPTION
Show reserve amounts for a channel.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
