.TH "LIGHTNING-NODE_GRAPH_NODES_WITH_CHANNELS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-nodes-with-channels \- FEAT-1544 node-graph-nodes-with-channels
.SH SYNOPSIS
.B lightning node-graph-nodes-with-channels
.SH DESCRIPTION
node-graph-nodes-with-channels for lightning CLI (FEAT-1544).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
