.TH "LIGHTNING-PEER_DISCONNECT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-disconnect \- disconnect from a peer
.SH SYNOPSIS
.B lightning peer-disconnect
.I peer_id
.SH DESCRIPTION
Disconnects from the specified peer.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
