.TH "LIGHTNING-WALLET_PIN_VERIFY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-pin-verify \- FEAT-883 wallet-pin-verify
.SH SYNOPSIS
.B lightning wallet-pin-verify
.SH DESCRIPTION
wallet-pin-verify for lightning CLI (FEAT-883).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
