.TH "LIGHTNING-CHANNEL-REMOTE-BALANCE-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-remote-balance-min \- FEAT-2267 channel-remote-balance-min
.SH SYNOPSIS
.B lightning channel-remote-balance-min
.SH DESCRIPTION
channel-remote-balance-min for lightning CLI (FEAT-2267).
.PP
Output: JSON from CLN with the channel having the lowest remote_msat.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
