.TH "LIGHTNING-PEER-NEWEST-INVOICE-PAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-newest-invoice-paid \- FEAT-2413 peer associated with most recently paid invoice
.SH SYNOPSIS
.B lightning peer-newest-invoice-paid
.SH DESCRIPTION
Reports the peer associated with the most recently paid invoice by matching destination to peer (FEAT-2413).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
