.TH "LIGHTNING-PEER_PAYMENT_HISTORY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-payment-history \- FEAT-717 peer-payment-history verb
.SH SYNOPSIS
.B lightning peer-payment-history
.SH DESCRIPTION
peer-payment-history verb for lightning CLI (FEAT-717).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
