.TH "LIGHTNING-CHANNEL_PENDING_CLOSE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-pending-close \- FEAT-1672 channel-pending-close
.SH SYNOPSIS
.B lightning channel-pending-close
.SH DESCRIPTION
channel-pending-close for lightning CLI (FEAT-1672).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
