.TH LIGHTNING-PEER-RECEIVABLE-BALANCE-KURTOSIS-YEARLY 1
.SH NAME
lightning-peer-receivable-balance-kurtosis-yearly \- kurtosis of peer receivable balances over the past year
.SH SYNOPSIS
lightning peer-receivable-balance-kurtosis-yearly
.SH DESCRIPTION
Returns the kurtosis of peer receivable balances over the past year.
.SH SEE ALSO
lightning(1)
