.TH "LIGHTNING-CHANNEL-OPENER-LOCAL-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-opener-local-count \- FEAT-2010 verb
.SH SYNOPSIS
.B lightning channel-opener-local-count
.SH DESCRIPTION
channel-opener-local-count for lightning CLI (FEAT-2010).
.PP
Output: JSON from CLN with count of locally-opened channels.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
