.TH "LIGHTNING-WALLET_AUTO_BACKUP" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-auto-backup \- FEAT-868 wallet-auto-backup
.SH SYNOPSIS
.B lightning wallet-auto-backup
.SH DESCRIPTION
wallet-auto-backup for lightning CLI (FEAT-868).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
