.TH "LIGHTNING-INVOICE_WEBHOOK_SEND" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-webhook-send \- POST an invoice to a webhook URL
.SH SYNOPSIS
.B lightning invoice-webhook-send
.I url bolt11
.SH DESCRIPTION
POSTs a JSON payload with the bolt11 field to the specified URL.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
