.TH "LIGHTNING-PEER_CHANNEL_IDS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-channel-ids \- list channel IDs for a peer
.SH SYNOPSIS
.B lightning peer-channel-ids
.SH DESCRIPTION
List channel IDs for a peer.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
