.TH "LIGHTNING-CHANNEL_HTLC_MAX_REMOTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-max-remote \- FEAT-1432 channel-htlc-max-remote
.SH SYNOPSIS
.B lightning channel-htlc-max-remote
.SH DESCRIPTION
channel-htlc-max-remote for lightning CLI (FEAT-1432).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
