.TH "LIGHTNING-NODE_PAYMENT_PREIMAGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-payment-preimage \- FEAT-944 node-payment-preimage
.SH SYNOPSIS
.B lightning node-payment-preimage
.SH DESCRIPTION
node-payment-preimage for lightning CLI (FEAT-944).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
