.TH "LIGHTNING-CHANNEL_POLICY_UPDATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-policy-update \- FEAT-1082 channel-policy-update
.SH SYNOPSIS
.B lightning channel-policy-update
.SH DESCRIPTION
channel-policy-update for lightning CLI (FEAT-1082).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
