.TH "LIGHTNING-PEER-CHANNEL-BALANCE-RATIO" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-channel-balance-ratio \- FEAT-2308 local/(local+remote) ratio per peer
.SH SYNOPSIS
.B lightning peer-channel-balance-ratio
.SH DESCRIPTION
Local/(local+remote) balance ratio per peer for lightning CLI (FEAT-2308).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
