.TH "LIGHTNING-CHANNEL-FEE-EARNED-MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-fee-earned-max \- FEAT-3419 verb
.SH SYNOPSIS
.B lightning channel-fee-earned-max
.SH DESCRIPTION
channel-fee-earned-max for lightning CLI (FEAT-3419).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
