.TH LIGHTNING-PEER-FEE-PPM-KURTOSIS 1
.SH NAME
lightning-peer-fee-ppm-kurtosis \- compute fee_ppm_kurtosis_peer via listpeers
.SH SYNOPSIS
.B lightning peer-fee-ppm-kurtosis
.SH DESCRIPTION
Queries the node via \fBlightning-cli listpeers\fR and computes fee_ppm_kurtosis_peer.
.SH SEE ALSO
lightning(1)
