.TH "LIGHTNING-NODE_LISTPEERS_COMPACT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpeers-compact \- list peers in compact format
.SH SYNOPSIS
.B lightning node-listpeers-compact
.SH DESCRIPTION
List peers in compact format.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
