.TH "LIGHTNING-NODE-GRAPH-CHANNEL-PEER-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-channel-peer-count \- FEAT-1989 verb
.SH SYNOPSIS
.B lightning node-graph-channel-peer-count
.SH DESCRIPTION
node-graph-channel-peer-count for lightning CLI (FEAT-1989).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
