.TH "LIGHTNING-NODE_LISTCHANNELS_BASE_FEE_SORTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-base-fee-sorted \- FEAT-1854 node-listchannels-base-fee-sorted
.SH SYNOPSIS
.B lightning node-listchannels-base-fee-sorted
.SH DESCRIPTION
node-listchannels-base-fee-sorted for lightning CLI (FEAT-1854).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
