.TH "LIGHTNING-NODE_CHANNEL_AGE_MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-age-max \- FEAT-1039 node-channel-age-max
.SH SYNOPSIS
.B lightning node-channel-age-max
.SH DESCRIPTION
node-channel-age-max for lightning CLI (FEAT-1039).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
