.TH "LIGHTNING-CHANNEL_CLOSE_UNILATERAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-unilateral \- FEAT-690 channel-close-unilateral verb
.SH SYNOPSIS
.B lightning channel-close-unilateral
.SH DESCRIPTION
channel-close-unilateral verb for lightning CLI (FEAT-690).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
