.TH "LIGHTNING-PEER_TOTAL_HTLCS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-total-htlcs \- FEAT-1017 peer-total-htlcs
.SH SYNOPSIS
.B lightning peer-total-htlcs
.SH DESCRIPTION
peer-total-htlcs for lightning CLI (FEAT-1017).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
