.TH "LIGHTNING-WALLET_NOTES_SET_TAG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-set-tag \- FEAT-1563 wallet-notes-set-tag
.SH SYNOPSIS
.B lightning wallet-notes-set-tag
.SH DESCRIPTION
wallet-notes-set-tag for lightning CLI (FEAT-1563).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
