.TH "LIGHTNING-NODE_PAY_FIRST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-first \- FEAT-1494 node-pay-first
.SH SYNOPSIS
.B lightning node-pay-first
.SH DESCRIPTION
node-pay-first for lightning CLI (FEAT-1494).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
