.TH "LIGHTNING-CHANNEL_RECEIVED_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-received-total \- FEAT-702 channel-received-total verb
.SH SYNOPSIS
.B lightning channel-received-total
.SH DESCRIPTION
channel-received-total verb for lightning CLI (FEAT-702).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
