.TH "LIGHTNING-CHANNEL_OPENER_REMOTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-opener-remote \- FEAT-1620 channel-opener-remote
.SH SYNOPSIS
.B lightning channel-opener-remote
.SH DESCRIPTION
channel-opener-remote for lightning CLI (FEAT-1620).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
