.TH "LIGHTNING-WALLET_BACKUP_CREATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-backup-create \- FEAT-1258 wallet-backup-create
.SH SYNOPSIS
.B lightning wallet-backup-create
.SH DESCRIPTION
wallet-backup-create for lightning CLI (FEAT-1258).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
