.TH "LIGHTNING-WALLET_RESTORE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-restore \- FEAT-1023 wallet-restore
.SH SYNOPSIS
.B lightning wallet-restore
.SH DESCRIPTION
wallet-restore for lightning CLI (FEAT-1023).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
