.TH "LIGHTNING-NODE_INFO_SUMMARY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-info-summary \- FEAT-1871 node-info-summary
.SH SYNOPSIS
.B lightning node-info-summary
.SH DESCRIPTION
node-info-summary for lightning CLI (FEAT-1871).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
