.TH "LIGHTNING-NODE_CHANNEL_OPEN_PENDING" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-open-pending \- FEAT-964 node-channel-open-pending
.SH SYNOPSIS
.B lightning node-channel-open-pending
.SH DESCRIPTION
node-channel-open-pending for lightning CLI (FEAT-964).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
