.TH "LIGHTNING-PEER-FEE-BASE-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-fee-base-min \- FEAT-2428 peer's channel with lowest fee_base_msat
.SH SYNOPSIS
.B lightning peer-fee-base-min
.SH DESCRIPTION
Reports the peer with the channel having the lowest fee_base_msat for the lightning CLI (FEAT-2428).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
