.TH "LIGHTNING-WALLET_CREATED_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-created-list \- list wallets with creation timestamps
.SH SYNOPSIS
.B lightning wallet-created-list
.SH DESCRIPTION
List wallets with creation timestamps.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
