.TH LIGHTNING-PEER-BOTH-BALANCES-SKEWNESS 1
.SH NAME
lightning-peer-both-balances-skewness \- skewness of both peer balances
.SH SYNOPSIS
lightning peer-both-balances-skewness
.SH DESCRIPTION
Returns the skewness of both peer balances.
.SH OUTPUT
JSON object with key \fBboth_balances_skewness_peer\fR.
