.TH LIGHTNING-PEER-RECEIVABLE-BALANCE-KURTOSIS-MONTHLY 1
.SH NAME
lightning-peer-receivable-balance-kurtosis-monthly \- kurtosis of peer receivable balances over the past month
.SH SYNOPSIS
lightning peer-receivable-balance-kurtosis-monthly
.SH DESCRIPTION
Returns the kurtosis of receivable balances per peer over the past month.
.SH SEE ALSO
lightning(1)
