.TH "LIGHTNING-CHANNEL_TO_SELF_DELAY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-to-self-delay \- FEAT-1392 channel-to-self-delay
.SH SYNOPSIS
.B lightning channel-to-self-delay
.SH DESCRIPTION
channel-to-self-delay for lightning CLI (FEAT-1392).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
