.TH "LIGHTNING-WALLET_NOTES_RECENT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-recent \- FEAT-1748 wallet-notes-recent
.SH SYNOPSIS
.B lightning wallet-notes-recent
.SH DESCRIPTION
wallet-notes-recent for lightning CLI (FEAT-1748).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
