.TH "LIGHTNING-INVOICE_LIST_RECENT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-recent \- list most recent invoices
.SH SYNOPSIS
.B lightning invoice-list-recent
.SH DESCRIPTION
List most recent invoices.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
