.TH "LIGHTNING-NODE_LISTCHANNELS_COMPACT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-compact \- list gossip channels in compact format
.SH SYNOPSIS
.B lightning node-listchannels-compact
.SH DESCRIPTION
List gossip channels in compact format.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
