.TH "LIGHTNING-NODE-INVOICE-PAID-AMOUNT-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-paid-amount-range \- FEAT-3138 verb
.SH SYNOPSIS
.B lightning node-invoice-paid-amount-range
.SH DESCRIPTION
node-invoice-paid-amount-range for lightning CLI (FEAT-3138).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
