.TH "LIGHTNING-CHANNEL-LOCAL-BALANCE-SKEWNESS-WEEKLY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-local-balance-skewness-weekly \- FEAT-3500 verb
.SH SYNOPSIS
.B lightning channel-local-balance-skewness-weekly
.SH DESCRIPTION
channel-local-balance-skewness-weekly for lightning CLI (FEAT-3500).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
