.TH "LIGHTNING-CHANNEL-HTLC-TIMEOUT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-timeout \- FEAT-2052 Show HTLC expiry and timeout info for peer channels
.SH SYNOPSIS
.B lightning channel-htlc-timeout
.SH DESCRIPTION
Show HTLC expiry and timeout info for peer channels (FEAT-2052).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
