.TH "LIGHTNING-CHANNEL_SPLICING_IN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-splicing-in \- initiate a splice-in to add capacity
.SH SYNOPSIS
.B lightning channel-splicing-in
.I channel_id amount_sat
.SH DESCRIPTION
Initiates a splice-in operation to add funds to a channel.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
