.TH "LIGHTNING-WALLET-HISTORY-EXPORT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-history-export \- export ledger history as JSON or CSV
.SH SYNOPSIS
.B lightning wallet-history-export
.I wallet_name
.RB [ --format
.IR csv | json ]
.SH DESCRIPTION
Exports the wallet ledger as JSON (default) or CSV.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-wallet-export-csv (1),
.BR lightning-wallet-transaction-log (1)
