.TH "LIGHTNING-NODE_INVOICE_PREIMAGE_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-preimage-list \- FEAT-1421 node-invoice-preimage-list
.SH SYNOPSIS
.B lightning node-invoice-preimage-list
.SH DESCRIPTION
node-invoice-preimage-list for lightning CLI (FEAT-1421).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
