.TH "LIGHTNING-PEER-BALANCE-RATIO-KURTOSIS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-balance-ratio-kurtosis \- FEAT-3483 verb
.SH SYNOPSIS
.B lightning peer-balance-ratio-kurtosis
.SH DESCRIPTION
peer-balance-ratio-kurtosis for lightning CLI (FEAT-3483).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
