.TH "LIGHTNING-NODE-LISTFORWARDS-FAIL-RATE-WEEK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-fail-rate-week \- FEAT-3035 verb
.SH SYNOPSIS
.B lightning node-listforwards-fail-rate-week
.SH DESCRIPTION
node-listforwards-fail-rate-week for lightning CLI (FEAT-3035).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
