.TH "LIGHTNING-NODE_PAY_BOLT11_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-bolt11-list \- FEAT-1214 node-pay-bolt11-list
.SH SYNOPSIS
.B lightning node-pay-bolt11-list
.SH DESCRIPTION
node-pay-bolt11-list for lightning CLI (FEAT-1214).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
