.TH "LIGHTNING-PEER_REACHABILITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-reachability \- FEAT-767 peer-reachability verb
.SH SYNOPSIS
.B lightning peer-reachability
.SH DESCRIPTION
peer-reachability verb for lightning CLI (FEAT-767).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
