.TH "LIGHTNING-CHANNEL_CLOSINGD_SIGEXCHANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-closingd-sigexchange \- FEAT-1662 channel-closingd-sigexchange
.SH SYNOPSIS
.B lightning channel-closingd-sigexchange
.SH DESCRIPTION
channel-closingd-sigexchange for lightning CLI (FEAT-1662).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
