.TH "LIGHTNING-NODE-LISTPAYS-COMPLETE-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-complete-count \- FEAT-1931 node-listpays-complete-count
.SH SYNOPSIS
.B lightning node-listpays-complete-count
.SH DESCRIPTION
node-listpays-complete-count for lightning CLI (FEAT-1931).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
