.TH "LIGHTNING-NODE_MAX_HTLC" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-max-htlc \- FEAT-701 node-max-htlc verb
.SH SYNOPSIS
.B lightning node-max-htlc
.SH DESCRIPTION
node-max-htlc verb for lightning CLI (FEAT-701).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
