.TH "LIGHTNING-PEER-HTLC-COUNT-MIN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-htlc-count-min \- FEAT-3036 verb
.SH SYNOPSIS
.B lightning peer-htlc-count-min
.SH DESCRIPTION
peer-htlc-count-min for lightning CLI (FEAT-3036).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
