.TH "LIGHTNING-CHANNEL_FLAGS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-flags \- FEAT-730 channel-flags verb
.SH SYNOPSIS
.B lightning channel-flags
.SH DESCRIPTION
channel-flags verb for lightning CLI (FEAT-730).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
