.TH "LIGHTNING-CHANNEL_FEERATE_PER_KBYTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-feerate-per-kbyte \- FEAT-1260 channel-feerate-per-kbyte
.SH SYNOPSIS
.B lightning channel-feerate-per-kbyte
.SH DESCRIPTION
channel-feerate-per-kbyte for lightning CLI (FEAT-1260).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
