.TH "LIGHTNING-WALLET_NOTES_UNIQUE_TAGS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-unique-tags \- FEAT-1708 wallet-notes-unique-tags
.SH SYNOPSIS
.B lightning wallet-notes-unique-tags
.SH DESCRIPTION
wallet-notes-unique-tags for lightning CLI (FEAT-1708).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
