.TH "LIGHTNING-WALLET_PASSPHRASE_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-passphrase-set \- FEAT-1018 wallet-passphrase-set
.SH SYNOPSIS
.B lightning wallet-passphrase-set
.SH DESCRIPTION
wallet-passphrase-set for lightning CLI (FEAT-1018).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
