.TH "LIGHTNING-WALLET_NOTES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes \- show notes for a wallet
.SH SYNOPSIS
.B lightning wallet-notes

.SH DESCRIPTION
Returns the notes.txt content for the named wallet, if present.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
