.TH "LIGHTNING-NODE-INVOICE-OLDEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-oldest \- FEAT-2017 node-invoice-oldest
.SH SYNOPSIS
.B lightning node-invoice-oldest
.SH DESCRIPTION
node-invoice-oldest for lightning CLI (FEAT-2017).
.PP
Output: JSON from CLN with the oldest paid invoice.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
