.TH "LIGHTNING-NODE_LISTPAYS_BY_DESTINATION" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-by-destination \- FEAT-1361 node-listpays-by-destination
.SH SYNOPSIS
.B lightning node-listpays-by-destination
.SH DESCRIPTION
node-listpays-by-destination for lightning CLI (FEAT-1361).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
