.TH "LIGHTNING-CHANNEL_PEER_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-peer-capacity \- FEAT-852 channel-peer-capacity
.SH SYNOPSIS
.B lightning channel-peer-capacity
.SH DESCRIPTION
channel-peer-capacity for lightning CLI (FEAT-852).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
