.TH "LIGHTNING-NODE_LISTPEERS_BY_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpeers-by-capacity \- FEAT-1654 node-listpeers-by-capacity
.SH SYNOPSIS
.B lightning node-listpeers-by-capacity
.SH DESCRIPTION
node-listpeers-by-capacity for lightning CLI (FEAT-1654).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
