.TH "LIGHTNING-PEER_SORT_BY_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-sort-by-capacity \- rank peers by total channel capacity
.SH SYNOPSIS
.B lightning peer-sort-by-capacity
.SH DESCRIPTION
Rank peers by total channel capacity.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
