.TH "LIGHTNING-NODE-INVOICE-PAID-AMOUNT-MEDIAN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-paid-amount-median \- FEAT-3142 verb
.SH SYNOPSIS
.B lightning node-invoice-paid-amount-median
.SH DESCRIPTION
node-invoice-paid-amount-median for lightning CLI (FEAT-3142).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
