.TH "LIGHTNING-CHANNEL_SET_PUBLIC" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-set-public \- set a channel to public (announced)
.SH SYNOPSIS
.B lightning channel-set-public
.I channel_id
.SH DESCRIPTION
Sets the channel to announced (public) mode via setchannel.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
