.TH "LIGHTNING-INVOICE_CREATED_INDEX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-created-index \- FEAT-1435 invoice-created-index
.SH SYNOPSIS
.B lightning invoice-created-index
.SH DESCRIPTION
invoice-created-index for lightning CLI (FEAT-1435).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
