.TH "LIGHTNING-NODE_PAYMENT_LIMITS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-payment-limits \- show min and max payment size limits
.SH SYNOPSIS
.B lightning node-payment-limits

.SH DESCRIPTION
Returns min and max payment size from CLN configuration.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
