.TH "LIGHTNING-INVOICE_QR_DATA" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-qr-data \- generate QR-friendly URI for a BOLT11 invoice
.SH SYNOPSIS
.B lightning invoice-qr-data
.SH DESCRIPTION
Generate QR-friendly URI for a BOLT11 invoice.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
