.TH "LIGHTNING-CHANNEL-FUNDING-TXID-LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-funding-txid-list \- FEAT-2250 list of funding_txid for all channels
.SH SYNOPSIS
.B lightning channel-funding-txid-list
.SH DESCRIPTION
List of funding_txid for all channels for lightning CLI (FEAT-2250).
.PP
Output: JSON from CLN with key funding_txids.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
