.TH "LIGHTNING-NODE_PAY_AVG_FEE_PPM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-avg-fee-ppm \- FEAT-1589 node-pay-avg-fee-ppm
.SH SYNOPSIS
.B lightning node-pay-avg-fee-ppm
.SH DESCRIPTION
node-pay-avg-fee-ppm for lightning CLI (FEAT-1589).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
