.TH "LIGHTNING-CHANNEL_FUNDING_TXID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-funding-txid \- FEAT-1466 channel-funding-txid
.SH SYNOPSIS
.B lightning channel-funding-txid
.SH DESCRIPTION
channel-funding-txid for lightning CLI (FEAT-1466).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
