.TH "LIGHTNING-CHANNEL-FEE-EARNED-KURTOSIS-WEEKLY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-fee-earned-kurtosis-weekly \- FEAT-3587 verb
.SH SYNOPSIS
.B lightning channel-fee-earned-kurtosis-weekly
.SH DESCRIPTION
channel-fee-earned-kurtosis-weekly for lightning CLI (FEAT-3587).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
