.TH "LIGHTNING-INVOICE_BOLT11_MIN_FINAL_CLTV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-bolt11-min-final-cltv \- FEAT-1405 invoice-bolt11-min-final-cltv
.SH SYNOPSIS
.B lightning invoice-bolt11-min-final-cltv
.SH DESCRIPTION
invoice-bolt11-min-final-cltv for lightning CLI (FEAT-1405).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
