.TH "LIGHTNING-PEER-FEE-EARNED-STDDEV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-fee-earned-stddev \- FEAT-3079 verb
.SH SYNOPSIS
.B lightning peer-fee-earned-stddev
.SH DESCRIPTION
peer-fee-earned-stddev for lightning CLI (FEAT-3079).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
