.TH "LIGHTNING-NODE_LISTFORWARDS_SUCCESS_RATE_WEEK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-success-rate-week \- FEAT-3016 verb
.SH SYNOPSIS
.B lightning node-listforwards-success-rate-week
.SH DESCRIPTION
node-listforwards-success-rate-week for lightning CLI (FEAT-3016).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
