.TH "LIGHTNING-PEER-FEE-PPM-KURTOSIS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-fee-ppm-kurtosis \- FEAT-3223 verb
.SH SYNOPSIS
.B lightning peer-fee-ppm-kurtosis
.SH DESCRIPTION
peer-fee-ppm-kurtosis for lightning CLI (FEAT-3223).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
