.TH "LIGHTNING-PEER_NEWEST_PAY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-newest-pay \- FEAT-2216 most recent complete pay to each peer
.SH SYNOPSIS
.B lightning peer-newest-pay
.SH DESCRIPTION
most recent complete pay to each peer for the lightning CLI (FEAT-2216).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
