.TH "LIGHTNING-CHANNEL_OPENER" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-opener \- FEAT-1330 channel-opener
.SH SYNOPSIS
.B lightning channel-opener
.SH DESCRIPTION
channel-opener for lightning CLI (FEAT-1330).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
