.TH "LIGHTNING-NODE-ADDRESS-LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-address-list \- show node network addresses
.SH SYNOPSIS
.B lightning node-address-list
.SH DESCRIPTION
Returns the node's announced addresses and local bindings from
.BR getinfo .
.PP
Output:
.nf
{"node_id":..., "addresses":[...], "binding":[...]}
.fi
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-node-info (1),
.BR lightning-node-network-info (1)
