.TH "LIGHTNING-CHANNEL_PEER_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-peer-list \- FEAT-2102 verb
.SH SYNOPSIS
.B lightning channel-peer-list
.SH DESCRIPTION
unique peer list with channel count for lightning CLI (FEAT-2102).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
