.TH "LIGHTNING-NODE_PEER_TIMEOUT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-peer-timeout \- FEAT-821 node-peer-timeout verb
.SH SYNOPSIS
.B lightning node-peer-timeout
.SH DESCRIPTION
node-peer-timeout verb for lightning CLI (FEAT-821).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
