.TH "LIGHTNING-CHANNEL_CLTV_DELTA" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-cltv-delta \- FEAT-856 channel-cltv-delta
.SH SYNOPSIS
.B lightning channel-cltv-delta
.SH DESCRIPTION
channel-cltv-delta for lightning CLI (FEAT-856).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
