.TH "LIGHTNING-NODE_NETWORK_INFO" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-network-info \- show node network and version info
.SH SYNOPSIS
.B lightning node-network-info

.SH DESCRIPTION
Returns network name, CLN version, block height, node ID, and peer count.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
