.TH "LIGHTNING-CHANNEL_CAPACITY_CHECK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-capacity-check \- list channels below a minimum capacity
.SH SYNOPSIS
.B lightning channel-capacity-check
.I min_sat
.SH DESCRIPTION
Returns channels whose total capacity is below the specified minimum.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
