.TH "LIGHTNING-CHANNEL-BOTH-BALANCES-TOP10" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-both-balances-top10 \- FEAT-3380 verb
.SH SYNOPSIS
.B lightning channel-both-balances-top10
.SH DESCRIPTION
channel-both-balances-top10 for lightning CLI (FEAT-3380).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
