.TH "LIGHTNING-CHANNEL_OPEN_RATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-rate \- show channel open rate
.SH SYNOPSIS
.B lightning channel-open-rate

.SH DESCRIPTION
Returns total channels and how many were opened in the last 7 days.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
