.TH "LIGHTNING-PEER_LIST_UNCONNECTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-list-unconnected \- FEAT-1387 peer-list-unconnected
.SH SYNOPSIS
.B lightning peer-list-unconnected
.SH DESCRIPTION
peer-list-unconnected for lightning CLI (FEAT-1387).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
