.TH "LIGHTNING-PEER-RECEIVABLE-BALANCE-SKEWNESS" 1 "May 2026" "lightning" "User Commands"
.SH NAME
lightning-peer-receivable-balance-skewness \- FEAT-3529 peer-receivable-balance-skewness
.SH SYNOPSIS
.B lightning peer-receivable-balance-skewness
.SH DESCRIPTION
Skewness of receivable balance across peers (FEAT-3529).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
