.TH "LIGHTNING-CHANNEL_OUR_CLTV_DELTA" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-our-cltv-delta \- FEAT-1460 channel-our-cltv-delta
.SH SYNOPSIS
.B lightning channel-our-cltv-delta
.SH DESCRIPTION
channel-our-cltv-delta for lightning CLI (FEAT-1460).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
