.TH "LIGHTNING-CHANNEL-THEIR-RESERVE-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-their-reserve-range \- FEAT-3265 verb
.SH SYNOPSIS
.B lightning channel-their-reserve-range
.SH DESCRIPTION
channel-their-reserve-range for lightning CLI (FEAT-3265).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
