.TH "LIGHTNING-CHANNEL_LAST_UPDATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-last-update \- FEAT-930 channel-last-update
.SH SYNOPSIS
.B lightning channel-last-update
.SH DESCRIPTION
channel-last-update for lightning CLI (FEAT-930).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
