.TH "LIGHTNING-CHANNEL_OPEN_ALIAS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-alias \- FEAT-1240 channel-open-alias
.SH SYNOPSIS
.B lightning channel-open-alias
.SH DESCRIPTION
channel-open-alias for lightning CLI (FEAT-1240).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
