.TH "LIGHTNING-NODE_LISTPEERS_PING" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpeers-ping \- FEAT-1364 node-listpeers-ping
.SH SYNOPSIS
.B lightning node-listpeers-ping
.SH DESCRIPTION
node-listpeers-ping for lightning CLI (FEAT-1364).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
