.TH "LIGHTNING-CHANNEL_LOCAL_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-local-msat \- FEAT-886 channel-local-msat
.SH SYNOPSIS
.B lightning channel-local-msat
.SH DESCRIPTION
channel-local-msat for lightning CLI (FEAT-886).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
