.TH "LIGHTNING-WALLET_NOTES_FIRST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-first \- FEAT-1903 wallet-notes-first
.SH SYNOPSIS
.B lightning wallet-notes-first
.SH DESCRIPTION
wallet-notes-first for lightning CLI (FEAT-1903).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
