.TH "LIGHTNING-PEER_GOSSIP_QUERIES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-gossip-queries \- FEAT-1427 peer-gossip-queries
.SH SYNOPSIS
.B lightning peer-gossip-queries
.SH DESCRIPTION
peer-gossip-queries for lightning CLI (FEAT-1427).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
