.TH "LIGHTNING-INVOICE_AMOUNT_SAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-amount-sat \- FEAT-1425 invoice-amount-sat
.SH SYNOPSIS
.B lightning invoice-amount-sat
.SH DESCRIPTION
invoice-amount-sat for lightning CLI (FEAT-1425).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
