.TH "LIGHTNING-NODE_PEER_COUNT_CONNECTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-peer-count-connected \- count connected and disconnected peers
.SH SYNOPSIS
.B lightning node-peer-count-connected
.SH DESCRIPTION
Count connected and disconnected peers.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
