.TH "LIGHTNING-NODE-LISTPAYS-PENDING" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-pending \- FEAT-1921 node-listpays-pending
.SH SYNOPSIS
.B lightning node-listpays-pending
.SH DESCRIPTION
node-listpays-pending for lightning CLI (FEAT-1921).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
