.TH "LIGHTNING-NODE-GRAPH-FEE-PPM-MEDIAN" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-fee-ppm-median \- FEAT-2194 verb
.SH SYNOPSIS
.B lightning node-graph-fee-ppm-median
.SH DESCRIPTION
approximate median fee_per_millionth from graph for lightning CLI (FEAT-2194).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
