.TH "LIGHTNING-NODE_LIST_CLOSED_CHANNELS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-list-closed-channels \- FEAT-884 node-list-closed-channels
.SH SYNOPSIS
.B lightning node-list-closed-channels
.SH DESCRIPTION
node-list-closed-channels for lightning CLI (FEAT-884).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
