.TH "LIGHTNING-CHANNEL-CLOSE-COUNT-MONTH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-count-month \- FEAT-3087 verb
.SH SYNOPSIS
.B lightning channel-close-count-month
.SH DESCRIPTION
channel-close-count-month for lightning CLI (FEAT-3087).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
