.TH "LIGHTNING-WALLET_NOTES_COPY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-copy \- FEAT-1833 wallet-notes-copy
.SH SYNOPSIS
.B lightning wallet-notes-copy
.SH DESCRIPTION
wallet-notes-copy for lightning CLI (FEAT-1833).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
