.TH "LIGHTNING-WALLET_NOTES_LAST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-last \- FEAT-1908 wallet-notes-last
.SH SYNOPSIS
.B lightning wallet-notes-last
.SH DESCRIPTION
wallet-notes-last for lightning CLI (FEAT-1908).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
