.TH "LIGHTNING-PEER_LAST_CHANNEL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-last-channel \- FEAT-847 peer-last-channel
.SH SYNOPSIS
.B lightning peer-last-channel
.SH DESCRIPTION
peer-last-channel for lightning CLI (FEAT-847).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
