.TH "LIGHTNING-INVOICE_LIST_BY_HASH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-list-by-hash \- FEAT-1145 invoice-list-by-hash
.SH SYNOPSIS
.B lightning invoice-list-by-hash
.SH DESCRIPTION
invoice-list-by-hash for lightning CLI (FEAT-1145).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
