.TH "LIGHTNING-NODE_PAY_30D_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-30d-total \- FEAT-2336 total amount_sent_msat for complete pays in last 30 days
.SH SYNOPSIS
.B lightning node-pay-30d-total
.SH DESCRIPTION
total amount_sent_msat for complete pays in last 30 days verb for lightning CLI (FEAT-2336).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
