.TH "LIGHTNING-NODE_TOTAL_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-total-capacity \- FEAT-761 node-total-capacity verb
.SH SYNOPSIS
.B lightning node-total-capacity
.SH DESCRIPTION
node-total-capacity verb for lightning CLI (FEAT-761).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
