.TH "LIGHTNING-WALLET_TRANSACTION_LOG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-transaction-log \- FEAT-758 wallet-transaction-log verb
.SH SYNOPSIS
.B lightning wallet-transaction-log
.SH DESCRIPTION
wallet-transaction-log verb for lightning CLI (FEAT-758).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
