.TH "LIGHTNING-PEER_TOTAL_SENT_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-total-sent-msat \- FEAT-1647 peer-total-sent-msat
.SH SYNOPSIS
.B lightning peer-total-sent-msat
.SH DESCRIPTION
peer-total-sent-msat for lightning CLI (FEAT-1647).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
