.TH "LIGHTNING-WALLET_NOTES_RESTORE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-restore \- FEAT-1733 wallet-notes-restore
.SH SYNOPSIS
.B lightning wallet-notes-restore
.SH DESCRIPTION
wallet-notes-restore for lightning CLI (FEAT-1733).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
