.TH "LIGHTNING-WALLET_PASSPHRASE_CHECK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-passphrase-check \- FEAT-858 wallet-passphrase-check
.SH SYNOPSIS
.B lightning wallet-passphrase-check
.SH DESCRIPTION
wallet-passphrase-check for lightning CLI (FEAT-858).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
