.TH "LIGHTNING-NODE_FUNDING_TXIDS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-funding-txids \- list funding transaction IDs for all channels
.SH SYNOPSIS
.B lightning node-funding-txids

.SH DESCRIPTION
Returns funding transaction IDs and output numbers for all peer channels.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
