.TH "LIGHTNING-CHANNEL_CLOSE_FORCE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-force \- FEAT-710 channel-close-force verb
.SH SYNOPSIS
.B lightning channel-close-force
.SH DESCRIPTION
channel-close-force verb for lightning CLI (FEAT-710).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
