.TH "LIGHTNING-CHANNEL_OUR_BASE_FEE_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-our-base-fee-total \- FEAT-1706 channel-our-base-fee-total
.SH SYNOPSIS
.B lightning channel-our-base-fee-total
.SH DESCRIPTION
channel-our-base-fee-total for lightning CLI (FEAT-1706).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
