.TH "LIGHTNING-PEER_NUM_CHANNELS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-num-channels \- FEAT-1067 peer-num-channels
.SH SYNOPSIS
.B lightning peer-num-channels
.SH DESCRIPTION
peer-num-channels for lightning CLI (FEAT-1067).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
