.TH "LIGHTNING-CHANNEL_LOCAL_PPM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-local-ppm \- FEAT-1546 channel-local-ppm
.SH SYNOPSIS
.B lightning channel-local-ppm
.SH DESCRIPTION
channel-local-ppm for lightning CLI (FEAT-1546).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
