.TH "LIGHTNING-CHANNEL_PEER_MSATOSHI" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-peer-msatoshi \- FEAT-966 channel-peer-msatoshi
.SH SYNOPSIS
.B lightning channel-peer-msatoshi
.SH DESCRIPTION
channel-peer-msatoshi for lightning CLI (FEAT-966).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
