.TH "LIGHTNING-NODE_LISTCHANNELS_ZERO_RESERVE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-zero-reserve \- FEAT-1409 node-listchannels-zero-reserve
.SH SYNOPSIS
.B lightning node-listchannels-zero-reserve
.SH DESCRIPTION
node-listchannels-zero-reserve for lightning CLI (FEAT-1409).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
