.TH "LIGHTNING-CHANNEL_UNILATERAL_CLOSE_INFO" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-unilateral-close-info \- FEAT-1766 channel-unilateral-close-info
.SH SYNOPSIS
.B lightning channel-unilateral-close-info
.SH DESCRIPTION
channel-unilateral-close-info for lightning CLI (FEAT-1766).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
