.TH "LIGHTNING-NODE_CHANNEL_SPENDABLE_MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-spendable-max \- FEAT-1269 node-channel-spendable-max
.SH SYNOPSIS
.B lightning node-channel-spendable-max
.SH DESCRIPTION
node-channel-spendable-max for lightning CLI (FEAT-1269).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
