.TH "LIGHTNING-NODE_GRAPH_ACTIVE_CHANNELS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-active-channels \- FEAT-1514 node-graph-active-channels
.SH SYNOPSIS
.B lightning node-graph-active-channels
.SH DESCRIPTION
node-graph-active-channels for lightning CLI (FEAT-1514).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
