.TH "LIGHTNING-CHANNEL_FEE_RATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-fee-rate \- FEAT-1066 channel-fee-rate
.SH SYNOPSIS
.B lightning channel-fee-rate
.SH DESCRIPTION
channel-fee-rate for lightning CLI (FEAT-1066).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
