.TH "LIGHTNING-NODE-INVOICE-BOLT12-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-bolt12-count \- FEAT-2344 count of invoices with local_offer_id set
.SH SYNOPSIS
.B lightning node-invoice-bolt12-count
.SH DESCRIPTION
count of invoices with local_offer_id set for lightning CLI (FEAT-2344).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
