.TH "LIGHTNING-CHANNEL_BALANCE_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-balance-total \- FEAT-1176 channel-balance-total
.SH SYNOPSIS
.B lightning channel-balance-total
.SH DESCRIPTION
channel-balance-total for lightning CLI (FEAT-1176).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
