.TH "LIGHTNING-CHANNEL_MAX_HTLC" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-max-htlc \- FEAT-1006 channel-max-htlc
.SH SYNOPSIS
.B lightning channel-max-htlc
.SH DESCRIPTION
channel-max-htlc for lightning CLI (FEAT-1006).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
