.TH "LIGHTNING-NODE_HTLC_IN_FLIGHT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-htlc-in-flight \- FEAT-849 node-htlc-in-flight
.SH SYNOPSIS
.B lightning node-htlc-in-flight
.SH DESCRIPTION
node-htlc-in-flight for lightning CLI (FEAT-849).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
