.TH "LIGHTNING-NODE_GOSSIP_MAP" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-gossip-map \- show summary of the gossip node map
.SH SYNOPSIS
.B lightning node-gossip-map
.SH DESCRIPTION
Show summary of the gossip node map.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
