.TH "LIGHTNING-CHANNEL_HTLC_MAX_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-max-msat \- FEAT-1562 channel-htlc-max-msat
.SH SYNOPSIS
.B lightning channel-htlc-max-msat
.SH DESCRIPTION
channel-htlc-max-msat for lightning CLI (FEAT-1562).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
