.TH "LIGHTNING-NODE_EMERGENCY_RECOVER" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-emergency-recover \- FEAT-689 node-emergency-recover verb
.SH SYNOPSIS
.B lightning node-emergency-recover
.SH DESCRIPTION
node-emergency-recover verb for lightning CLI (FEAT-689).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
