.TH "LIGHTNING-PEER_SEND_CUSTOM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-send-custom \- FEAT-937 peer-send-custom
.SH SYNOPSIS
.B lightning peer-send-custom
.SH DESCRIPTION
peer-send-custom for lightning CLI (FEAT-937).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
