.TH "LIGHTNING-NODE-GRAPH-TOP-CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-top-capacity \- FEAT-2054 Show top 5 channels by capacity from the network graph
.SH SYNOPSIS
.B lightning node-graph-top-capacity
.SH DESCRIPTION
Show top 5 channels by capacity from the network graph (FEAT-2054).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
