.TH "LIGHTNING-NODE_INVOICES_TOTAL_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoices-total-msat \- FEAT-731 node-invoices-total-msat verb
.SH SYNOPSIS
.B lightning node-invoices-total-msat
.SH DESCRIPTION
node-invoices-total-msat verb for lightning CLI (FEAT-731).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
