.TH "LIGHTNING-NODE-INVOICE-PAID-COUNT-YEARLY" 1 "May 2026" "lightning" "User Commands"
.SH NAME
lightning-node-invoice-paid-count-yearly \- FEAT-3527 node-invoice-paid-count-yearly
.SH SYNOPSIS
.B lightning node-invoice-paid-count-yearly
.SH DESCRIPTION
Count of invoices paid this year for lightning CLI (FEAT-3527).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
