.TH "LIGHTNING-WALLET_BACKUP_LIST_ALL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-backup-list-all \- FEAT-1283 wallet-backup-list-all
.SH SYNOPSIS
.B lightning wallet-backup-list-all
.SH DESCRIPTION
wallet-backup-list-all for lightning CLI (FEAT-1283).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
