.TH "LIGHTNING-INVOICE_AMOUNT_PAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-amount-paid \- FEAT-855 invoice-amount-paid
.SH SYNOPSIS
.B lightning invoice-amount-paid
.SH DESCRIPTION
invoice-amount-paid for lightning CLI (FEAT-855).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
