.TH "LIGHTNING-CHANNEL_MAX_RECEIVABLE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-max-receivable \- FEAT-1180 channel-max-receivable
.SH SYNOPSIS
.B lightning channel-max-receivable
.SH DESCRIPTION
channel-max-receivable for lightning CLI (FEAT-1180).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
