.TH "LIGHTNING-NODE_CHANNEL_CAPACITY_AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channel-capacity-avg \- FEAT-1009 node-channel-capacity-avg
.SH SYNOPSIS
.B lightning node-channel-capacity-avg
.SH DESCRIPTION
node-channel-capacity-avg for lightning CLI (FEAT-1009).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
