.TH "LIGHTNING-NODE-INVOICE-UNPAID-COUNT-YEARLY" 1 "May 2026" "lightning" "User Commands"
.SH NAME
lightning-node-invoice-unpaid-count-yearly \- FEAT-3568 node-invoice-unpaid-count-yearly
.SH SYNOPSIS
.B lightning node-invoice-unpaid-count-yearly
.SH DESCRIPTION
Yearly count of unpaid invoices (FEAT-3568).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
