.TH "LIGHTNING-WALLET_META_ALL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-meta-all \- FEAT-1108 wallet-meta-all
.SH SYNOPSIS
.B lightning wallet-meta-all
.SH DESCRIPTION
wallet-meta-all for lightning CLI (FEAT-1108).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
