.TH "LIGHTNING-PEER-HTLC-MAX-MSAT-MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-htlc-max-msat-max \- FEAT-3310 verb
.SH SYNOPSIS
.B lightning peer-htlc-max-msat-max
.SH DESCRIPTION
peer-htlc-max-msat-max for lightning CLI (FEAT-3310).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
