.TH "LIGHTNING-NODE_LISTCHANNELS_BY_DIRECTION" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-by-direction \- FEAT-1704 node-listchannels-by-direction
.SH SYNOPSIS
.B lightning node-listchannels-by-direction
.SH DESCRIPTION
node-listchannels-by-direction for lightning CLI (FEAT-1704).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
