.TH "LIGHTNING-INVOICE_DELETE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-delete \- FEAT-935 invoice-delete
.SH SYNOPSIS
.B lightning invoice-delete
.SH DESCRIPTION
invoice-delete for lightning CLI (FEAT-935).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
