.TH "LIGHTNING-WALLET_BACKUP_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-backup-list \- FEAT-998 wallet-backup-list
.SH SYNOPSIS
.B lightning wallet-backup-list
.SH DESCRIPTION
wallet-backup-list for lightning CLI (FEAT-998).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
