.TH "LIGHTNING-NODE_GRAPH_CHANNELS_PRIVATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-channels-private \- FEAT-1384 node-graph-channels-private
.SH SYNOPSIS
.B lightning node-graph-channels-private
.SH DESCRIPTION
node-graph-channels-private for lightning CLI (FEAT-1384).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
