.TH "LIGHTNING-PEER-SPENDABLE-KURTOSIS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-spendable-kurtosis \- FEAT-3466 verb
.SH SYNOPSIS
.B lightning peer-spendable-kurtosis
.SH DESCRIPTION
peer-spendable-kurtosis for lightning CLI (FEAT-3466).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
