.TH "LIGHTNING-NODE_PAY_FEES_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-fees-total \- FEAT-1481 node-pay-fees-total
.SH SYNOPSIS
.B lightning node-pay-fees-total
.SH DESCRIPTION
node-pay-fees-total for lightning CLI (FEAT-1481).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
