.TH "LIGHTNING-CHANNEL_MIN_DEPTH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-min-depth \- FEAT-1540 channel-min-depth
.SH SYNOPSIS
.B lightning channel-min-depth
.SH DESCRIPTION
channel-min-depth for lightning CLI (FEAT-1540).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
