.TH "LIGHTNING-NODE-INVOICE-COUNT-DAILY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-count-daily \- FEAT-3355 verb
.SH SYNOPSIS
.B lightning node-invoice-count-daily
.SH DESCRIPTION
node-invoice-count-daily for lightning CLI (FEAT-3355).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
