.TH "LIGHTNING-PEER-FEE-REVENUE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-fee-revenue \- FEAT-2016 peer-fee-revenue
.SH SYNOPSIS
.B lightning peer-fee-revenue
.SH DESCRIPTION
peer-fee-revenue for lightning CLI (FEAT-2016).
.PP
Output: JSON from CLN with fee revenue in msat grouped by incoming channel.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
