.TH "LIGHTNING-PEER_DISCONNECT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-disconnect \- FEAT-1057 peer-disconnect
.SH SYNOPSIS
.B lightning peer-disconnect
.SH DESCRIPTION
peer-disconnect for lightning CLI (FEAT-1057).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
