.TH "LIGHTNING-NODE_LISTFORWARDS_AVG_FEE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-avg-fee \- FEAT-1829 node-listforwards-avg-fee
.SH SYNOPSIS
.B lightning node-listforwards-avg-fee
.SH DESCRIPTION
node-listforwards-avg-fee for lightning CLI (FEAT-1829).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
