.TH "LIGHTNING-INVOICE_LABEL_LIST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-label-list \- FEAT-785 invoice-label-list verb
.SH SYNOPSIS
.B lightning invoice-label-list
.SH DESCRIPTION
invoice-label-list verb for lightning CLI (FEAT-785).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
