.TH "LIGHTNING-CHANNEL_OPEN_PROGRESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-progress \- FEAT-752 channel-open-progress verb
.SH SYNOPSIS
.B lightning channel-open-progress
.SH DESCRIPTION
channel-open-progress verb for lightning CLI (FEAT-752).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
