.TH "LIGHTNING-CHANNEL-FEE-PPM-SKEWNESS-WEEKLY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-fee-ppm-skewness-weekly \- FEAT-3245 verb
.SH SYNOPSIS
.B lightning channel-fee-ppm-skewness-weekly
.SH DESCRIPTION
channel-fee-ppm-skewness-weekly for lightning CLI (FEAT-3245).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
