.TH "LIGHTNING-CHANNEL-HTLC-MIN-MSAT-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-min-msat-avg \- FEAT-3285 verb
.SH SYNOPSIS
.B lightning channel-htlc-min-msat-avg
.SH DESCRIPTION
channel-htlc-min-msat-avg for lightning CLI (FEAT-3285).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
