.TH "LIGHTNING-WALLET_NOTES_TAG_RENAME" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-tag-rename \- FEAT-1803 wallet-notes-tag-rename
.SH SYNOPSIS
.B lightning wallet-notes-tag-rename
.SH DESCRIPTION
wallet-notes-tag-rename for lightning CLI (FEAT-1803).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
