.TH "LIGHTNING-WALLET_NOTES_UPDATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-update \- FEAT-1428 wallet-notes-update
.SH SYNOPSIS
.B lightning wallet-notes-update
.SH DESCRIPTION
wallet-notes-update for lightning CLI (FEAT-1428).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
