.TH "LIGHTNING-CHANNEL-SHORT-ID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-short-id \- FEAT-1975 verb
.SH SYNOPSIS
.B lightning channel-short-id
.SH DESCRIPTION
verb for lightning CLI (FEAT-1975).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
