.TH LIGHTNING-PEER-RECEIVABLE-BALANCE-SKEWNESS-MONTHLY 1
.SH NAME
lightning-peer-receivable-balance-skewness-monthly \- skewness of peer receivable balances over the past month
.SH SYNOPSIS
lightning peer-receivable-balance-skewness-monthly
.SH DESCRIPTION
Returns the skewness of peer receivable balances over the past month.
.SH SEE ALSO
lightning(1)
