.TH "LIGHTNING-NODE-WATCHTOWER-STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-watchtower-status \- show watchtower configuration
.SH SYNOPSIS
.B lightning node-watchtower-status
.SH DESCRIPTION
Returns whether watchtower is configured in the node's settings.
.PP
Output:
.nf
{"watchtower_enabled":bool, "config":{...}}
.fi
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-node-check-config (1)
