.TH "LIGHTNING-NODE_GRAPH_CONNECTED_NODES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-connected-nodes \- FEAT-1714 node-graph-connected-nodes
.SH SYNOPSIS
.B lightning node-graph-connected-nodes
.SH DESCRIPTION
node-graph-connected-nodes for lightning CLI (FEAT-1714).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
