.TH "LIGHTNING-WALLET_META_HAS_KEY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-meta-has-key \- FEAT-1648 wallet-meta-has-key
.SH SYNOPSIS
.B lightning wallet-meta-has-key
.SH DESCRIPTION
wallet-meta-has-key for lightning CLI (FEAT-1648).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
