.TH "LIGHTNING-CHANNEL-HTLC-IN-FLIGHT-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-htlc-in-flight-count \- FEAT-2170 verb
.SH SYNOPSIS
.B lightning channel-htlc-in-flight-count
.SH DESCRIPTION
verb for lightning CLI (FEAT-2170).
.PP
Returns count of current in-flight HTLCs across all peer channels. Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
