.TH "LIGHTNING-NODE_INVOICE_STATS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-stats \- show invoice statistics
.SH SYNOPSIS
.B lightning node-invoice-stats
.SH DESCRIPTION
Show invoice statistics.
.PP
Output: JSON object from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
