.TH "LIGHTNING-NODE_PAYMENT_AMOUNT_TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-payment-amount-total \- FEAT-754 node-payment-amount-total verb
.SH SYNOPSIS
.B lightning node-payment-amount-total
.SH DESCRIPTION
node-payment-amount-total verb for lightning CLI (FEAT-754).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
