.TH "LIGHTNING-NODE-LISTFORWARDS-PENDING-COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-pending-count \- FEAT-2301 count of pending/offered forwards
.SH SYNOPSIS
.B lightning node-listforwards-pending-count
.SH DESCRIPTION
Count of pending/offered forwards for lightning CLI (FEAT-2301).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
