.TH "LIGHTNING-NODE-PAY-COUNT-7D" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-count-7d \- FEAT-2326 verb
.SH SYNOPSIS
.B lightning node-pay-count-7d
.SH DESCRIPTION
node-pay-count-7d for lightning CLI (FEAT-2326).
.PP
Output: JSON from CLN with count of complete pays in last 7 days.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
