.TH "LIGHTNING-WALLET_MIGRATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-migrate \- FEAT-663 wallet-migrate verb
.SH SYNOPSIS
.B lightning wallet-migrate
.SH DESCRIPTION
wallet-migrate verb for lightning CLI (FEAT-663).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
