.TH "LIGHTNING-INVOICE-BOLT12-DECODE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-bolt12-decode \- decode a BOLT 12 offer or invoice
.SH SYNOPSIS
.B lightning invoice-bolt12-decode
.I bolt12
.SH DESCRIPTION
Decodes a BOLT 12 string (offer or invoice) via
.BR decode .
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning-invoice-decode (1),
.BR lightning-node-offers-list (1)
