.TH "LIGHTNING-NODE_ROUTING_TABLE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-routing-table \- show fee policies from the gossip graph
.SH SYNOPSIS
.B lightning node-routing-table

.SH DESCRIPTION
Returns fee policies from the gossip channel graph, limited to N entries.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
