.TH "LIGHTNING-CHANNEL_STATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-state \- FEAT-654 channel-state verb
.SH SYNOPSIS
.B lightning channel-state
.SH DESCRIPTION
channel-state verb for lightning CLI (FEAT-654).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
