.TH LIGHTNING-CHANNEL-BOTH-BALANCES-KURTOSIS-MONTHLY 1
.SH NAME
lightning-channel-both-balances-kurtosis-monthly \- monthly kurtosis of both channel balances
.SH SYNOPSIS
lightning channel-both-balances-kurtosis-monthly
.SH DESCRIPTION
Returns the monthly kurtosis of both channel balances in millisatoshis.
.SH OUTPUT
JSON object with key \fBboth_balances_kurtosis_monthly_msat\fR.
