.TH "LIGHTNING-PEER_FIRST_CHANNEL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-first-channel \- FEAT-1117 peer-first-channel
.SH SYNOPSIS
.B lightning peer-first-channel
.SH DESCRIPTION
peer-first-channel for lightning CLI (FEAT-1117).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
