.TH "LIGHTNING-NODE-LISTFORWARDS-AMOUNT-STDDEV" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-amount-stddev \- FEAT-3293 verb
.SH SYNOPSIS
.B lightning node-listforwards-amount-stddev
.SH DESCRIPTION
node-listforwards-amount-stddev for lightning CLI (FEAT-3293).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
