.TH "LIGHTNING-WALLET_TAG_REMOVE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-tag-remove \- remove a tag from a wallet
.SH SYNOPSIS
.B lightning wallet-tag-remove
.SH DESCRIPTION
Remove a tag from a wallet.
.PP
Output: JSON object from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
