.TH "LIGHTNING-WALLET_META_SET" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-meta-set \- set a metadata key-value pair on a wallet
.SH SYNOPSIS
.B lightning wallet-meta-set
.SH DESCRIPTION
Set a metadata key-value pair on a wallet.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
