.TH "LIGHTNING-CHANNEL-CLOSE-COUNT-WEEK" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-count-week \- FEAT-3090 verb
.SH SYNOPSIS
.B lightning channel-close-count-week
.SH DESCRIPTION
channel-close-count-week for lightning CLI (FEAT-3090).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
