.TH "LIGHTNING-NODE_PEER_LIST_IDS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-peer-list-ids \- FEAT-841 node-peer-list-ids
.SH SYNOPSIS
.B lightning node-peer-list-ids
.SH DESCRIPTION
node-peer-list-ids for lightning CLI (FEAT-841).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
