.TH "LIGHTNING-NODE_HTLC_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-htlc-count \- FEAT-1059 node-htlc-count
.SH SYNOPSIS
.B lightning node-htlc-count
.SH DESCRIPTION
node-htlc-count for lightning CLI (FEAT-1059).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
