.TH "LIGHTNING-NODE_PAYMENT_STATS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-payment-stats \- FEAT-721 node-payment-stats verb
.SH SYNOPSIS
.B lightning node-payment-stats
.SH DESCRIPTION
node-payment-stats verb for lightning CLI (FEAT-721).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
