.TH "LIGHTNING-PEER_NODE_ID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-node-id \- look up node ID by alias
.SH SYNOPSIS
.B lightning peer-node-id
.SH DESCRIPTION
Look up node ID by alias.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
