.TH "LIGHTNING-NODE-PAY-FEE-TOTAL-WEEKLY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-fee-total-weekly \- FEAT-2864 node-pay-fee-total-weekly
.SH SYNOPSIS
.B lightning node-pay-fee-total-weekly
.SH DESCRIPTION
Total payment fees this week for lightning CLI (FEAT-2864).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
