.TH "LIGHTNING-CHANNEL-REMOTE-PCT-RANGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-remote-pct-range \- FEAT-3147 verb
.SH SYNOPSIS
.B lightning channel-remote-pct-range
.SH DESCRIPTION
channel-remote-pct-range for lightning CLI (FEAT-3147).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
