.TH "LIGHTNING-CHANNEL_BALANCE_RATIO" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-balance-ratio \- FEAT-1746 channel-balance-ratio
.SH SYNOPSIS
.B lightning channel-balance-ratio
.SH DESCRIPTION
channel-balance-ratio for lightning CLI (FEAT-1746).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
