.TH "LIGHTNING-CHANNEL_BALANCE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-balance \- FEAT-1566 channel-balance
.SH SYNOPSIS
.B lightning channel-balance
.SH DESCRIPTION
channel-balance for lightning CLI (FEAT-1566).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
