.TH "LIGHTNING-CHANNEL-CLOSE-COUNT-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-count-total \- FEAT-3094 verb
.SH SYNOPSIS
.B lightning channel-close-count-total
.SH DESCRIPTION
channel-close-count-total for lightning CLI (FEAT-3094).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
