.TH "LIGHTNING-NODE_LISTCHANNELS_ENABLED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listchannels-enabled \- FEAT-1884 node-listchannels-enabled
.SH SYNOPSIS
.B lightning node-listchannels-enabled
.SH DESCRIPTION
node-listchannels-enabled for lightning CLI (FEAT-1884).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
