.TH "LIGHTNING-PEER_REMOTE_BALANCE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-remote-balance \- FEAT-1827 peer-remote-balance
.SH SYNOPSIS
.B lightning peer-remote-balance
.SH DESCRIPTION
peer-remote-balance for lightning CLI (FEAT-1827).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
