.TH "LIGHTNING-PEER-FEE-PPM-SKEWNESS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-fee-ppm-skewness \- FEAT-3226 verb
.SH SYNOPSIS
.B lightning peer-fee-ppm-skewness
.SH DESCRIPTION
peer-fee-ppm-skewness for lightning CLI (FEAT-3226).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
