.TH "LIGHTNING-WALLET_NOTES_TRIM" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-trim \- FEAT-1863 wallet-notes-trim
.SH SYNOPSIS
.B lightning wallet-notes-trim
.SH DESCRIPTION
wallet-notes-trim for lightning CLI (FEAT-1863).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
