.TH "LIGHTNING-NODE_ONCHAIN_TXS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-onchain-txs \- FEAT-1051 node-onchain-txs
.SH SYNOPSIS
.B lightning node-onchain-txs
.SH DESCRIPTION
node-onchain-txs for lightning CLI (FEAT-1051).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
