.TH "LIGHTNING-NODE_BACKUP_STATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-backup-state \- write static channel backup to a directory
.SH SYNOPSIS
.B lightning node-backup-state\n.RI [ output_dir ]
.SH DESCRIPTION
Writes the static channel backup (SCB) blob to a .bin file in the output directory.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
