.TH "LIGHTNING-NODE_PAY_ROUTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-route \- FEAT-694 node-pay-route verb
.SH SYNOPSIS
.B lightning node-pay-route
.SH DESCRIPTION
node-pay-route verb for lightning CLI (FEAT-694).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
