.TH "LIGHTNING-CHANNEL_CLOSE_TO_ADDR" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-to-addr \- FEAT-1918 channel-close-to-addr
.SH SYNOPSIS
.B lightning channel-close-to-addr
.SH DESCRIPTION
channel-close-to-addr for lightning CLI (FEAT-1918).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
