.TH "LIGHTNING-NODE_PAY_COUNT_BY_DEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-count-by-dest \- FEAT-1631 node-pay-count-by-dest
.SH SYNOPSIS
.B lightning node-pay-count-by-dest
.SH DESCRIPTION
node-pay-count-by-dest for lightning CLI (FEAT-1631).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
