.TH "LIGHTNING-WALLET_TAG_COUNT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-tag-count \- FEAT-1333 wallet-tag-count
.SH SYNOPSIS
.B lightning wallet-tag-count
.SH DESCRIPTION
wallet-tag-count for lightning CLI (FEAT-1333).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
