.TH "LIGHTNING-NODE_GRAPH_AVG_CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-avg-capacity \- FEAT-1639 node-graph-avg-capacity
.SH SYNOPSIS
.B lightning node-graph-avg-capacity
.SH DESCRIPTION
node-graph-avg-capacity for lightning CLI (FEAT-1639).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
