.TH "LIGHTNING-CHANNEL_CLOSE_TYPE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-close-type \- FEAT-1086 channel-close-type
.SH SYNOPSIS
.B lightning channel-close-type
.SH DESCRIPTION
channel-close-type for lightning CLI (FEAT-1086).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
