.TH "LIGHTNING-WALLET_ENCRYPTION_STATUS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-encryption-status \- FEAT-908 wallet-encryption-status
.SH SYNOPSIS
.B lightning wallet-encryption-status
.SH DESCRIPTION
wallet-encryption-status for lightning CLI (FEAT-908).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
