.TH "LIGHTNING-NODE_LNURL_PAY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-lnurl-pay \- fetch an invoice via LNURL
.SH SYNOPSIS
.B lightning node-lnurl-pay
.I lnurl
.SH DESCRIPTION
Fetches an invoice from an LNURL endpoint via CLN's fetchinvoice command.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
