.TH "LIGHTNING-CHANNEL_REESTABLISH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-reestablish \- FEAT-674 channel-reestablish verb
.SH SYNOPSIS
.B lightning channel-reestablish
.SH DESCRIPTION
channel-reestablish verb for lightning CLI (FEAT-674).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
