.TH "LIGHTNING-WALLET_NOTES_CLEAR" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-clear \- FEAT-1138 wallet-notes-clear
.SH SYNOPSIS
.B lightning wallet-notes-clear
.SH DESCRIPTION
wallet-notes-clear for lightning CLI (FEAT-1138).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
