.TH "LIGHTNING-NODE_LISTFORWARDS_RATE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-rate \- FEAT-1889 node-listforwards-rate
.SH SYNOPSIS
.B lightning node-listforwards-rate
.SH DESCRIPTION
node-listforwards-rate for lightning CLI (FEAT-1889).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
