.TH "LIGHTNING-CHANNEL_POLICY_REMOTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-policy-remote \- FEAT-946 channel-policy-remote
.SH SYNOPSIS
.B lightning channel-policy-remote
.SH DESCRIPTION
channel-policy-remote for lightning CLI (FEAT-946).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
