.TH "LIGHTNING-NODE_GRAPH_CHANNEL_FEES" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-channel-fees \- FEAT-1584 node-graph-channel-fees
.SH SYNOPSIS
.B lightning node-graph-channel-fees
.SH DESCRIPTION
node-graph-channel-fees for lightning CLI (FEAT-1584).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
