.TH "LIGHTNING-NODE_PAY_ROUTE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-route \- FEAT-1111 node-pay-route
.SH SYNOPSIS
.B lightning node-pay-route
.SH DESCRIPTION
node-pay-route for lightning CLI (FEAT-1111).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
