.TH "LIGHTNING-NODE-GRAPH-MIN-CAPACITY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-min-capacity \- FEAT-1959 verb
.SH SYNOPSIS
.B lightning node-graph-min-capacity
.SH DESCRIPTION
node-graph-min-capacity verb for lightning CLI (FEAT-1959).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
