.TH "LIGHTNING-INVOICE_DESCRIPTION" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-description \- FEAT-695 invoice-description verb
.SH SYNOPSIS
.B lightning invoice-description
.SH DESCRIPTION
invoice-description verb for lightning CLI (FEAT-695).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
