.TH "LIGHTNING-WALLET_HISTORY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-history \- FEAT-1178 wallet-history
.SH SYNOPSIS
.B lightning wallet-history
.SH DESCRIPTION
wallet-history for lightning CLI (FEAT-1178).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
