.TH "LIGHTNING-NODE_LISTPAYS_COMPLETE_FEE_MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpays-complete-fee-max \- FEAT-2211 max fee of complete pays
.SH SYNOPSIS
.B lightning node-listpays-complete-fee-max
.SH DESCRIPTION
max fee of complete pays for the lightning CLI (FEAT-2211).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
