.TH "LIGHTNING-INVOICE_CREATE_LABEL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-create-label \- FEAT-1075 invoice-create-label
.SH SYNOPSIS
.B lightning invoice-create-label
.SH DESCRIPTION
invoice-create-label for lightning CLI (FEAT-1075).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
