.TH "LIGHTNING-CHANNEL_MAX_INFLIGHT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-max-inflight \- FEAT-840 channel-max-inflight verb
.SH SYNOPSIS
.B lightning channel-max-inflight
.SH DESCRIPTION
channel-max-inflight verb for lightning CLI (FEAT-840).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
