.TH "LIGHTNING-WALLET_NOTE_EXISTS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-note-exists \- FEAT-1298 wallet-note-exists
.SH SYNOPSIS
.B lightning wallet-note-exists
.SH DESCRIPTION
wallet-note-exists for lightning CLI (FEAT-1298).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
