.TH "LIGHTNING-NODE_LISTPEERS_UNCONNECTED" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listpeers-unconnected \- FEAT-1121 node-listpeers-unconnected
.SH SYNOPSIS
.B lightning node-listpeers-unconnected
.SH DESCRIPTION
node-listpeers-unconnected for lightning CLI (FEAT-1121).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
