.TH "LIGHTNING-CHANNEL_TOTAL_BALANCE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-total-balance \- FEAT-1676 channel-total-balance
.SH SYNOPSIS
.B lightning channel-total-balance
.SH DESCRIPTION
channel-total-balance for lightning CLI (FEAT-1676).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
