.TH "LIGHTNING-CHANNEL_RECEIVABLE_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-receivable-msat \- FEAT-1806 channel-receivable-msat
.SH SYNOPSIS
.B lightning channel-receivable-msat
.SH DESCRIPTION
channel-receivable-msat for lightning CLI (FEAT-1806).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
