.TH "LIGHTNING-NODE_GRAPH_SHORT_CHANNEL_IDS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-graph-short-channel-ids \- FEAT-1849 node-graph-short-channel-ids
.SH SYNOPSIS
.B lightning node-graph-short-channel-ids
.SH DESCRIPTION
node-graph-short-channel-ids for lightning CLI (FEAT-1849).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
