.TH "LIGHTNING-CHANNEL_PEER_ALIAS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-peer-alias \- show alias for a peer node
.SH SYNOPSIS
.B lightning channel-peer-alias
.I peer_id
.SH DESCRIPTION
Returns the alias and color for the specified peer from the gossip graph.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
