.TH "LIGHTNING-CHANNEL_IN_FEES_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-in-fees-msat \- FEAT-1382 channel-in-fees-msat
.SH SYNOPSIS
.B lightning channel-in-fees-msat
.SH DESCRIPTION
channel-in-fees-msat for lightning CLI (FEAT-1382).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
