.TH "LIGHTNING-NODE_INVOICE_OVERPAID" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-invoice-overpaid \- FEAT-984 node-invoice-overpaid
.SH SYNOPSIS
.B lightning node-invoice-overpaid
.SH DESCRIPTION
node-invoice-overpaid for lightning CLI (FEAT-984).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
