.TH "LIGHTNING-NODE-LISTFORWARDS-COUNT-TODAY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-count-today \- FEAT-3266 verb
.SH SYNOPSIS
.B lightning node-listforwards-count-today
.SH DESCRIPTION
node-listforwards-count-today for lightning CLI (FEAT-3266).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
