.TH "LIGHTNING-NODE_CHANNELS_SUMMARY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-channels-summary \- FEAT-671 node-channels-summary verb
.SH SYNOPSIS
.B lightning node-channels-summary
.SH DESCRIPTION
node-channels-summary verb for lightning CLI (FEAT-671).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
