.TH "LIGHTNING-NODE_HTLC_TIMEOUT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-htlc-timeout \- show max HTLC expiry configuration
.SH SYNOPSIS
.B lightning node-htlc-timeout
.SH DESCRIPTION
Show max HTLC expiry configuration.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
