.TH "LIGHTNING-CHANNEL_AGE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-age \- FEAT-786 channel-age verb
.SH SYNOPSIS
.B lightning channel-age
.SH DESCRIPTION
channel-age verb for lightning CLI (FEAT-786).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
