.TH "LIGHTNING-NODE-LISTINVOICES-PAID-AMOUNT-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listinvoices-paid-amount-total \- FEAT-2379 total amount_received_msat of paid invoices
.SH SYNOPSIS
.B lightning node-listinvoices-paid-amount-total
.SH DESCRIPTION
Total amount_received_msat of paid invoices for lightning CLI (FEAT-2379).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
