.TH "LIGHTNING-NODE-LISTFORWARDS-FEE-AVG-MONTHLY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-listforwards-fee-avg-monthly \- FEAT-3336 verb
.SH SYNOPSIS
.B lightning node-listforwards-fee-avg-monthly
.SH DESCRIPTION
node-listforwards-fee-avg-monthly for lightning CLI (FEAT-3336).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
