.TH "LIGHTNING-PEER_PAY_HISTORY" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-pay-history \- FEAT-1167 peer-pay-history
.SH SYNOPSIS
.B lightning peer-pay-history
.SH DESCRIPTION
peer-pay-history for lightning CLI (FEAT-1167).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
