.TH "LIGHTNING-WALLET_PATH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-path \- print filesystem path of a wallet
.SH SYNOPSIS
.B lightning wallet-path
.I <arg>
.SH DESCRIPTION
Returns the filesystem path of the named wallet and whether it exists.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
