.TH "LIGHTNING-CHANNEL_TOTAL_IN_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-total-in-msat \- FEAT-1522 channel-total-in-msat
.SH SYNOPSIS
.B lightning channel-total-in-msat
.SH DESCRIPTION
channel-total-in-msat for lightning CLI (FEAT-1522).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
