.TH "LIGHTNING-PEER-FEE-BASE-AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-fee-base-avg \- FEAT-2278 average fee_base_msat of own channels grouped by peer
.SH SYNOPSIS
.B lightning peer-fee-base-avg
.SH DESCRIPTION
peer-fee-base-avg for lightning CLI (FEAT-2278).
.PP
Output: JSON from CLN. Returns a mapping of peer_id to average fee_base_msat across channels with that peer.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
