.TH "LIGHTNING-CHANNEL_THEIR_RESERVE_MSAT" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-their-reserve-msat \- FEAT-1336 channel-their-reserve-msat
.SH SYNOPSIS
.B lightning channel-their-reserve-msat
.SH DESCRIPTION
channel-their-reserve-msat for lightning CLI (FEAT-1336).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
