.TH "LIGHTNING-WALLET_NOTES_FIND_VALUE" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-notes-find-value \- FEAT-1663 wallet-notes-find-value
.SH SYNOPSIS
.B lightning wallet-notes-find-value
.SH DESCRIPTION
wallet-notes-find-value for lightning CLI (FEAT-1663).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
