.TH "LIGHTNING-CHANNEL_OPEN_DUAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-open-dual \- open a dual-funded channel
.SH SYNOPSIS
.B lightning channel-open-dual
.I peer_id amount_sat
.SH DESCRIPTION
Initiates a dual-funded channel open via CLN's openchannel_init command.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
