.TH "LIGHTNING-CHANNEL_MAX_PENDING_HTLCS" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-max-pending-htlcs \- FEAT-1022 channel-max-pending-htlcs
.SH SYNOPSIS
.B lightning channel-max-pending-htlcs
.SH DESCRIPTION
channel-max-pending-htlcs for lightning CLI (FEAT-1022).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
