.TH "LIGHTNING-WALLET_RENAME_LABEL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-wallet-rename-label \- update the display label of a wallet
.SH SYNOPSIS
.B lightning wallet-rename-label
.SH DESCRIPTION
Update the display label of a wallet.
.PP
Output: JSON object or array from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
