.TH "LIGHTNING-NODE_PAY_AMOUNT_AVG" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-pay-amount-avg \- FEAT-1651 node-pay-amount-avg
.SH SYNOPSIS
.B lightning node-pay-amount-avg
.SH DESCRIPTION
node-pay-amount-avg for lightning CLI (FEAT-1651).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
