.TH "LIGHTNING-PEER-FEE-BASE-MAX" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-peer-fee-base-max \- FEAT-2478 peer-fee-base-max
.SH SYNOPSIS
.B lightning peer-fee-base-max
.SH DESCRIPTION
Peer channel with the highest fee_base_msat (FEAT-2478).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
