.TH "LIGHTNING-INVOICE_PAYMENT_HASH" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-invoice-payment-hash \- FEAT-985 invoice-payment-hash
.SH SYNOPSIS
.B lightning invoice-payment-hash
.SH DESCRIPTION
invoice-payment-hash for lightning CLI (FEAT-985).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
