.TH "LIGHTNING-CHANNEL-CSV-DELAY-TOTAL" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-channel-csv-delay-total \- FEAT-1995 verb
.SH SYNOPSIS
.B lightning channel-csv-delay-total
.SH DESCRIPTION
channel-csv-delay-total for lightning CLI (FEAT-1995).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
