.TH "LIGHTNING-NODE_PAYMENT_LATEST" 1 "May 2026" "lightning 0.6.0" "User Commands"
.SH NAME
lightning-node-payment-latest \- FEAT-971 node-payment-latest
.SH SYNOPSIS
.B lightning node-payment-latest
.SH DESCRIPTION
node-payment-latest for lightning CLI (FEAT-971).
.PP
Output: JSON from CLN.
.SH EXIT STATUS
.TP
.B 0
Always.
.SH SEE ALSO
.BR lightning(1)
